import { StyleSheet } from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.card,
    },
    backBtn: {
      width: 40,
      height: 40,
      justifyContent: 'center',
      alignItems: 'flex-start',
    },
    headerTitle: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 18,
      color: colors.text,
      textAlign: 'center',
    },
    headerRightPlaceholder: {
      width: 40,
    },
    scrollContent: {
      paddingHorizontal: 20,
      paddingTop: 24,
      paddingBottom: 120,
    },
    avatarSection: {
      alignItems: 'center',
      marginBottom: 24,
    },
    avatarContainer: {
      position: 'relative',
      width: 96,
      height: 96,
      borderRadius: 48,
      backgroundColor: colors.isDark ? colors.surface : colors.slate[100],
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 12,
    },
    avatarImage: {
      width: 96,
      height: 96,
      borderRadius: 48,
    },
    cameraBadge: {
      position: 'absolute',
      bottom: 2,
      right: 2,
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: colors.card,
    },
    changePhotoBtn: {
      marginBottom: 4,
    },
    changePhotoText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.primary,
      fontSize: 15,
      textAlign: 'center',
    },
    changePhotoSub: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.textMuted,
      fontSize: 12.5,
      textAlign: 'center',
    },
    formGroup: {
      marginBottom: 20,
    },
    label: {
      fontFamily: colors.fonts.sora.semiBold,
      fontSize: 14,
      color: colors.text,
      marginBottom: 8,
    },
    inputBox: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.card,
      borderWidth: 1.5,
      borderColor: colors.border,
      borderRadius: 16,
      paddingHorizontal: 16,
      height: 56,
    },
    inputBoxFocused: {
      borderColor: colors.primary,
      backgroundColor: colors.isDark ? colors.surface : colors.card,
    },
    inputIcon: {
      marginRight: 10,
      alignSelf: 'center',
    },
    inputText: {
      fontFamily: colors.fonts.sora.medium,
      flex: 1,
      height: '100%',
      fontSize: 15,
      color: colors.text,
      paddingVertical: 0,
      textAlignVertical: 'center',
      includeFontPadding: false,
    },
    margin10: {
      marginTop: 3,
    },
    helperText: {
      fontFamily: colors.fonts.sora.regular,
      fontSize: 12,
      color: colors.textMuted,
      marginTop: 6,
    },
    genderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 4,
    },
    genderChip: {
      flex: 1,
      height: 48,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.card,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 8,
    },
    genderChipLast: {
      marginRight: 0,
    },
    genderChipActive: {
      borderColor: colors.primary,
      backgroundColor: colors.isDark ? colors.alpha.orange20 : colors.orange.subtleBg,
    },
    genderChipText: {
      fontFamily: colors.fonts.sora.semiBold,
      fontSize: 14,
      color: colors.text,
    },
    genderChipTextActive: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.primary,
    },
    verifiedCard: {
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 16,
      padding: 16,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    verifiedCardLeft: {
      flex: 1,
      marginRight: 12,
    },
    verifiedCardLabel: {
      fontFamily: colors.fonts.sora.regular,
      fontSize: 12,
      color: colors.textMuted,
      marginBottom: 2,
    },
    verifiedCardValue: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 15.5,
      color: colors.text,
      marginBottom: 4,
    },
    verifiedStatusRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    verifiedStatusText: {
      fontFamily: colors.fonts.sora.regular,
      fontSize: 12,
      color: colors.textMuted,
      marginLeft: 4,
    },
    chipButton: {
      backgroundColor: colors.isDark ? colors.alpha.orange20 : colors.orange.subtleBg,
      paddingVertical: 6,
      paddingHorizontal: 14,
      borderRadius: 14,
    },
    chipButtonText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.primary,
      fontSize: 13,
    },
    securityBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingVertical: 10,
      paddingHorizontal: 14,
      marginTop: 8,
      marginBottom: 20,
    },
    securityText: {
      fontFamily: colors.fonts.sora.regular,
      flex: 1,
      fontSize: 12,
      color: colors.textMuted,
      marginLeft: 8,
    },
    bottomBar: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: colors.card,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      paddingHorizontal: 20,
      paddingTop: 12,
      flexDirection: 'row',
      alignItems: 'center',
      shadowColor: colors.isDark ? colors.black : colors.navy[900],
      shadowOffset: { width: 0, height: -3 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 10,
    },
    cancelButton: {
      flex: 1,
      height: 52,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    cancelButtonText: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 16,
      color: colors.text,
    },
    saveButton: {
      flex: 1.5,
      height: 52,
      borderRadius: 16,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    saveButtonText: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 16,
      color: colors.white,
    },
  });
}
