import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.white || '#FFFFFF',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.alpha?.border || '#F1F5F9',
      backgroundColor: colors.white || '#FFFFFF',
    },
    backBtn: {
      width: 40,
      height: 40,
      justifyContent: 'center',
      alignItems: 'flex-start',
    },
    headerTitle: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 18,
      color: colors.navy?.[900] || '#0F1E36',
      textAlign: 'center',
    },
    headerRightPlaceholder: {
      width: 40,
    },
    scrollContent: {
      paddingHorizontal: 20,
      paddingTop: 24,
      paddingBottom: 120,
    },
    avatarSection: {
      alignItems: 'center',
      marginBottom: 24,
    },
    avatarContainer: {
      position: 'relative',
      width: 96,
      height: 96,
      borderRadius: 48,
      backgroundColor: '#EFF4F9',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 12,
    },
    avatarImage: {
      width: 96,
      height: 96,
      borderRadius: 48,
    },
    cameraBadge: {
      position: 'absolute',
      bottom: 2,
      right: 2,
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.orange?.[600] || '#FF5500',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: colors.white || '#FFFFFF',
    },
    changePhotoBtn: {
      marginBottom: 4,
    },
    changePhotoText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.orange?.[600] || '#FF5500',
      fontSize: 15,
      textAlign: 'center',
    },
    changePhotoSub: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.textMuted || '#64748B',
      fontSize: 12.5,
      textAlign: 'center',
    },
    formGroup: {
      marginBottom: 20,
    },
    label: {
      fontFamily: colors.fonts.sora.semiBold,
      fontSize: 14,
      color: colors.navy?.[900] || '#1E293B',
      marginBottom: 8,
    },
    inputBox: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.white || '#FFFFFF',
      borderWidth: 1,
      borderColor: '#E2E8F0',
      borderRadius: 16,
      paddingHorizontal: 16,
      height: 56,
    },
    inputBoxFocused: {
      borderColor: colors.orange?.[500] || '#FF6600',
    },
    inputIcon: {
      marginRight: 10,
    },
    inputText: {
      fontFamily: colors.fonts.sora.medium,
      flex: 1,
      fontSize: 15,
      color: colors.navy?.[900] || '#0F1E36',
      paddingVertical: 0,
    },
    helperText: {
      fontFamily: colors.fonts.sora.regular,
      fontSize: 12,
      color: colors.textMuted || '#64748B',
      marginTop: 6,
    },
    genderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 4,
    },
    genderChip: {
      flex: 1,
      height: 48,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: '#E2E8F0',
      backgroundColor: colors.white || '#FFFFFF',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 8,
    },
    genderChipLast: {
      marginRight: 0,
    },
    genderChipActive: {
      borderColor: colors.orange?.[500] || '#FF6600',
      backgroundColor: '#FFF7ED',
    },
    genderChipText: {
      fontFamily: colors.fonts.sora.semiBold,
      fontSize: 14,
      color: colors.navy?.[900] || '#1E293B',
    },
    genderChipTextActive: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.orange?.[600] || '#FF5500',
    },
    verifiedCard: {
      backgroundColor: colors.white || '#FFFFFF',
      borderWidth: 1,
      borderColor: '#E2E8F0',
      borderRadius: 16,
      padding: 16,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    verifiedCardLeft: {
      flex: 1,
      marginRight: 12,
    },
    verifiedCardLabel: {
      fontFamily: colors.fonts.sora.regular,
      fontSize: 12,
      color: colors.textMuted || '#64748B',
      marginBottom: 2,
    },
    verifiedCardValue: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 15.5,
      color: colors.navy?.[900] || '#0F1E36',
      marginBottom: 4,
    },
    verifiedStatusRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    verifiedStatusText: {
      fontFamily: colors.fonts.sora.regular,
      fontSize: 12,
      color: colors.textMuted || '#64748B',
      marginLeft: 4,
    },
    chipButton: {
      backgroundColor: '#FFF1E7',
      paddingVertical: 6,
      paddingHorizontal: 14,
      borderRadius: 14,
    },
    chipButtonText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.orange?.[600] || '#FF5500',
      fontSize: 13,
    },
    securityBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#F8FAFC',
      borderWidth: 1,
      borderColor: '#E2E8F0',
      borderRadius: 12,
      paddingVertical: 10,
      paddingHorizontal: 14,
      marginTop: 8,
      marginBottom: 20,
    },
    securityText: {
      fontFamily: colors.fonts.sora.regular,
      flex: 1,
      fontSize: 12,
      color: colors.textMuted || '#64748B',
      marginLeft: 8,
    },
    bottomBar: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: colors.white || '#FFFFFF',
      borderTopWidth: 1,
      borderTopColor: '#F1F5F9',
      paddingHorizontal: 20,
      paddingTop: 12,
      flexDirection: 'row',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: -3},
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 10,
    },
    cancelButton: {
      flex: 1,
      height: 52,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#CBD5E1',
      backgroundColor: colors.white || '#FFFFFF',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    cancelButtonText: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 16,
      color: colors.navy?.[900] || '#0F1E36',
    },
    saveButton: {
      flex: 1.5,
      height: 52,
      borderRadius: 16,
      backgroundColor: colors.orange?.[600] || '#FF5500',
      justifyContent: 'center',
      alignItems: 'center',
    },
    saveButtonText: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 16,
      color: colors.white || '#FFFFFF',
    },
  });
}
