import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 12,
      paddingBottom: 10,
      backgroundColor: colors.background,
    },
    headerBtn: {
      width: 44,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      color: colors.text,
      fontSize: 17,
      fontWeight: '700',
    },
    scroll: {
      paddingHorizontal: 16,
      paddingTop: 8,
    },
    mapCard: {
      borderRadius: 18,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 18,
      backgroundColor: colors.map.land,
    },
    mapBg: {
      height: 210,
      backgroundColor: colors.map.land,
    },
    roadH: {
      position: 'absolute',
      top: '48%',
      left: 0,
      right: 0,
      height: 8,
      backgroundColor: colors.map.road,
    },
    roadV: {
      position: 'absolute',
      top: 0,
      bottom: 0,
      left: '40%',
      width: 8,
      backgroundColor: colors.map.roadAlt,
    },
    park: {
      position: 'absolute',
      top: 18,
      right: 24,
      width: 70,
      height: 48,
      borderRadius: 10,
      backgroundColor: colors.map.park,
    },
    routeLine: {
      position: 'absolute',
      left: '22%',
      top: '58%',
      width: '48%',
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.orange[500],
      transform: [{rotate: '-18deg'}],
    },
    startPin: {
      position: 'absolute',
      left: '18%',
      top: '52%',
      width: 28,
      height: 28,
      borderRadius: 8,
      backgroundColor: colors.orange[500],
      alignItems: 'center',
      justifyContent: 'center',
    },
    endPin: {
      position: 'absolute',
      right: '18%',
      top: '28%',
    },
    etaPill: {
      position: 'absolute',
      left: 12,
      bottom: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.card,
      borderRadius: 999,
      paddingVertical: 10,
      paddingHorizontal: 12,
      maxWidth: '88%',
      shadowColor: colors.navy[900],
      shadowOpacity: 0.08,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 2},
      elevation: 3,
    },
    etaText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '700',
    },
    sectionLabel: {
      color: colors.muted,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1.1,
      marginBottom: 12,
    },
    contactsRow: {
      flexDirection: 'row',
      gap: 14,
      marginBottom: 18,
    },
    contactItem: {
      alignItems: 'center',
      width: 64,
    },
    avatar: {
      width: 54,
      height: 54,
      borderRadius: 27,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 6,
      borderWidth: 2.5,
    },
    avatarSelected: {
      backgroundColor: colors.isDark ? colors.navy.cardBg : colors.navy[800],
      borderColor: colors.orange[500],
    },
    avatarMuted: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
    },
    avatarText: {
      color: colors.white,
      fontSize: 14,
      fontWeight: '800',
    },
    avatarTextMuted: {
      color: colors.muted,
    },
    addAvatar: {
      width: 54,
      height: 54,
      borderRadius: 27,
      borderWidth: 1.5,
      borderStyle: 'dashed',
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 6,
      backgroundColor: colors.card,
    },
    contactName: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '600',
    },
    contactNameMuted: {
      color: colors.muted,
      fontSize: 12,
      fontWeight: '600',
    },
    orLabel: {
      color: colors.muted,
      fontSize: 13,
      fontWeight: '500',
      marginBottom: 8,
    },
    phoneRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: 14,
      paddingLeft: 14,
      paddingRight: 6,
      paddingVertical: 6,
      marginBottom: 16,
      gap: 8,
    },
    phoneInput: {
      flex: 1,
      color: colors.text,
      fontSize: 15,
      fontWeight: '600',
      padding: 0,
      margin: 0,
    },
    sendBtn: {
      backgroundColor: colors.orange[500],
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    sendText: {
      color: colors.white,
      fontSize: 14,
      fontWeight: '700',
    },
    linkCard: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 14,
      marginBottom: 12,
    },
    linkLabel: {
      color: colors.muted,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1.1,
      marginBottom: 10,
    },
    linkRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    linkText: {
      flex: 1,
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
    },
    copyBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    copyText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '700',
    },
    infoBanner: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      backgroundColor: colors.isDark ? colors.alpha.blue18 : colors.blue[100],
      borderRadius: 14,
      paddingVertical: 12,
      paddingHorizontal: 14,
    },
    infoText: {
      flex: 1,
      color: colors.isDark ? colors.text : colors.navy[800],
      fontSize: 13,
      fontWeight: '500',
      lineHeight: 19,
    },
    footer: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      paddingHorizontal: 16,
      paddingTop: 10,
      backgroundColor: colors.background,
    },
    shareBtn: {
      backgroundColor: colors.orange[500],
      borderRadius: 16,
      paddingVertical: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    shareText: {
      color: colors.white,
      fontSize: 16,
      fontWeight: '700',
    },
  });
}

