import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.map.land,
    },
    map: {
      ...StyleSheet.absoluteFillObject,
    },
    mapRoadH: {
      position: 'absolute',
      height: 10,
      left: 0,
      right: 0,
      backgroundColor: colors.map.road,
    },
    mapRoadV: {
      position: 'absolute',
      width: 10,
      top: 0,
      bottom: 0,
      backgroundColor: colors.map.road,
    },
    mapRoadAlt: {
      backgroundColor: colors.map.roadAlt,
    },
    mapLabel: {
      fontFamily: colors.fonts.sora.bold,
      position: 'absolute',
      color: colors.muted,
      fontSize: 11,
      letterSpacing: 1.2,
    },
    water: {
      position: 'absolute',
      backgroundColor: colors.map.water,
      borderRadius: 40,
      opacity: 0.7,
    },
    park: {
      position: 'absolute',
      backgroundColor: colors.map.park,
      borderRadius: 16,
      opacity: 0.85,
    },
    building: {
      position: 'absolute',
      backgroundColor: colors.map.building,
      borderRadius: 6,
    },
    banner: {
      position: 'absolute',
      left: 16,
      right: 16,
      zIndex: 2,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: 14,
      backgroundColor: colors.isDark ? colors.alpha.orange18 : colors.orange[100],
      borderWidth: 1,
      borderColor: colors.isDark ? colors.alpha.orange30 : colors.orange[200],
    },
    bannerText: {
      fontFamily: colors.fonts.sora.semiBold,
      flex: 1,
      color: colors.text,
      fontSize: 13,
      lineHeight: 18,
    },
    sheet: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: colors.card,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingHorizontal: 22,
      paddingTop: 22,
      shadowColor: colors.shadow || colors.navy[900],
      shadowOpacity: 0.12,
      shadowRadius: 18,
      shadowOffset: {width: 0, height: -4},
      elevation: 16,
    },
    iconBadge: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.isDark ? colors.alpha.orange18 : colors.orange[100],
      marginBottom: 16,
    },
    title: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 26,
      letterSpacing: -0.4,
      marginBottom: 8,
    },
    body: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.gray[500],
      fontSize: 14,
      lineHeight: 21,
      marginBottom: 18,
    },
    benefitRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginBottom: 12,
    },
    benefitIcon: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surface,
    },
    benefitText: {
      fontFamily: colors.fonts.sora.medium,
      flex: 1,
      color: colors.text,
      fontSize: 14,
      lineHeight: 20,
    },
    actions: {
      marginTop: 18,
      gap: 10,
    },
    linkBtn: {
      alignItems: 'center',
      paddingVertical: 10,
    },
    linkText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.primary,
      fontSize: 15,
    },
    searchWrap: {
      marginBottom: 8,
    },
    placeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingVertical: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    placeIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surface,
    },
    placeCopy: {
      flex: 1,
    },
    placeTitle: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 15,
      marginBottom: 2,
    },
    placeSub: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.gray[500],
      fontSize: 13,
      lineHeight: 18,
    },
    chevron: {
      fontFamily: colors.fonts.sora.light,
      color: colors.gray[400],
      fontSize: 22,
    },
  });
}
