import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 12,
      paddingBottom: 4,
    },
    headerBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      color: colors.text,
      fontSize: 17,
      fontWeight: '700',
    },
    progressWrap: {
      paddingHorizontal: 20,
      marginTop: 12,
      marginBottom: 16,
    },
    progressTrack: {
      flexDirection: 'row',
      gap: 6,
      marginBottom: 8,
    },
    progressSeg: {
      flex: 1,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.border,
    },
    progressSegActive: {
      backgroundColor: colors.primary,
    },
    stepText: {
      color: colors.muted,
      fontSize: 12,
      fontWeight: '500',
    },
    scroll: {
      paddingHorizontal: 20,
      paddingTop: 2,
    },
    heroCard: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      backgroundColor: colors.isDark ? colors.alpha.orange14 : colors.orange[50],
      borderWidth: 1,
      borderColor: colors.isDark ? colors.alpha.orange35 : colors.orange[200],
      borderRadius: 16,
      padding: 14,
      marginBottom: 20,
    },
    heroIcon: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: colors.isDark ? colors.alpha.orange25 : colors.orange[100],
      alignItems: 'center',
      justifyContent: 'center',
    },
    heroCopy: {
      flex: 1,
      minWidth: 0,
    },
    heroTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
    },
    heroBody: {
      color: colors.isDark ? colors.orange[300] : colors.orange[700],
      fontSize: 13,
      fontWeight: '400',
      marginTop: 3,
      lineHeight: 18,
    },
    section: {
      marginBottom: 18,
    },
    sectionLabel: {
      color: colors.muted,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1.1,
      marginBottom: 10,
    },
    card: {
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
    },
    placeRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      paddingBottom: 12,
    },
    placeDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      marginTop: 5,
    },
    placeCopy: {
      flex: 1,
      minWidth: 0,
    },
    placeTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
    },
    placeMeta: {
      color: colors.muted,
      fontSize: 12,
      fontWeight: '400',
      marginTop: 2,
      lineHeight: 17,
    },
    placeInput: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
      padding: 0,
      margin: 0,
    },
    editIconBtn: {
      padding: 4,
      marginTop: -2,
    },
    suggestBox: {
      marginTop: 4,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
      paddingTop: 4,
    },
    suggestRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      paddingVertical: 10,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    suggestRowLast: {
      borderBottomWidth: 0,
    },
    suggestCopy: {
      flex: 1,
      minWidth: 0,
    },
    suggestTitle: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '600',
    },
    suggestMeta: {
      color: colors.muted,
      fontSize: 12,
      fontWeight: '400',
      marginTop: 2,
    },
    suggestEmpty: {
      color: colors.muted,
      fontSize: 13,
      fontWeight: '400',
      paddingVertical: 12,
    },
    divider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.border,
      marginBottom: 12,
    },
    contactRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    contactCopy: {
      flex: 1,
      minWidth: 0,
      color: colors.text,
      fontSize: 13,
      fontWeight: '500',
    },
    youTag: {
      color: colors.muted,
      fontSize: 12,
      fontWeight: '500',
    },
    editText: {
      color: colors.primary,
      fontSize: 14,
      fontWeight: '700',
    },
    noteCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
      marginBottom: 18,
    },
    noteTitle: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 6,
    },
    noteInput: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '400',
      lineHeight: 19,
      padding: 0,
      margin: 0,
      minHeight: 38,
      textAlignVertical: 'top',
    },
    savedScroll: {
      gap: 8,
      paddingRight: 8,
    },
    savedChip: {
      paddingVertical: 9,
      paddingHorizontal: 14,
      borderRadius: 999,
      borderWidth: 1.5,
      borderColor: colors.border,
      backgroundColor: colors.card,
    },
    savedChipActive: {
      borderColor: colors.primary,
      backgroundColor: colors.isDark ? colors.alpha.orange18 : colors.orange[50],
    },
    savedChipText: {
      color: colors.muted,
      fontSize: 13,
      fontWeight: '600',
    },
    savedChipTextActive: {
      color: colors.primary,
      fontWeight: '700',
    },
    footer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      paddingHorizontal: 20,
      paddingTop: 10,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
      backgroundColor: colors.card,
    },
    footerCopy: {
      flex: 1,
      minWidth: 0,
    },
    footerLabel: {
      color: colors.muted,
      fontSize: 12,
      fontWeight: '500',
    },
    footerValue: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
      marginTop: 2,
    },
    continueBtn: {
      backgroundColor: colors.primary,
      paddingVertical: 14,
      paddingHorizontal: 28,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    continueText: {
      color: colors.white,
      fontSize: 16,
      fontWeight: '700',
    },
  });
}
