import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 12,
      paddingBottom: 10,
      backgroundColor: colors.card,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerBtn: {
      minWidth: 56,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      color: colors.text,
      fontSize: 17,
      fontWeight: '700',
    },
    resetText: {
      color: colors.primary,
      fontSize: 15,
      fontWeight: '700',
    },
    scroll: {
      paddingHorizontal: 16,
      paddingTop: 14,
    },
    chipsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 14,
    },
    chip: {
      paddingVertical: 9,
      paddingHorizontal: 14,
      borderRadius: 999,
      borderWidth: 1.5,
      borderColor: colors.border,
      backgroundColor: colors.card,
    },
    chipActive: {
      borderColor: colors.primary,
      backgroundColor: colors.isDark ? colors.alpha.orange18 : colors.orange[50],
    },
    chipText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '600',
    },
    chipTextActive: {
      color: colors.primary,
      fontWeight: '700',
    },
    card: {
      backgroundColor: colors.card,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 16,
      marginBottom: 12,
    },
    monthRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    monthTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '700',
    },
    monthNav: {
      flexDirection: 'row',
      gap: 4,
    },
    navBtn: {
      width: 34,
      height: 34,
      alignItems: 'center',
      justifyContent: 'center',
    },
    weekRow: {
      flexDirection: 'row',
      marginBottom: 6,
    },
    weekLabel: {
      flex: 1,
      textAlign: 'center',
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
    },
    daysGrid: {
      width: '100%',
    },
    weekDaysRow: {
      flexDirection: 'row',
      width: '100%',
    },
    dayCell: {
      flex: 1,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dayInRange: {
      backgroundColor: colors.isDark ? colors.alpha.orange25 : colors.orange[100],
    },
    dayRangeStart: {
      borderTopLeftRadius: 20,
      borderBottomLeftRadius: 20,
      backgroundColor: colors.isDark ? colors.alpha.orange25 : colors.orange[100],
    },
    dayRangeEnd: {
      borderTopRightRadius: 20,
      borderBottomRightRadius: 20,
      backgroundColor: colors.isDark ? colors.alpha.orange25 : colors.orange[100],
    },
    daySelected: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dayText: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '500',
    },
    dayTextMuted: {
      color: colors.isDark ? colors.navy[700] : colors.gray[300],
    },
    dayTextSelected: {
      color: colors.white,
      fontWeight: '700',
    },
    dayTextInRange: {
      color: colors.text,
      fontWeight: '600',
    },
    rangeTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 14,
    },
    rangeLabel: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1.1,
    },
    rangeDays: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '500',
    },
    rangeDates: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    rangeFrom: {
      flex: 1,
    },
    rangeTo: {
      flex: 1,
      alignItems: 'flex-end',
    },
    rangeHint: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '500',
      marginBottom: 4,
    },
    rangeValue: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '800',
      letterSpacing: -0.2,
    },
    summaryCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: colors.isDark ? colors.navy.cardBg4 : colors.orange[50],
      borderWidth: 1,
      borderColor: colors.isDark ? colors.border : colors.orange[200],
      borderRadius: 18,
      paddingVertical: 14,
      paddingHorizontal: 14,
      marginBottom: 12,
    },
    summaryIcon: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.isDark ? colors.alpha.orange20 : colors.orange[100],
      alignItems: 'center',
      justifyContent: 'center',
    },
    summaryCopy: {
      flex: 1,
      minWidth: 0,
    },
    summaryTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
    },
    summaryMeta: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '400',
      marginTop: 3,
      lineHeight: 18,
    },
    toggleCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      backgroundColor: colors.card,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 14,
      paddingHorizontal: 14,
      marginBottom: 12,
    },
    toggleCopy: {
      flex: 1,
      minWidth: 0,
      paddingRight: 4,
    },
    toggleTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
    },
    toggleMeta: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '400',
      marginTop: 3,
      lineHeight: 18,
    },
    switchTrack: {
      width: 52,
      height: 32,
      borderRadius: 16,
      padding: 3,
      justifyContent: 'center',
    },
    switchTrackOn: {
      backgroundColor: colors.primary,
      alignItems: 'flex-end',
    },
    switchTrackOff: {
      backgroundColor: colors.isDark ? colors.navy.borderMuted : colors.gray[300],
      alignItems: 'flex-start',
    },
    switchThumb: {
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: colors.white,
      shadowColor: colors.black,
      shadowOpacity: 0.12,
      shadowRadius: 3,
      shadowOffset: {width: 0, height: 1},
      elevation: 2,
    },
    footer: {
      paddingHorizontal: 16,
      paddingTop: 10,
      backgroundColor: colors.background,
    },
    applyBtn: {
      backgroundColor: colors.primary,
      borderRadius: 16,
      paddingVertical: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    applyText: {
      color: colors.white,
      fontSize: 16,
      fontWeight: '700',
    },
  });
}
