import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingBottom: 12,
      backgroundColor: colors.card,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      fontFamily: colors.fonts.sora.bold,
      flex: 1,
      textAlign: 'center',
      color: colors.text,
      fontSize: 18,
    },
    scroll: {
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    infoCard: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
      marginBottom: 16,
    },
    infoIcon: {
      marginRight: 12,
      marginTop: 2,
    },
    infoBody: {
      flex: 1,
    },
    infoTitle: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 14,
      marginBottom: 3,
    },
    infoSub: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.textMuted,
      fontSize: 12,
      lineHeight: 16,
    },
    sectionLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.textMuted,
      fontSize: 11,
      letterSpacing: 0.8,
      marginBottom: 8,
    },
    formCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 16,
      marginBottom: 16,
    },
    inputGroup: {
      marginBottom: 14,
    },
    inputLabel: {
      fontFamily: colors.fonts.sora.semiBold,
      color: colors.text,
      fontSize: 13,
      marginBottom: 6,
    },
    textInputBox: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: 12,
      height: 48,
      backgroundColor: colors.inputBg || colors.background,
    },
    textInputField: {
      fontFamily: colors.fonts.sora.regular,
      flex: 1,
      color: colors.text,
      fontSize: 14.5,
      paddingVertical: 0,
    },
    phonePrefix: {
      fontFamily: colors.fonts.sora.semiBold,
      color: colors.textMuted,
      fontSize: 14.5,
      marginRight: 8,
    },
    chipRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 4,
    },
    relationChip: {
      paddingHorizontal: 12,
      paddingVertical: 7,
      borderRadius: 20,
      backgroundColor: colors.isDark ? colors.navy[800] : colors.slate[100],
      borderWidth: 1,
      borderColor: colors.border,
    },
    relationChipActive: {
      backgroundColor: colors.isDark ? colors.alpha.orange25 : colors.orange[100],
      borderColor: colors.primary,
    },
    relationChipText: {
      fontFamily: colors.fonts.sora.semiBold,
      fontSize: 12.5,
      color: colors.textMuted,
    },
    relationChipTextActive: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.primary,
    },
    numberCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
      marginBottom: 16,
    },
    toggleCard: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.card,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 8,
    },
    toggleTitle: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.text,
      fontSize: 13,
      flex: 1,
      marginRight: 10,
    },
    toggleTrack: {
      width: 44,
      height: 24,
      borderRadius: 12,
      padding: 2,
      justifyContent: 'center',
    },
    toggleTrackActive: {
      backgroundColor: colors.primary,
    },
    toggleTrackInactive: {
      backgroundColor: colors.isDark ? colors.navy.borderMuted : colors.navy.borderSoft,
    },
    toggleThumb: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: colors.white,
      shadowColor: colors.black,
      shadowOffset: {width: 0, height: 1},
      shadowOpacity: 0.2,
      shadowRadius: 1.5,
      elevation: 2,
    },
    toggleThumbActive: {
      alignSelf: 'flex-end',
    },
    toggleThumbInactive: {
      alignSelf: 'flex-start',
    },
    liveLocationCard: {
      backgroundColor: colors.isDark ? colors.navy.cardBg4 : colors.orange.lightBg,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.isDark ? colors.alpha.orange30 : colors.amber[300],
      padding: 14,
      marginTop: 8,
      marginBottom: 16,
    },
    liveLocationTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
    },
    liveLocationIcon: {
      marginRight: 10,
      marginTop: 2,
    },
    liveLocationBody: {
      flex: 1,
    },
    liveLocationTitle: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.isDark ? colors.orange[450] : colors.orange[850],
      fontSize: 13.5,
      marginBottom: 2,
    },
    liveLocationSub: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.isDark ? colors.navy[300] : colors.amber[900],
      fontSize: 11.5,
      lineHeight: 15,
    },
    shareNowBtn: {
      backgroundColor: colors.primary,
      borderRadius: 14,
      height: 46,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 12,
    },
    shareNowText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.white,
      fontSize: 14.5,
    },
    footer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 16,
      paddingTop: 10,
      backgroundColor: colors.card,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    removeBtn: {
      flex: 1,
      height: 50,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: colors.border,
      backgroundColor: colors.card,
      alignItems: 'center',
      justifyContent: 'center',
    },
    removeBtnText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 15,
    },
    saveBtn: {
      flex: 1,
      height: 50,
      borderRadius: 16,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    saveBtnText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.white,
      fontSize: 15,
    },
  });
}
