import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: '#F3F6FA',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingBottom: 12,
      backgroundColor: '#FFFFFF',
    },
    headerBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      color: '#0F2840',
      fontSize: 18,
      fontWeight: '700',
    },
    scroll: {
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    infoCard: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#E8ECF2',
      padding: 14,
      marginBottom: 16,
    },
    infoIcon: {
      marginRight: 12,
      marginTop: 2,
    },
    infoBody: {
      flex: 1,
    },
    infoTitle: {
      color: '#0F2840',
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 3,
    },
    infoSub: {
      color: '#6E7C91',
      fontSize: 12,
      fontWeight: '400',
      lineHeight: 16,
    },
    sectionLabel: {
      color: '#7E8B9E',
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.8,
      marginBottom: 8,
    },
    numberCard: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#E8ECF2',
      padding: 14,
      marginBottom: 16,
    },
    numberLabel: {
      color: '#8A96A6',
      fontSize: 11.5,
      fontWeight: '500',
      marginBottom: 8,
    },
    numberBox: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderWidth: 1,
      borderColor: '#E8ECF2',
      borderRadius: 12,
      paddingHorizontal: 12,
      height: 46,
      marginBottom: 12,
      backgroundColor: '#FAFCFE',
    },
    numberLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    countryCode: {
      color: '#6E7C91',
      fontSize: 14,
      fontWeight: '600',
    },
    phoneNumber: {
      color: '#0F2840',
      fontSize: 15,
      fontWeight: '700',
    },
    verifiedBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#DCFCE7',
      borderRadius: 20,
      paddingVertical: 4,
      paddingHorizontal: 8,
      gap: 5,
    },
    verifiedDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: '#16A34A',
    },
    verifiedText: {
      color: '#16A34A',
      fontSize: 12,
      fontWeight: '700',
    },
    contactMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingTop: 2,
    },
    contactMetaLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    contactMetaText: {
      color: '#0F2840',
      fontSize: 12.5,
      fontWeight: '500',
    },
    changeLink: {
      color: '#FF7006',
      fontSize: 13,
      fontWeight: '700',
    },
    toggleCard: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: '#FFFFFF',
      borderRadius: 14,
      borderWidth: 1,
      borderColor: '#E8ECF2',
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 8,
    },
    toggleTitle: {
      color: '#0F2840',
      fontSize: 13,
      fontWeight: '500',
      flex: 1,
      marginRight: 10,
    },
    toggleTrack: {
      width: 44,
      height: 24,
      borderRadius: 12,
      padding: 2,
      justifyContent: 'center',
    },
    toggleTrackActive: {
      backgroundColor: '#FF7006',
    },
    toggleTrackInactive: {
      backgroundColor: '#B5BFC9',
    },
    toggleThumb: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: '#FFFFFF',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 1},
      shadowOpacity: 0.2,
      shadowRadius: 1.5,
      elevation: 2,
    },
    toggleThumbActive: {
      alignSelf: 'flex-end',
    },
    toggleThumbInactive: {
      alignSelf: 'flex-start',
    },
    liveLocationCard: {
      backgroundColor: '#FFF7ED',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#FED7AA',
      padding: 14,
      marginTop: 8,
      marginBottom: 16,
    },
    liveLocationTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
    },
    liveLocationIcon: {
      marginRight: 10,
      marginTop: 2,
    },
    liveLocationBody: {
      flex: 1,
    },
    liveLocationTitle: {
      color: '#C2410C',
      fontSize: 13.5,
      fontWeight: '700',
      marginBottom: 2,
    },
    liveLocationSub: {
      color: '#78350F',
      fontSize: 11.5,
      fontWeight: '400',
      lineHeight: 15,
    },
    shareNowBtn: {
      backgroundColor: '#FF7006',
      borderRadius: 14,
      height: 46,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 12,
    },
    shareNowText: {
      color: '#FFFFFF',
      fontSize: 14.5,
      fontWeight: '700',
    },
    footer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 16,
      paddingTop: 10,
      backgroundColor: '#FFFFFF',
      borderTopWidth: 1,
      borderTopColor: '#F0F3F7',
    },
    removeBtn: {
      flex: 1,
      height: 50,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: '#C3CFDF',
      backgroundColor: '#FFFFFF',
      alignItems: 'center',
      justifyContent: 'center',
    },
    removeBtnText: {
      color: '#0F2840',
      fontSize: 15,
      fontWeight: '700',
    },
    saveBtn: {
      flex: 1,
      height: 50,
      borderRadius: 16,
      backgroundColor: '#FF7006',
      alignItems: 'center',
      justifyContent: 'center',
    },
    saveBtnText: {
      color: '#FFFFFF',
      fontSize: 15,
      fontWeight: '700',
    },
  });
}
