import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingBottom: 12,
      backgroundColor: colors.card,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      color: colors.text,
      fontSize: 18,
      fontWeight: '700',
    },
    scroll: {
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    infoCard: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
      marginBottom: 16,
    },
    infoIcon: {
      marginRight: 12,
      marginTop: 2,
    },
    infoBody: {
      flex: 1,
    },
    infoTitle: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 3,
    },
    infoSub: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '400',
      lineHeight: 16,
    },
    sectionLabel: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.8,
      marginBottom: 8,
    },
    numberCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
      marginBottom: 16,
    },
    numberLabel: {
      color: colors.textMuted,
      fontSize: 11.5,
      fontWeight: '500',
      marginBottom: 8,
    },
    numberBox: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: 12,
      height: 46,
      marginBottom: 12,
      backgroundColor: colors.inputBg,
    },
    numberLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    countryCode: {
      color: colors.textMuted,
      fontSize: 14,
      fontWeight: '600',
    },
    phoneNumber: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
    },
    verifiedBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.isDark ? colors.alpha.green25 : colors.green[200],
      borderRadius: 20,
      paddingVertical: 4,
      paddingHorizontal: 8,
      gap: 5,
    },
    verifiedDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.success,
    },
    verifiedText: {
      color: colors.isDark ? colors.green[400] : colors.green[600],
      fontSize: 12,
      fontWeight: '700',
    },
    contactMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingTop: 2,
    },
    contactMetaLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    contactMetaText: {
      color: colors.text,
      fontSize: 12.5,
      fontWeight: '500',
    },
    changeLink: {
      color: colors.primary,
      fontSize: 13,
      fontWeight: '700',
    },
    toggleCard: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.card,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 8,
    },
    toggleTitle: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '500',
      flex: 1,
      marginRight: 10,
    },
    toggleTrack: {
      width: 44,
      height: 24,
      borderRadius: 12,
      padding: 2,
      justifyContent: 'center',
    },
    toggleTrackActive: {
      backgroundColor: colors.primary,
    },
    toggleTrackInactive: {
      backgroundColor: colors.isDark ? colors.navy.borderMuted : colors.navy.borderSoft,
    },
    toggleThumb: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: colors.white,
      shadowColor: colors.black,
      shadowOffset: {width: 0, height: 1},
      shadowOpacity: 0.2,
      shadowRadius: 1.5,
      elevation: 2,
    },
    toggleThumbActive: {
      alignSelf: 'flex-end',
    },
    toggleThumbInactive: {
      alignSelf: 'flex-start',
    },
    liveLocationCard: {
      backgroundColor: colors.isDark ? colors.navy.cardBg4 : colors.orange.lightBg,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.isDark ? colors.alpha.orange30 : colors.amber[300],
      padding: 14,
      marginTop: 8,
      marginBottom: 16,
    },
    liveLocationTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
    },
    liveLocationIcon: {
      marginRight: 10,
      marginTop: 2,
    },
    liveLocationBody: {
      flex: 1,
    },
    liveLocationTitle: {
      color: colors.isDark ? colors.orange[450] : colors.orange[850],
      fontSize: 13.5,
      fontWeight: '700',
      marginBottom: 2,
    },
    liveLocationSub: {
      color: colors.isDark ? colors.navy[300] : colors.amber[900],
      fontSize: 11.5,
      fontWeight: '400',
      lineHeight: 15,
    },
    shareNowBtn: {
      backgroundColor: colors.primary,
      borderRadius: 14,
      height: 46,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 12,
    },
    shareNowText: {
      color: colors.white,
      fontSize: 14.5,
      fontWeight: '700',
    },
    footer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 16,
      paddingTop: 10,
      backgroundColor: colors.card,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    removeBtn: {
      flex: 1,
      height: 50,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: colors.border,
      backgroundColor: colors.card,
      alignItems: 'center',
      justifyContent: 'center',
    },
    removeBtnText: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
    },
    saveBtn: {
      flex: 1,
      height: 50,
      borderRadius: 16,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    saveBtnText: {
      color: colors.white,
      fontSize: 15,
      fontWeight: '700',
    },
  });
}
