import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingBottom: 12,
      backgroundColor: colors.card,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      color: colors.text,
      fontSize: 18,
      fontWeight: '700',
    },
    headerSpacer: {
      width: 40,
    },
    scroll: {
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    ticketCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.isDark ? '#2A2016' : '#FFF6E5',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.isDark ? 'rgba(255, 112, 6, 0.3)' : '#FDE68A',
      padding: 14,
      marginBottom: 16,
    },
    ticketIcon: {
      marginRight: 10,
    },
    ticketBody: {
      flex: 1,
    },
    ticketTitle: {
      color: colors.isDark ? '#FF9A4A' : '#92400E',
      fontSize: 13.5,
      fontWeight: '700',
      marginBottom: 2,
    },
    ticketSub: {
      color: colors.isDark ? '#FDBA74' : '#B45309',
      fontSize: 11.5,
      fontWeight: '500',
    },
    ticketStatus: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    statusDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.isDark ? '#FF9A4A' : '#92400E',
    },
    statusText: {
      color: colors.isDark ? '#FF9A4A' : '#92400E',
      fontSize: 12,
      fontWeight: '700',
    },
    sectionLabel: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.8,
      marginBottom: 8,
    },
    sectionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    charCount: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '500',
    },
    tripCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.card,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 12,
      paddingVertical: 12,
      marginBottom: 16,
    },
    tripIconWrap: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: colors.iconBg,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    tripBody: {
      flex: 1,
    },
    tripTitle: {
      color: colors.text,
      fontSize: 13.5,
      fontWeight: '700',
      marginBottom: 2,
    },
    tripSub: {
      color: colors.textMuted,
      fontSize: 11.5,
      fontWeight: '400',
    },
    categoryDropdown: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.card,
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: colors.primary,
      paddingHorizontal: 14,
      height: 48,
      marginBottom: 10,
    },
    categoryText: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '500',
    },
    subCategoriesWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 16,
    },
    subPill: {
      backgroundColor: colors.card,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 14,
      paddingVertical: 8,
    },
    subPillSelected: {
      backgroundColor: colors.isDark ? 'rgba(255, 112, 6, 0.22)' : '#FFF5ED',
      borderColor: colors.primary,
      borderWidth: 1.5,
    },
    subPillText: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '500',
    },
    subPillTextSelected: {
      color: colors.primary,
      fontWeight: '700',
    },
    textCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
      marginBottom: 16,
      minHeight: 90,
    },
    textInput: {
      color: colors.text,
      fontSize: 12.5,
      lineHeight: 18,
      padding: 0,
      margin: 0,
      textAlignVertical: 'top',
    },
    attachmentsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginBottom: 16,
    },
    fileBox: {
      width: 56,
      height: 56,
      borderRadius: 14,
      backgroundColor: colors.iconBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    addBox: {
      width: 56,
      height: 56,
      borderRadius: 14,
      borderWidth: 1.5,
      borderStyle: 'dashed',
      borderColor: colors.border,
      backgroundColor: colors.card,
      alignItems: 'center',
      justifyContent: 'center',
    },
    addText: {
      color: colors.textMuted,
      fontSize: 10.5,
      fontWeight: '600',
      marginTop: 2,
    },
    footer: {
      paddingHorizontal: 16,
      paddingTop: 10,
      backgroundColor: colors.card,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    submitBtn: {
      backgroundColor: colors.primary,
      borderRadius: 16,
      height: 52,
      alignItems: 'center',
      justifyContent: 'center',
    },
    submitText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '700',
    },
    replyHint: {
      color: colors.textMuted,
      fontSize: 12,
      textAlign: 'center',
      marginTop: 10,
    },
  });
}
