import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingBottom: 12,
      backgroundColor: colors.card,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      fontFamily: colors.fonts.sora.bold,
      flex: 1,
      textAlign: 'center',
      color: colors.text,
      fontSize: 18,
    },
    headerSpacer: {
      width: 40,
    },
    scroll: {
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    ticketCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.isDark ? colors.navy.darkPanel : colors.orange.warningBg,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.isDark ? colors.alpha.orange30 : colors.amber[200],
      padding: 14,
      marginBottom: 16,
    },
    ticketIcon: {
      marginRight: 10,
    },
    ticketBody: {
      flex: 1,
    },
    ticketTitle: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.isDark ? colors.orange[450] : colors.amber[800],
      fontSize: 13.5,
      marginBottom: 2,
    },
    ticketSub: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.isDark ? colors.amber[300] : colors.amber[700],
      fontSize: 11.5,
    },
    ticketStatus: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    statusDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.isDark ? colors.orange[450] : colors.amber[800],
    },
    statusText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.isDark ? colors.orange[450] : colors.amber[800],
      fontSize: 12,
    },
    sectionLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.textMuted,
      fontSize: 11,
      letterSpacing: 0.8,
      marginBottom: 8,
    },
    sectionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    charCount: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.textMuted,
      fontSize: 11,
    },
    tripCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.card,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 12,
      paddingVertical: 12,
      marginBottom: 16,
    },
    tripIconWrap: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: colors.iconBg,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    tripBody: {
      flex: 1,
    },
    tripTitle: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 13.5,
      marginBottom: 2,
    },
    tripSub: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.textMuted,
      fontSize: 11.5,
    },
    categoryDropdown: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.card,
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: colors.primary,
      paddingHorizontal: 14,
      height: 48,
      marginBottom: 10,
    },
    categoryText: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.text,
      fontSize: 14,
    },
    subCategoriesWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 16,
    },
    subPill: {
      backgroundColor: colors.card,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 14,
      paddingVertical: 8,
    },
    subPillSelected: {
      backgroundColor: colors.isDark ? colors.alpha.orange22 : colors.orange.subtleBg,
      borderColor: colors.primary,
      borderWidth: 1.5,
    },
    subPillText: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.text,
      fontSize: 12,
    },
    subPillTextSelected: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.primary,
    },
    textCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
      marginBottom: 16,
      minHeight: 90,
    },
    textInput: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.text,
      fontSize: 12.5,
      lineHeight: 18,
      padding: 0,
      margin: 0,
      textAlignVertical: 'top',
    },
    attachmentsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginBottom: 16,
    },
    fileBox: {
      width: 56,
      height: 56,
      borderRadius: 14,
      backgroundColor: colors.iconBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    addBox: {
      width: 56,
      height: 56,
      borderRadius: 14,
      borderWidth: 1.5,
      borderStyle: 'dashed',
      borderColor: colors.border,
      backgroundColor: colors.card,
      alignItems: 'center',
      justifyContent: 'center',
    },
    addText: {
      fontFamily: colors.fonts.sora.semiBold,
      color: colors.textMuted,
      fontSize: 10.5,
      marginTop: 2,
    },
    footer: {
      paddingHorizontal: 16,
      paddingTop: 10,
      backgroundColor: colors.card,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    submitBtn: {
      backgroundColor: colors.primary,
      borderRadius: 16,
      height: 52,
      alignItems: 'center',
      justifyContent: 'center',
    },
    submitText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.white,
      fontSize: 16,
    },
    replyHint: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.textMuted,
      fontSize: 12,
      textAlign: 'center',
      marginTop: 10,
    },
  });
}
