import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: '#F3F6FA',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingBottom: 12,
      backgroundColor: '#FFFFFF',
    },
    headerBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      color: '#0F2840',
      fontSize: 18,
      fontWeight: '700',
    },
    headerSpacer: {
      width: 40,
    },
    scroll: {
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    ticketCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFF6E5',
      borderRadius: 16,
      padding: 14,
      marginBottom: 16,
    },
    ticketIcon: {
      marginRight: 10,
    },
    ticketBody: {
      flex: 1,
    },
    ticketTitle: {
      color: '#92400E',
      fontSize: 13.5,
      fontWeight: '700',
      marginBottom: 2,
    },
    ticketSub: {
      color: '#B45309',
      fontSize: 11.5,
      fontWeight: '500',
    },
    ticketStatus: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    statusDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: '#92400E',
    },
    statusText: {
      color: '#92400E',
      fontSize: 12,
      fontWeight: '700',
    },
    sectionLabel: {
      color: '#7E8B9E',
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.8,
      marginBottom: 8,
    },
    sectionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    charCount: {
      color: '#8A96A6',
      fontSize: 11,
      fontWeight: '500',
    },
    tripCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      borderRadius: 14,
      borderWidth: 1,
      borderColor: '#E8ECF2',
      paddingHorizontal: 12,
      paddingVertical: 12,
      marginBottom: 16,
    },
    tripIconWrap: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: '#F0F4F8',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    tripBody: {
      flex: 1,
    },
    tripTitle: {
      color: '#0F2840',
      fontSize: 13.5,
      fontWeight: '700',
      marginBottom: 2,
    },
    tripSub: {
      color: '#6E7C91',
      fontSize: 11.5,
      fontWeight: '400',
    },
    categoryDropdown: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: '#FFFFFF',
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: '#FF7006',
      paddingHorizontal: 14,
      height: 48,
      marginBottom: 10,
    },
    categoryText: {
      color: '#0F2840',
      fontSize: 14,
      fontWeight: '500',
    },
    subCategoriesWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 16,
    },
    subPill: {
      backgroundColor: '#FFFFFF',
      borderRadius: 20,
      borderWidth: 1,
      borderColor: '#E2E8F0',
      paddingHorizontal: 14,
      paddingVertical: 8,
    },
    subPillSelected: {
      backgroundColor: '#FFF5ED',
      borderColor: '#FF7006',
      borderWidth: 1.5,
    },
    subPillText: {
      color: '#0F2840',
      fontSize: 12,
      fontWeight: '500',
    },
    subPillTextSelected: {
      color: '#FF7006',
      fontWeight: '700',
    },
    textCard: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#E8ECF2',
      padding: 14,
      marginBottom: 16,
      minHeight: 90,
    },
    textInput: {
      color: '#0F2840',
      fontSize: 12.5,
      lineHeight: 18,
      padding: 0,
      margin: 0,
      textAlignVertical: 'top',
    },
    attachmentsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginBottom: 16,
    },
    fileBox: {
      width: 56,
      height: 56,
      borderRadius: 14,
      backgroundColor: '#E2E8F0',
      alignItems: 'center',
      justifyContent: 'center',
    },
    addBox: {
      width: 56,
      height: 56,
      borderRadius: 14,
      borderWidth: 1.5,
      borderStyle: 'dashed',
      borderColor: '#CBD5E1',
      backgroundColor: '#FFFFFF',
      alignItems: 'center',
      justifyContent: 'center',
    },
    addText: {
      color: '#64748B',
      fontSize: 10.5,
      fontWeight: '600',
      marginTop: 2,
    },
    footer: {
      paddingHorizontal: 16,
      paddingTop: 10,
      backgroundColor: '#FFFFFF',
      borderTopWidth: 1,
      borderTopColor: '#F0F3F7',
    },
    submitBtn: {
      backgroundColor: '#FF7006',
      borderRadius: 16,
      height: 52,
      alignItems: 'center',
      justifyContent: 'center',
    },
    submitText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '700',
    },
    replyHint: {
      color: '#6E7C91',
      fontSize: 12,
      textAlign: 'center',
      marginTop: 10,
    },
  });
}
