import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scroll: {
      paddingHorizontal: 20,
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      marginBottom: 16,
      gap: 12,
    },
    headerCopy: {


      flex: 1,
      paddingRight: 8,
    },
    title: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 28,
      letterSpacing: -0.4,
    },
    subtitle: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.textMuted,
      fontSize: 14,
      marginTop: 4,
      lineHeight: 20,
    },
    bellBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.isDark ? colors.surface : colors.navy[900],
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: colors.isDark ? 1 : 0,
      borderColor: colors.border,
      shadowColor: colors.black,
      shadowOpacity: 0.12,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 2},
      elevation: 3,
    },
    badge: {
      position: 'absolute',
      top: -2,
      right: -2,
      minWidth: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: colors.red[500],
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 4,
      borderWidth: 2,
      borderColor: colors.isDark ? colors.surface : colors.white,
    },
    badgeText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.white,
      fontSize: 10,
    },
    searchBox: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      backgroundColor: colors.isDark ? colors.surface : colors.gray[100],
      borderRadius: 18,
      borderWidth: colors.isDark ? 1 : 0,
      borderColor: colors.border,
      paddingHorizontal: 16,
      paddingVertical: 13,
      marginBottom: 22,
    },
    searchInput: {
      fontFamily: colors.fonts.sora.regular,
      flex: 1,
      color: colors.text,
      fontSize: 15,
      padding: 0,
      margin: 0,
    },
    section: {
      marginBottom: 22,
    },
    sectionLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.textSub,
      fontSize: 11,
      letterSpacing: 1.2,
      marginBottom: 10,
    },
    rideList: {
      gap: 10,
    },
    rideCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      backgroundColor: colors.card,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 8,
      paddingHorizontal: 10,
    },
    rideIcon: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: colors.isDark ? colors.alpha.orange20 : colors.orange[100],
      alignItems: 'center',
      justifyContent: 'center',
    },
    rideCopy: {
      flex: 1,
      minWidth: 0,
    },
    rideTitle: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 15,
    },
    rideMeta: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.textMuted,
      fontSize: 12,
      marginTop: 1,
    },
    rideBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: colors.isDark ? colors.alpha.orange20 : colors.orange[100],
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 999,
    },
    rideBadgeDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.orange[500],
    },
    rideBadgeText: {
      fontFamily: colors.fonts.sora.semiBold,
      color: colors.orange[600],
      fontSize: 11,
    },
    planGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    planCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 12,
    },
    planTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    planIcon: {
      width: 34,
      height: 34,
      borderRadius: 10,
      backgroundColor: colors.isDark ? colors.navy.cardBg2 : colors.navy[100],
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    planKicker: {
      fontFamily: colors.fonts.sora.regular,
      flex: 1,
      color: colors.textMuted,
      fontSize: 11,
      lineHeight: 14,
    },
    planTitle: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 14,
      marginTop: 10,
      lineHeight: 18,
    },
    portalCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
    },
    portalIcon: {
      width: 48,
      height: 48,
      borderRadius: 14,
      backgroundColor: colors.isDark ? colors.navy.cardBg3 : colors.blue[100],
      alignItems: 'center',
      justifyContent: 'center',
    },
    portalCopy: {
      flex: 1,
      minWidth: 0,
    },
    portalTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 4,
    },
    portalTitle: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 16,
    },
    newBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      backgroundColor: colors.isDark ? colors.alpha.blue20_59 : colors.blue[100],
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 999,
    },
    newBadgeDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.blue[500],
    },
    newBadgeText: {
      fontFamily: colors.fonts.sora.semiBold,
      color: colors.blue[500],
      fontSize: 11,
    },
    portalBody: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.textMuted,
      fontSize: 13,
      lineHeight: 18,
    },
    empty: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.textMuted,
      fontSize: 14,
      textAlign: 'center',
      marginTop: 24,
    },
  });
}
