import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    body: {
      flex: 1,
    },
    top: {
      flex: 1,
      paddingHorizontal: 20,
    },
    back: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.surface,
      borderWidth: colors.isDark ? 1 : 0,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 24,
    },
    avatar: {
      width: 56,
      height: 56,
      borderRadius: 28,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 18,
    },
    avatarChat: {
      backgroundColor: colors.isDark ? colors.alpha.orange18 : colors.orange[100],
    },
    avatarPaused: {
      backgroundColor: colors.isDark ? colors.alpha.red18 : colors.red[100],
    },
    avatarVerified: {
      backgroundColor: colors.isDark ? colors.alpha.green18 : colors.green[100],
    },
    title: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 28,
      fontWeight: '800',
      letterSpacing: -0.4,
    },
    meta: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      marginTop: 8,
      marginBottom: 28,
    },
    metaText: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.gray[500],
      fontSize: 14,
    },
    change: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.primary,
      fontSize: 14,
      fontWeight: '700',
    },
    boxes: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 14,
    },
    boxesHit: {
      position: 'relative',
    },
    box: {
      flex: 1,
      aspectRatio: 1,
      maxHeight: 56,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surface,
      borderWidth: 1.5,
      borderColor: colors.border,
    },
    boxFilled: {
      backgroundColor: colors.card,
      borderColor: colors.primary,
    },
    boxFocused: {
      backgroundColor: colors.card,
      borderColor: colors.primary,
    },
    boxError: {
      backgroundColor: colors.isDark ? colors.alpha.redAlpha15 : colors.red[75],
      borderColor: colors.danger,
    },
    boxSuccess: {
      backgroundColor: colors.isDark ? colors.alpha.greenDark15 : colors.green[100],
      borderColor: colors.green[600],
      borderWidth: 1.5,
    },
    boxDigit: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 22,
      fontWeight: '700',
      color: colors.text,
    },
    boxDigitError: {
      color: colors.danger,
    },
    boxDigitSuccess: {
      color: colors.green[600],
    },
    caret: {
      width: 2,
      height: 22,
      borderRadius: 1,
      backgroundColor: colors.primary,
    },
    hiddenInput: {
      position: 'absolute',
      opacity: 0,
      height: 56,
      width: '100%',
      top: 0,
    },
    hintRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 6,
      marginBottom: 14,
    },
    hint: {
      fontFamily: colors.fonts.sora.regular,
      flex: 1,
      fontSize: 13,
      lineHeight: 18,
      color: colors.muted,
    },
    hintError: {
      color: colors.danger,
    },
    hintSuccess: {
      color: colors.green[600],
    },
    banner: {
      borderRadius: 16,
      padding: 14,
      backgroundColor: colors.isDark ? colors.alpha.red18 : colors.red[100],
      marginBottom: 14,
    },
    bannerTitle: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.red[600],
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 4,
    },
    bannerBody: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.red[600],
      fontSize: 13,
      lineHeight: 19,
    },
    support: {
      fontFamily: colors.fonts.sora.bold,
      marginTop: 8,
      color: colors.text,
      fontSize: 13,
      fontWeight: '700',
    },
    chip: {
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 999,
      backgroundColor: colors.surface,
      borderWidth: colors.isDark ? 1 : 0,
      borderColor: colors.border,
    },
    chipResend: {
      backgroundColor: colors.isDark ? colors.alpha.orange18 : colors.orange[100],
    },
    chipLabel: {
      fontFamily: colors.fonts.sora.semiBold,
      fontSize: 13,
      fontWeight: '600',
      color: colors.muted,
    },
    chipLabelResend: {
      color: colors.primary,
    },
    footer: {
      paddingHorizontal: 20,
      paddingTop: 16,
    },
    help: {
      fontFamily: colors.fonts.sora.regular,
      marginTop: 14,
      textAlign: 'center',
      color: colors.muted,
      fontSize: 13,
    },
    helpLink: {
      fontFamily: colors.fonts.sora.semiBold,
      color: colors.gray[600],
      fontWeight: '600',
    },
    verifyButton: {
      minHeight: 56,
      borderRadius: 18,
    },
    // OTP Modal Styles
    otpModalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 24,
    },
    otpModalContent: {
      width: '100%',
      backgroundColor: colors.card,
      borderRadius: 24,
      padding: 24,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 10},
      shadowOpacity: 0.25,
      shadowRadius: 20,
      elevation: 10,
    },
    otpIconContainer: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: colors.isDark ? colors.alpha.orange18 : colors.orange[100],
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
    },
    otpModalTitle: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 20,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 8,
      textAlign: 'center',
    },
    otpModalSub: {
      fontFamily: colors.fonts.sora.regular,
      fontSize: 14,
      color: colors.muted,
      textAlign: 'center',
      marginBottom: 20,
    },
    otpBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.isDark ? colors.alpha.orange18 : '#FFF7ED',
      borderColor: colors.orange[400],
      borderWidth: 1.5,
      borderStyle: 'dashed',
      borderRadius: 16,
      paddingVertical: 14,
      paddingHorizontal: 24,
      marginBottom: 24,
      width: '100%',
    },
    otpBadgeText: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 28,
      fontWeight: '800',
      color: colors.orange[500],
      letterSpacing: 6,
    },
    otpModalActions: {
      width: '100%',
      gap: 12,
    },
    autoFillBtn: {
      backgroundColor: colors.orange[500],
      borderRadius: 16,
      paddingVertical: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    autoFillBtnText: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 16,
      fontWeight: '700',
      color: '#FFFFFF',
    },
    dismissBtn: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      paddingVertical: 12,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    dismissBtnText: {
      fontFamily: colors.fonts.sora.semiBold,
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
    },
  });
}
