import {StyleSheet} from 'react-native';

const c = {
  bg: '#08070C',
  card: 'rgba(255,255,255,0.04)',
  border: 'rgba(255,255,255,0.1)',
  text: '#FFFFFF',
  muted: 'rgba(255,255,255,0.4)',
  faint: 'rgba(255,255,255,0.32)',
  pink: '#F472B6',
  purple: '#C084FC',
  live: '#86EFAC',
};

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: c.bg,
  },
  header: {
    paddingHorizontal: 18,
    paddingBottom: 8,
  },
  navRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 8,
  },
  menu: {
    width: 28,
    height: 28,
    tintColor: '#FFFFFF',
    borderRadius: 8,
  },
  resultsEy: {
    fontSize: 9.5,
    fontWeight: '500',
    letterSpacing: 1.6,
    color: c.faint,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 8,
    marginTop: 2,
  },
  keyword: {
    flex: 1,
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: -0.8,
    color: c.text,
  },
  count: {
    fontSize: 11.5,
    fontWeight: '500',
    color: c.muted,
  },
  searchBox: {
    marginTop: 12,
    height: 44,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.09)',
    paddingHorizontal: 14,
    color: c.text,
    fontSize: 15,
  },
  tabs: {
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 18,
    paddingBottom: 12,
  },
  tab: {
    flex: 1,
    height: 52,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    borderWidth: 1,
  },
  tabIdle: {
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderColor: 'rgba(255,255,255,0.07)',
  },
  tabOn: {
    backgroundColor: 'rgba(236,72,153,0.14)',
    borderColor: 'rgba(236,72,153,0.4)',
  },
  tabName: {
    fontSize: 10.5,
    fontWeight: '700',
  },
  list: {
    paddingHorizontal: 18,
    paddingBottom: 40,
  },
  hero: {
    borderRadius: 24,
    backgroundColor: 'rgba(168,85,247,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.09)',
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 16,
    marginBottom: 16,
  },
  heroTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  heroKicker: {
    fontSize: 9.5,
    fontWeight: '500',
    letterSpacing: 1.6,
    color: 'rgba(255,255,255,0.38)',
  },
  heroValueRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 4,
    paddingTop: 4,
  },
  heroValue: {
    fontSize: 40,
    fontWeight: '800',
    letterSpacing: -1.6,
    color: '#F9A8D4',
    lineHeight: 42,
  },
  heroUnit: {
    fontSize: 18,
    fontWeight: '800',
    color: 'rgba(255,255,255,0.55)',
  },
  heroUnitLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: c.muted,
    paddingLeft: 4,
  },
  livePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    height: 28,
    paddingHorizontal: 11,
    borderRadius: 999,
    backgroundColor: 'rgba(74,222,128,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(74,222,128,0.28)',
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#4ADE80',
  },
  liveText: {
    fontSize: 10.5,
    fontWeight: '700',
    color: c.live,
  },
  hint: {
    fontSize: 11,
    fontWeight: '600',
    color: c.muted,
    paddingTop: 4,
  },
  mixBar: {
    flexDirection: 'row',
    height: 8,
    marginTop: 16,
    borderRadius: 999,
    overflow: 'hidden',
    gap: 2,
  },
  mixSegIg: {backgroundColor: '#F472B6'},
  mixSegTt: {backgroundColor: '#22D3EE'},
  mixSegYt: {backgroundColor: '#FB7185'},
  mixRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minHeight: 44,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
  },
  mixSwatch: {
    width: 24,
    height: 24,
    borderRadius: 8,
  },
  mixName: {
    flex: 1,
    color: c.text,
    fontSize: 13,
    fontWeight: '700',
  },
  mixCount: {
    color: c.muted,
    fontSize: 12,
    fontWeight: '600',
  },
  metrics: {
    flexDirection: 'row',
    paddingTop: 12,
  },
  metric: {flex: 1},
  metricValue: {
    fontSize: 15,
    fontWeight: '600',
    color: c.pink,
  },
  metricLabel: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: 'rgba(255,255,255,0.34)',
    paddingTop: 2,
  },
  split: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 14,
  },
  splitCol: {flex: 1},
  section: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: c.text,
  },
  sectionLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  card: {
    borderRadius: 22,
    backgroundColor: c.card,
    borderWidth: 1,
    borderColor: c.border,
    marginBottom: 14,
    overflow: 'hidden',
  },
  thumb: {
    height: 210,
    justifyContent: 'center',
    alignItems: 'center',
  },
  overlayRow: {
    position: 'absolute',
    top: 12,
    left: 12,
    right: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  topPick: {
    height: 26,
    paddingHorizontal: 11,
    borderRadius: 999,
    backgroundColor: '#EC4899',
    justifyContent: 'center',
  },
  topPickText: {
    color: '#fff',
    fontSize: 10.5,
    fontWeight: '800',
  },
  platBadge: {
    marginLeft: 'auto',
    height: 26,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(0,0,0,0.62)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    justifyContent: 'center',
  },
  platBadgeText: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 10.5,
    fontWeight: '700',
  },
  play: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: 'rgba(8,7,12,0.5)',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  playTri: {
    marginLeft: 3,
    width: 0,
    height: 0,
    borderTopWidth: 8,
    borderBottomWidth: 8,
    borderLeftWidth: 12,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: '#fff',
  },
  duration: {
    position: 'absolute',
    right: 12,
    bottom: 12,
    height: 22,
    paddingHorizontal: 8,
    borderRadius: 6,
    backgroundColor: 'rgba(0,0,0,0.82)',
    color: '#fff',
    fontSize: 11,
    fontWeight: '500',
    overflow: 'hidden',
    textAlignVertical: 'center',
    lineHeight: 22,
  },
  cardBody: {
    padding: 14,
  },
  author: {
    color: c.muted,
    fontSize: 12,
    fontWeight: '600',
  },
  cardTitle: {
    color: c.text,
    fontSize: 16,
    fontWeight: '800',
    marginTop: 4,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 10,
  },
  meta: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 12,
    fontWeight: '600',
  },
  score: {
    marginLeft: 'auto',
    color: c.text,
    fontSize: 15,
    fontWeight: '600',
  },
  tier: {
    height: 26,
    paddingHorizontal: 11,
    borderRadius: 999,
    justifyContent: 'center',
  },
  tierText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '800',
  },
  actions: {
    flexDirection: 'row',
    gap: 9,
    paddingTop: 13,
  },
  saveBtn: {
    flex: 1,
    height: 44,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveText: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 13,
    fontWeight: '700',
  },
  analyzeBtn: {
    flex: 1.35,
    height: 44,
    borderRadius: 14,
    backgroundColor: '#EC4899',
    alignItems: 'center',
    justifyContent: 'center',
  },
  analyzeText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
  },
  loadMore: {
    alignSelf: 'center',
    height: 42,
    paddingHorizontal: 20,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  loadMoreText: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 13,
    fontWeight: '700',
  },
  empty: {
    color: c.muted,
    textAlign: 'center',
    paddingVertical: 40,
  },
});
