import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.white,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 12,
      paddingBottom: 4,
    },
    headerBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      color: colors.navy[900],
      fontSize: 17,
      fontWeight: '700',
    },
    progressWrap: {
      paddingHorizontal: 20,
      marginTop: 12,
      marginBottom: 16,
    },
    progressTrack: {
      flexDirection: 'row',
      gap: 6,
      marginBottom: 8,
    },
    progressSeg: {
      flex: 1,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.gray[200],
    },
    progressSegActive: {
      backgroundColor: colors.orange[500],
    },
    stepText: {
      color: colors.gray[500],
      fontSize: 12,
      fontWeight: '500',
    },
    scroll: {
      paddingHorizontal: 20,
      paddingTop: 2,
    },
    routeCard: {
      flexDirection: 'row',
      alignItems: 'stretch',
      backgroundColor: colors.white,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.gray[200],
      paddingVertical: 14,
      paddingHorizontal: 14,
      marginBottom: 18,
      gap: 10,
    },
    routeTimeline: {
      width: 12,
      alignItems: 'center',
    },
    routeDotStart: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.orange[500],
    },
    routeLine: {
      width: 2,
      flex: 1,
      minHeight: 22,
      backgroundColor: colors.gray[300],
      marginVertical: 4,
    },
    routeDotEnd: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.navy[800],
    },
    routeCopy: {
      flex: 1,
      minWidth: 0,
      justifyContent: 'space-between',
      gap: 16,
    },
    routeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    routeTitle: {
      flex: 1,
      color: colors.navy[900],
      fontSize: 14,
      fontWeight: '700',
    },
    routeMeta: {
      color: colors.gray[500],
      fontSize: 13,
      fontWeight: '500',
    },
    section: {
      marginBottom: 18,
    },
    sectionLabel: {
      color: colors.gray[500],
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1.1,
      marginBottom: 10,
    },
    riderList: {
      gap: 10,
    },
    riderCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: colors.white,
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: colors.gray[200],
      paddingVertical: 12,
      paddingHorizontal: 12,
    },
    riderCardActive: {
      borderColor: colors.orange[500],
      backgroundColor: colors.orange[50],
    },
    riderIcon: {
      width: 42,
      height: 42,
      borderRadius: 12,
      backgroundColor: colors.white,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.gray[200],
    },
    riderCopy: {
      flex: 1,
      minWidth: 0,
    },
    riderTitle: {
      color: colors.navy[900],
      fontSize: 15,
      fontWeight: '700',
    },
    riderMeta: {
      color: colors.gray[500],
      fontSize: 12,
      fontWeight: '400',
      marginTop: 2,
    },
    riderBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      gap: 5,
      marginTop: 6,
      backgroundColor: colors.orange[100],
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 999,
    },
    riderBadgeAlt: {
      backgroundColor: colors.blue[100],
    },
    riderBadgeDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.orange[500],
    },
    riderBadgeDotAlt: {
      backgroundColor: colors.blue[500],
    },
    riderBadgeText: {
      color: colors.orange[700],
      fontSize: 11,
      fontWeight: '600',
    },
    riderBadgeTextAlt: {
      color: colors.blue[600],
    },
    riderPrice: {
      color: colors.navy[900],
      fontSize: 16,
      fontWeight: '800',
    },
    riderPriceActive: {
      color: colors.orange[600],
    },
    fareCard: {
      backgroundColor: colors.white,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.gray[200],
      padding: 14,
      marginBottom: 12,
    },
    fareRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      marginBottom: 10,
    },
    fareRowLast: {
      marginBottom: 0,
    },
    fareLabel: {
      flex: 1,
      color: colors.gray[500],
      fontSize: 13,
      fontWeight: '400',
    },
    fareAmount: {
      color: colors.navy[900],
      fontSize: 13,
      fontWeight: '700',
    },
    payCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: colors.white,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.gray[200],
      padding: 14,
      marginBottom: 8,
    },
    payIcon: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: colors.gray[100],
      alignItems: 'center',
      justifyContent: 'center',
    },
    payCopy: {
      flex: 1,
      minWidth: 0,
    },
    payTitle: {
      color: colors.navy[900],
      fontSize: 15,
      fontWeight: '700',
    },
    payMeta: {
      color: colors.gray[500],
      fontSize: 12,
      fontWeight: '400',
      marginTop: 2,
    },
    changeText: {
      color: colors.orange[600],
      fontSize: 14,
      fontWeight: '700',
    },
    footer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      paddingHorizontal: 20,
      paddingTop: 10,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.gray[200],
      backgroundColor: colors.white,
    },
    footerCopy: {
      flex: 1,
      minWidth: 0,
    },
    footerLabel: {
      color: colors.gray[500],
      fontSize: 12,
      fontWeight: '500',
    },
    footerPrice: {
      color: colors.navy[900],
      fontSize: 26,
      fontWeight: '800',
      marginTop: 2,
      letterSpacing: -0.4,
    },
    footerNote: {
      color: colors.green[600],
      fontSize: 11,
      fontWeight: '600',
      marginTop: 2,
    },
    confirmBtn: {
      backgroundColor: colors.orange[500],
      paddingVertical: 14,
      paddingHorizontal: 28,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    confirmText: {
      color: colors.white,
      fontSize: 16,
      fontWeight: '700',
    },
  });
}
