import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      marginBottom: 20,
    },
    headerBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      fontFamily: colors.fonts.sora.bold,
      flex: 1,
      textAlign: 'center',
      color: colors.text,
      fontSize: 17,
      fontWeight: '700',
    },
    scroll: {
      paddingHorizontal: 20,
      paddingBottom: 12,
    },
    title: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 28,
      fontWeight: '800',
      letterSpacing: -0.4,
      marginBottom: 8,
    },
    subtitle: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.gray[500],
      fontSize: 14,
      lineHeight: 20,
      marginBottom: 20,
    },
    card: {
      borderWidth: 1.5,
      borderColor: colors.border,
      borderRadius: 20,
      padding: 16,
      marginBottom: 12,
      backgroundColor: colors.card,
    },
    cardSelected: {
      borderColor: colors.primary,
      backgroundColor: colors.isDark ? colors.alpha.orange15 : colors.orange[50],
    },
    cardTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
    },
    iconWrap: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    iconSelected: {
      backgroundColor: colors.surface,
    },
    copy: {
      flex: 1,
    },
    cardTitle: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 4,
    },
    cardBody: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.gray[500],
      fontSize: 13,
      lineHeight: 18,
    },
    radio: {
      width: 22,
      height: 22,
      borderRadius: 11,
      borderWidth: 1.5,
      borderColor: colors.border,
      backgroundColor: colors.card,
      marginTop: 2,
    },
    radioOn: {
      borderWidth: 6,
      borderColor: colors.primary,
      backgroundColor: colors.card,
    },
    divider: {
      height: 1,
      backgroundColor: colors.border,
      marginTop: 14,
      marginBottom: 12,
    },
    dividerSelected: {
      backgroundColor: colors.isDark ? colors.alpha.orange30 : colors.orange[200],
    },
    hint: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    hintText: {
      fontFamily: colors.fonts.sora.medium,
      flex: 1,
      fontSize: 13,
      fontWeight: '500',
      color: colors.muted,
    },
    hintSuccess: {
      fontFamily: colors.fonts.sora.semiBold,
      color: colors.green[600],
      fontWeight: '600',
    },
    note: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      borderWidth: 1.5,
      borderColor: colors.border,
      borderRadius: 20,
      padding: 14,
      marginTop: 4,
      backgroundColor: colors.card,
    },
    noteText: {
      fontFamily: colors.fonts.sora.regular,
      flex: 1,
      color: colors.text,
      fontSize: 13,
      lineHeight: 19,
    },
    footer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 16,
      paddingHorizontal: 20,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      backgroundColor: colors.background,
    },
    pickedLabel: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.gray[500],
      fontSize: 13,
    },
    pickedValue: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 20,
      fontWeight: '800',
      marginTop: 2,
    },
    continue: {
      minWidth: 148,
      borderRadius: 999,
    },
  });
}
