import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.map.land,
    },
    mapArea: {
      height: '32%',
      backgroundColor: colors.map.land,
      overflow: 'hidden',
    },
    roadH: {
      position: 'absolute',
      top: '42%',
      left: 0,
      right: 0,
      height: 10,
      backgroundColor: colors.map.road,
    },
    roadH2: {
      position: 'absolute',
      top: '68%',
      left: 0,
      right: 0,
      height: 7,
      backgroundColor: colors.map.roadAlt,
    },
    roadV: {
      position: 'absolute',
      top: 0,
      bottom: 0,
      left: '48%',
      width: 10,
      backgroundColor: colors.map.road,
    },
    blockA: {
      position: 'absolute',
      top: 24,
      left: 24,
      width: 70,
      height: 50,
      borderRadius: 8,
      backgroundColor: colors.map.building,
    },
    blockB: {
      position: 'absolute',
      top: 30,
      right: 36,
      width: 90,
      height: 60,
      borderRadius: 8,
      backgroundColor: colors.map.park,
    },
    pinWrap: {
      ...StyleSheet.absoluteFillObject,
      alignItems: 'center',
      justifyContent: 'center',
      paddingBottom: 28,
    },
    pinShadow: {
      position: 'absolute',
      bottom: '42%',
      width: 18,
      height: 6,
      borderRadius: 3,
      backgroundColor: 'rgba(13,43,71,0.2)',
    },
    dragHint: {
      position: 'absolute',
      alignSelf: 'center',
      bottom: 18,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.navy[900],
      borderRadius: 999,
      paddingVertical: 8,
      paddingHorizontal: 14,
    },
    dragDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.orange[500],
    },
    dragText: {
      color: colors.white,
      fontSize: 12,
      fontWeight: '600',
    },
    backBtn: {
      position: 'absolute',
      left: 16,
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: colors.white,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.navy[900],
      shadowOpacity: 0.12,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 2},
      elevation: 4,
      zIndex: 5,
    },
    sheet: {
      flex: 1,
      marginTop: -18,
    },
    sheetInner: {
      flex: 1,
      backgroundColor: colors.white,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingHorizontal: 18,
      paddingTop: 10,
    },
    grabber: {
      alignSelf: 'center',
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.gray[300],
      marginBottom: 14,
    },
    title: {
      color: colors.navy[900],
      fontSize: 24,
      fontWeight: '800',
      letterSpacing: -0.3,
      marginBottom: 14,
    },
    addressBox: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      backgroundColor: colors.navy[50],
      borderRadius: 14,
      paddingVertical: 12,
      paddingHorizontal: 12,
      marginBottom: 16,
    },
    addressText: {
      flex: 1,
      color: colors.navy[900],
      fontSize: 14,
      fontWeight: '600',
      lineHeight: 20,
    },
    form: {
      paddingBottom: 12,
    },
    sectionLabel: {
      color: colors.gray[400],
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1.1,
      marginBottom: 10,
    },
    labelRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 16,
    },
    labelChip: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      borderWidth: 1.5,
      borderColor: colors.gray[200],
      borderRadius: 14,
      paddingVertical: 12,
      backgroundColor: colors.white,
    },
    labelChipActive: {
      borderColor: colors.orange[500],
      backgroundColor: colors.orange[50],
    },
    labelChipText: {
      color: colors.navy[800],
      fontSize: 13,
      fontWeight: '700',
    },
    labelChipTextActive: {
      color: colors.orange[600],
    },
    fieldGroup: {
      marginBottom: 14,
    },
    fieldLabel: {
      color: colors.gray[500],
      fontSize: 13,
      fontWeight: '500',
      marginBottom: 8,
    },
    fieldBox: {
      borderWidth: 1.5,
      borderColor: colors.gray[200],
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 14,
      backgroundColor: colors.white,
    },
    fieldInput: {
      color: colors.navy[900],
      fontSize: 15,
      fontWeight: '600',
      padding: 0,
      margin: 0,
    },
    saveBtn: {
      backgroundColor: colors.orange[500],
      borderRadius: 16,
      paddingVertical: 16,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 4,
    },
    saveBtnDisabled: {
      opacity: 0.45,
    },
    saveText: {
      color: colors.white,
      fontSize: 16,
      fontWeight: '700',
    },
  });
}
