import { StyleSheet } from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },

    scrollContent: {
      paddingBottom: 110,
    },

    // Navy Hero Section
    navyHero: {
      backgroundColor: colors.navy[850],
      borderBottomLeftRadius: 32,
      borderBottomRightRadius: 32,
      paddingHorizontal: 20,
      paddingBottom: 36,
      position: 'relative',
      overflow: 'hidden',
    },
    glow: {
      position: 'absolute',
      top: -30,
      right: -30,
      width: 300,
      height: 300,
    },
    menuBtn: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: colors.alpha.white10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    giftBadge: {
      width: 48,
      height: 48,
      borderRadius: 16,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 14,
      marginBottom: 16,
      shadowColor: colors.primary,
      shadowOpacity: 0.3,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 4,
    },
    heroTitle: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 32,
      fontWeight: '900',
      color: colors.white,
      lineHeight: 38,
      letterSpacing: -0.5,
    },
    heroSub: {
      fontFamily: colors.fonts.sora.medium,
      fontSize: 13.5,
      fontWeight: '500',
      color: colors.navy[350],
      lineHeight: 19,
      marginTop: 8,
    },

    // Dashed Code Card
    codeCard: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      borderWidth: 2,
      borderColor: colors.primary,
      borderStyle: 'dashed',
      padding: 16,
      marginHorizontal: 16,
      marginTop: 14,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      shadowColor: colors.black,
      shadowOpacity: 0.04,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    codeLeft: {
      flex: 1,
    },
    codeLabel: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 11,
      fontWeight: '700',
      color: colors.navy[350],
      letterSpacing: 0.8,
      textTransform: 'uppercase',
      marginBottom: 3,
    },
    codeValue: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 20,
      fontWeight: '900',
      color: colors.text,
      letterSpacing: 0.5,
    },
    copyBtn: {
      backgroundColor: colors.orange[175],
      paddingHorizontal: 14,
      paddingVertical: 9,
      borderRadius: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    copyText: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 13.5,
      fontWeight: '800',
      color: colors.primary,
    },

    // Milestone Card
    milestoneCard: {
      backgroundColor: colors.surface,
      borderRadius: 22,
      padding: 18,
      marginHorizontal: 16,
      marginTop: 14,
      shadowColor: colors.black,
      shadowOpacity: 0.04,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    milestoneHead: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    milestoneTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    milestoneTitle: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 14.5,
      fontWeight: '800',
      color: colors.text,
    },
    inProgressBadge: {
      backgroundColor: colors.orange[175],
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    inProgressDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.primary,
    },
    inProgressText: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 11.5,
      fontWeight: '800',
      color: colors.orange[700],
    },
    milestoneStats: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    milestoneDrivers: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 17,
      fontWeight: '900',
      color: colors.text,
    },
    milestoneReward: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 20,
      fontWeight: '900',
      color: colors.primary,
    },
    trackRow: {
      flexDirection: 'row',
      gap: 5,
      marginVertical: 12,
    },
    segment: {
      flex: 1,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.background,
    },
    segmentFilled: {
      backgroundColor: colors.primary,
    },
    milestoneSub: {
      fontFamily: colors.fonts.sora.medium,
      fontSize: 12.5,
      fontWeight: '500',
      color: colors.textMuted,
    },

    // Referrals Section
    sectionTitle: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 11.5,
      fontWeight: '700',
      color: colors.textMuted,
      letterSpacing: 0.6,
      textTransform: 'uppercase',
      marginHorizontal: 16,
      marginTop: 22,
      marginBottom: 10,
    },
    referralsCard: {
      backgroundColor: colors.surface,
      borderRadius: 22,
      marginHorizontal: 16,
      paddingHorizontal: 16,
      shadowColor: colors.black,
      shadowOpacity: 0.04,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    referralItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 14,
    },
    referralBorder: {
      borderBottomWidth: 1,
      borderBottomColor: colors.slate[100],
    },
    referralLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      flex: 1,
    },
    avatarCircle: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarText: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 13,
      fontWeight: '800',
    },
    referralInfo: {
      flex: 1,
    },
    referralName: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 14.5,
      fontWeight: '800',
      color: colors.text,
    },
    referralSub: {
      fontFamily: colors.fonts.sora.medium,
      fontSize: 12.5,
      fontWeight: '500',
      color: colors.textMuted,
      marginTop: 2,
    },
    referralRight: {
      alignItems: 'flex-end',
      gap: 4,
    },
    referralAmount: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 14.5,
      fontWeight: '800',
      color: colors.green[700],
    },
    statusBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 12,
    },
    statusBadgePaid: {
      backgroundColor: colors.green[200],
    },
    statusBadgeProgress: {
      backgroundColor: colors.blue[50],
    },
    statusDotPaid: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.green[600],
    },
    statusDotProgress: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.blue[550],
    },
    statusTextPaid: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 11.5,
      fontWeight: '800',
      color: colors.green[700],
    },
    statusTextProgress: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 11.5,
      fontWeight: '800',
      color: colors.blue[550],
    },

    // Sticky Share Button Container
    shareBtnWrap: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: colors.background,
      paddingHorizontal: 16,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: colors.borderLight,
      zIndex: 50,
    },
    shareBtn: {
      backgroundColor: colors.primary,
      height: 52,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.primary,
      shadowOpacity: 0.25,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 4,
    },
    shareBtnText: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.white,
      fontSize: 16,
      fontWeight: '800',
    },
  });
}
