import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.navy[25],
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 12,
      paddingBottom: 12,
      backgroundColor: colors.white,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.gray[200],
    },
    headerBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      fontFamily: colors.fonts.sora.bold,
      flex: 1,
      textAlign: 'center',
      color: colors.text,
      fontSize: 17,
    },
    scroll: {
      paddingHorizontal: 16,
      paddingTop: 16,
      gap: 12,
    },
    card: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 16,
    },
    cardRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
    },
    cardCopy: {
      flex: 1,
      minWidth: 0,
    },
    cardTitle: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 16,
    },
    cardSub: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.textSecondary,
      fontSize: 13,
      lineHeight: 18,
      marginTop: 4,
    },
    onBadge: {
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginTop: 12,
      backgroundColor: colors.isDark ? colors.alpha.green18 : colors.green[100],
      borderRadius: 999,
      paddingVertical: 5,
      paddingHorizontal: 10,
    },
    onDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: colors.green[500],
    },
    onBadgeText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.isDark ? colors.green[400] : colors.green[600],
      fontSize: 12,
    },
    mapPreview: {
      height: 140,
      borderRadius: 16,
      overflow: 'hidden',
      backgroundColor: colors.map.land,
      marginBottom: 14,
    },
    mapImage: {
      ...StyleSheet.absoluteFillObject,
      width: '100%',
      height: '100%',
    },
    destRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    destCopy: {
      flex: 1,
      minWidth: 0,
    },
    destTitle: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 15,
    },
    destMeta: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.textSecondary,
      fontSize: 12,
      marginTop: 2,
    },
    changeLink: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.orange[600],
      fontSize: 14,
    },
    usesTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    usesCount: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 16,
    },
    usesTrack: {
      height: 8,
      borderRadius: 999,
      backgroundColor: colors.isDark ? colors.navy[800] : colors.gray[200],
      overflow: 'hidden',
      marginBottom: 10,
    },
    usesFill: {
      height: '100%',
      borderRadius: 999,
      backgroundColor: colors.orange[600],
    },
    usesHint: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 17,
      marginBottom: 8,
    },
    infoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    infoText: {
      fontFamily: colors.fonts.sora.regular,
      flex: 1,
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 17,
    },
    rulesTitle: {
      marginBottom: 12,
    },
    ruleRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      marginBottom: 12,
    },
    ruleText: {
      fontFamily: colors.fonts.sora.medium,
      flex: 1,
      color: colors.textSecondary,
      fontSize: 13,
      lineHeight: 18,
    },
    footer: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      paddingHorizontal: 16,
      paddingTop: 12,
      backgroundColor: colors.surface,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    footerHint: {
      fontFamily: colors.fonts.sora.regular,
      textAlign: 'center',
      color: colors.textMuted,
      fontSize: 12,
      marginBottom: 10,
    },
    ctaBtn: {
      backgroundColor: colors.orange[600],
    },
  });
}
