import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    scroll: {
      paddingBottom: 4,
    },
    matchBadge: {
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.isDark ? colors.alpha.green15 : colors.green[100],
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 14,
      marginBottom: 10,
    },
    matchDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: colors.green[500],
    },
    matchBadgeText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.green[600],
      fontSize: 12,
    },
    liveBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      backgroundColor: colors.isDark ? colors.alpha.green15 : colors.green[100],
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 14,
    },
    headline: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 22,
      marginBottom: 4,
    },
    headlineOnWay: {
      fontFamily: colors.fonts.sora.extraBold,
      flex: 1,
      color: colors.text,
      fontSize: 22,
      marginRight: 8,
    },
    headlineRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 14,
    },
    subline: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.muted,
      fontSize: 14,
      marginBottom: 14,
    },
    driverCard: {
      borderWidth: 1.5,
      borderColor: colors.border,
      borderRadius: 16,
      padding: 14,
      marginBottom: 16,
      backgroundColor: colors.card,
    },
    driverRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 16,
    },
    driverTop: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    avatar: {
      width: 48,
      height: 48,
      borderRadius: 24,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    avatarOrange: {
      backgroundColor: colors.isDark ? colors.alpha.orange20 : colors.orange[100],
    },
    avatarNavy: {
      backgroundColor: colors.isDark ? colors.navy.cardBg : colors.navy[800],
    },
    avatarBlue: {
      backgroundColor: colors.isDark ? colors.alpha.blue20_59 : colors.blue[100],
    },
    avatarText: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 15,
    },
    avatarTextOrange: {
      color: colors.orange[500],
    },
    avatarTextNavy: {
      color: colors.white,
    },
    avatarTextBlue: {
      color: colors.blue[500],
    },
    driverCopy: {
      flex: 1,
      minWidth: 0,
    },
    nameRatingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      marginBottom: 3,
      flexWrap: 'wrap',
    },
    driverName: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 16,
    },
    ratingText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 13,
    },
    driverMeta: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.muted,
      fontSize: 12,
    },
    ratingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginTop: 2,
    },
    plate: {
      backgroundColor: colors.surface,
      paddingHorizontal: 10,
      paddingVertical: 8,
      borderRadius: 10,
    },
    plateDark: {
      backgroundColor: colors.isDark ? colors.navy.cardBg : colors.navy[800],
      borderRadius: 12,
      paddingHorizontal: 10,
      paddingVertical: 9,
    },
    plateText: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 11,
    },
    plateTextLight: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.white,
      fontSize: 11,
    },
    otpInline: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 12,
      paddingTop: 12,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    otpInlineText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 13,
    },
    sectionLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.muted,
      fontSize: 11,
      letterSpacing: 0.8,
      marginBottom: 10,
    },
    poolCard: {
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: 14,
      paddingVertical: 12,
      paddingHorizontal: 12,
      marginBottom: 8,
      borderWidth: 1.5,
      borderColor: colors.border,
      backgroundColor: colors.card,
    },
    poolCardYou: {
      backgroundColor: colors.isDark ? colors.navy.cardBg : colors.orange[50],
      borderColor: colors.orange[500],
    },
    poolCopy: {
      flex: 1,
      minWidth: 0,
      marginLeft: 10,
    },
    poolName: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 14,
    },
    poolRoute: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.muted,
      fontSize: 12,
      marginTop: 2,
    },
    poolStatus: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 11,
      marginLeft: 8,
      maxWidth: 88,
      textAlign: 'right',
    },
    poolStatusYou: {
      color: colors.orange[500],
    },
    poolStatusOther: {
      color: colors.muted,
    },
    infoBanner: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      backgroundColor: colors.isDark ? colors.alpha.blue18 : colors.blue[100],
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginTop: 8,
    },
    infoBannerText: {
      fontFamily: colors.fonts.sora.medium,
      flex: 1,
      color: colors.isDark ? colors.text : colors.navy[700],
      fontSize: 13,
      lineHeight: 19,
    },
    otpBox: {
      borderWidth: 1.5,
      borderColor: colors.orange[400],
      backgroundColor: colors.isDark ? colors.navy[950] : colors.orange[50],
      borderRadius: 18,
      padding: 14,
      marginBottom: 18,
    },
    otpHead: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 12,
    },
    otpHeadText: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.orange[500],
      fontSize: 12,
      letterSpacing: 0.7,
    },
    otpDigits: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 10,
      marginBottom: 12,
    },
    otpDigit: {
      flex: 1,
      height: 56,
      borderRadius: 14,
      backgroundColor: colors.card,
      borderWidth: 1.5,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    otpDigitText: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 26,
    },
    otpHint: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.orange[500],
      fontSize: 12,
      lineHeight: 17,
    },
    actionsRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 14,
    },
    actionBtn: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingVertical: 13,
      borderRadius: 14,
      backgroundColor: colors.surface,
    },
    actionBtnSos: {
      backgroundColor: colors.isDark ? colors.alpha.red18 : colors.red[100],
    },
    actionLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 11,
    },
    actionLabelSos: {
      color: colors.red[500],
    },
    safetyBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      backgroundColor: colors.isDark ? colors.navy.cardBg : colors.blue[100],
      borderRadius: 16,
      paddingHorizontal: 12,
      paddingVertical: 13,
      marginBottom: 14,
    },
    safetyIcon: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.card,
    },
    safetyCopy: {
      flex: 1,
      minWidth: 0,
    },
    safetyTitle: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 13,
      marginBottom: 2,
    },
    safetyBody: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.muted,
      fontSize: 12,
      lineHeight: 17,
    },
    cancelLink: {
      alignItems: 'center',
      paddingVertical: 8,
    },
    cancelLinkSpaced: {
      alignItems: 'center',
      paddingVertical: 8,
      marginTop: 14,
    },
    cancelLinkText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.muted,
      fontSize: 15,
    },
    onTripHead: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 10,
    },
    onTripBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.isDark ? colors.alpha.orange18 : colors.orange[100],
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 14,
    },
    onTripDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: colors.orange[500],
    },
    onTripBadgeText: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.orange[500],
      fontSize: 11,
      letterSpacing: 0.4,
    },
    onTripDrop: {
      fontFamily: colors.fonts.sora.extraBold,
      flex: 1,
      color: colors.text,
      fontSize: 16,
    },
    onTripTrack: {
      height: 5,
      borderRadius: 3,
      backgroundColor: colors.border,
      overflow: 'hidden',
      marginBottom: 14,
    },
    onTripFill: {
      height: '100%',
      borderRadius: 3,
      backgroundColor: colors.orange[500],
    },
    metricsRow: {
      flexDirection: 'row',
      backgroundColor: colors.surface,
      borderRadius: 14,
      paddingVertical: 14,
      paddingHorizontal: 8,
      marginBottom: 14,
    },
    metricCol: {
      flex: 1,
      alignItems: 'center',
    },
    metricLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.muted,
      fontSize: 10,
      letterSpacing: 0.5,
      marginBottom: 4,
    },
    metricValue: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 15,
    },
    onTripDriver: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 14,
    },
    onTripDriverName: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 15,
      marginBottom: 2,
    },
    miniAction: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: 8,
    },
    shareLiveBtn: {
      borderWidth: 1.5,
      borderColor: colors.border,
      borderRadius: 16,
      paddingVertical: 15,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.card,
    },
    shareLiveText: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 15,
    },
  });
}

