import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.gray[50],
    },
    hero: {
      backgroundColor: '#E8F5EC',
      borderBottomLeftRadius: 36,
      borderBottomRightRadius: 36,
      alignItems: 'center',
      paddingHorizontal: 28,
      paddingBottom: 28,
    },
    checkOuter: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: '#C8E6C9',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 18,
    },
    checkInner: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#1B5E20',
      alignItems: 'center',
      justifyContent: 'center',
    },
    title: {
      color: '#1B5E20',
      fontSize: 30,
      fontWeight: '800',
      textAlign: 'center',
      marginBottom: 10,
      letterSpacing: -0.3,
    },
    subtitle: {
      color: '#2E7D32',
      fontSize: 15,
      fontWeight: '500',
      textAlign: 'center',
      lineHeight: 22,
      paddingHorizontal: 8,
    },
    content: {
      flex: 1,
      paddingHorizontal: 20,
      paddingTop: 22,
    },
    starsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      marginBottom: 22,
    },
    receiptCard: {
      backgroundColor: colors.white,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.gray[200],
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 14,
    },
    receiptHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      marginBottom: 14,
    },
    receiptIcon: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: colors.gray[100],
      alignItems: 'center',
      justifyContent: 'center',
    },
    receiptCopy: {
      flex: 1,
      minWidth: 0,
    },
    receiptTitle: {
      color: colors.navy[900],
      fontSize: 15,
      fontWeight: '800',
      marginBottom: 3,
    },
    receiptSub: {
      color: colors.gray[500],
      fontSize: 12,
      fontWeight: '500',
    },
    divider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.gray[200],
      marginBottom: 10,
    },
    fareRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 8,
    },
    fareLabel: {
      color: colors.gray[600],
      fontSize: 14,
      fontWeight: '500',
    },
    fareValue: {
      color: colors.navy[900],
      fontSize: 14,
      fontWeight: '700',
    },
    totalRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingTop: 10,
      paddingBottom: 6,
    },
    totalLabel: {
      color: colors.navy[900],
      fontSize: 16,
      fontWeight: '800',
    },
    totalValue: {
      color: colors.navy[900],
      fontSize: 16,
      fontWeight: '800',
    },
    actionRow: {
      flexDirection: 'row',
      gap: 8,
      marginTop: 12,
    },
    actionBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      backgroundColor: colors.gray[100],
      borderRadius: 12,
      paddingVertical: 11,
      paddingHorizontal: 6,
    },
    actionText: {
      color: colors.navy[800],
      fontSize: 12,
      fontWeight: '700',
    },
    footer: {
      paddingHorizontal: 20,
      paddingTop: 12,
      backgroundColor: colors.gray[50],
    },
    homeBtn: {
      backgroundColor: colors.orange[500],
      borderRadius: 16,
      paddingVertical: 16,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 14,
    },
    homeText: {
      color: colors.white,
      fontSize: 16,
      fontWeight: '800',
    },
    rebookBtn: {
      alignItems: 'center',
      paddingVertical: 6,
    },
    rebookText: {
      color: colors.orange[500],
      fontSize: 15,
      fontWeight: '700',
    },
  });
}
