import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: 24,
      paddingBottom: 16,
    },
    closeBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 12,
    },
    avatar: {
      alignSelf: 'center',
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: colors.isDark ? '#1A3959' : colors.navy[800],
      borderWidth: 2.5,
      borderColor: colors.orange[500],
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 18,
    },
    avatarText: {
      color: colors.white,
      fontSize: 22,
      fontWeight: '800',
      letterSpacing: 0.5,
    },
    title: {
      color: colors.text,
      fontSize: 26,
      fontWeight: '800',
      textAlign: 'center',
      lineHeight: 34,
      marginBottom: 10,
      paddingHorizontal: 8,
    },
    subtitle: {
      color: colors.muted,
      fontSize: 14,
      fontWeight: '500',
      textAlign: 'center',
      lineHeight: 20,
      marginBottom: 22,
      paddingHorizontal: 12,
    },
    starsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      marginBottom: 28,
    },
    starHit: {
      padding: 2,
    },
    sectionLabel: {
      color: colors.muted,
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 0.9,
      marginBottom: 12,
    },
    tagsWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      marginBottom: 18,
    },
    tag: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: colors.border,
      backgroundColor: colors.card,
    },
    tagSelected: {
      borderColor: colors.orange[500],
      backgroundColor: colors.isDark ? '#1A3959' : colors.white,
    },
    tagText: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '600',
    },
    tagTextSelected: {
      color: colors.orange[500],
      fontWeight: '700',
    },
    noteInput: {
      minHeight: 88,
      borderRadius: 14,
      backgroundColor: colors.surface,
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 14,
      fontSize: 15,
      fontWeight: '500',
      color: colors.text,
      textAlignVertical: 'top',
      marginBottom: 24,
    },
    tipRow: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 8,
    },
    tipBtn: {
      flex: 1,
      height: 48,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.card,
    },
    tipBtnSelected: {
      borderColor: colors.orange[500],
      borderWidth: 2,
    },
    tipText: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
    },
    tipTextSelected: {
      color: colors.orange[500],
    },
    customInput: {
      marginTop: 12,
      height: 48,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: colors.orange[500],
      paddingHorizontal: 14,
      fontSize: 15,
      fontWeight: '600',
      color: colors.text,
      backgroundColor: colors.card,
    },
    footer: {
      paddingHorizontal: 24,
      paddingTop: 12,
      backgroundColor: colors.background,
    },
    submitBtn: {
      backgroundColor: colors.orange[500],
      borderRadius: 16,
      paddingVertical: 16,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 14,
    },
    submitText: {
      color: colors.white,
      fontSize: 16,
      fontWeight: '800',
    },
    skipBtn: {
      alignItems: 'center',
      paddingVertical: 6,
    },
    skipText: {
      color: colors.muted,
      fontSize: 15,
      fontWeight: '600',
    },
  });
}

