import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'transparent',
    },
    backdrop: {
      ...StyleSheet.absoluteFillObject,
    },
    backBtn: {
      position: 'absolute',
      left: 16,
      zIndex: 8,
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.white,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.navy[900],
      shadowOpacity: 0.12,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 2},
      elevation: 4,
    },
    radarArea: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: '8%',
      height: '42%',
      alignItems: 'center',
      justifyContent: 'center',
    },
    radarPulse: {
      position: 'absolute',
      width: 120,
      height: 120,
      borderRadius: 60,
      borderWidth: 2,
      borderColor: colors.orange[400],
      backgroundColor: 'rgba(255, 140, 60, 0.12)',
    },
    radarCore: {
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 2,
      shadowColor: colors.orange[600],
      shadowOpacity: 0.35,
      shadowRadius: 10,
      shadowOffset: {width: 0, height: 4},
      elevation: 6,
    },
    radarPin: {
      marginBottom: -4,
    },
    vehiclePin: {
      position: 'absolute',
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.white,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.navy[900],
      shadowOpacity: 0.14,
      shadowRadius: 6,
      shadowOffset: {width: 0, height: 2},
      elevation: 4,
      zIndex: 3,
    },
    sheet: {
      backgroundColor: colors.white,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingHorizontal: 20,
      paddingTop: 10,
      shadowColor: colors.navy[900],
      shadowOpacity: 0.14,
      shadowRadius: 18,
      shadowOffset: {width: 0, height: -4},
      elevation: 22,
    },
    grabber: {
      alignSelf: 'center',
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.gray[200],
      marginBottom: 16,
    },
    findingRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginBottom: 16,
    },
    spinnerWrap: {
      width: 40,
      height: 40,
      marginRight: 12,
      marginTop: 2,
      alignItems: 'center',
      justifyContent: 'center',
    },
    spinnerRing: {
      width: 36,
      height: 36,
      borderRadius: 18,
      borderWidth: 3,
      borderColor: colors.orange[200],
      borderTopColor: colors.orange[500],
      borderRightColor: colors.orange[500],
    },
    findingCopy: {
      flex: 1,
      minWidth: 0,
    },
    findingTitle: {
      color: colors.navy[900],
      fontSize: 20,
      fontWeight: '800',
      marginBottom: 4,
    },
    findingSub: {
      color: colors.gray[500],
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 20,
    },
    progressTrack: {
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.gray[200],
      overflow: 'hidden',
      marginBottom: 20,
    },
    progressFill: {
      height: '100%',
      borderRadius: 3,
      backgroundColor: colors.orange[500],
    },
    tripCard: {
      flexDirection: 'row',
      marginBottom: 16,
    },
    timeline: {
      width: 18,
      alignItems: 'center',
      marginRight: 12,
      paddingTop: 4,
      paddingBottom: 4,
    },
    pickupDot: {
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: colors.orange[500],
    },
    timelineLine: {
      width: 2,
      flex: 1,
      backgroundColor: colors.gray[300],
      marginVertical: 4,
    },
    dropSquare: {
      width: 12,
      height: 12,
      borderRadius: 3,
      backgroundColor: colors.navy[800],
    },
    tripCopy: {
      flex: 1,
      minWidth: 0,
      gap: 16,
    },
    tripBlock: {},
    tripLabel: {
      color: colors.gray[500],
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.8,
      marginBottom: 4,
    },
    tripAddress: {
      color: colors.navy[900],
      fontSize: 15,
      fontWeight: '700',
    },
    infoBox: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      backgroundColor: colors.gray[100],
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 16,
    },
    infoText: {
      flex: 1,
      color: colors.gray[600],
      fontSize: 13,
      fontWeight: '500',
      lineHeight: 19,
    },
    cancelBtn: {
      borderWidth: 1.5,
      borderColor: '#F5C4C4',
      backgroundColor: colors.white,
      borderRadius: 16,
      paddingVertical: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    cancelText: {
      color: colors.red[500],
      fontSize: 16,
      fontWeight: '800',
    },
    unavailableScroll: {
      paddingBottom: 4,
    },
    warnIconWrap: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.amber[100],
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
      marginTop: 2,
    },
    altLabel: {
      color: colors.gray[500],
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.9,
      marginBottom: 10,
    },
    altRow: {
      flexDirection: 'row',
      gap: 12,
      marginBottom: 18,
    },
    altCard: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: colors.gray[200],
      borderRadius: 18,
      paddingVertical: 14,
      paddingHorizontal: 12,
      backgroundColor: colors.white,
      gap: 8,
    },
    altName: {
      flex: 1,
      color: colors.navy[900],
      fontSize: 15,
      fontWeight: '700',
    },
    altPrice: {
      color: colors.orange[700],
      fontSize: 15,
      fontWeight: '800',
    },
    searchAgainBtn: {
      backgroundColor: colors.orange[500],
      borderRadius: 16,
      paddingVertical: 16,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 12,
    },
    searchAgainText: {
      color: colors.white,
      fontSize: 16,
      fontWeight: '800',
    },
    cancelLink: {
      alignItems: 'center',
      paddingVertical: 6,
    },
    cancelLinkText: {
      color: colors.navy[800],
      fontSize: 15,
      fontWeight: '700',
    },
    arrivalPill: {
      position: 'absolute',
      alignSelf: 'center',
      zIndex: 7,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.navy[900],
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 22,
      maxWidth: '78%',
      shadowColor: colors.navy[900],
      shadowOpacity: 0.2,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 2},
      elevation: 5,
    },
    arrivalPillText: {
      color: colors.white,
      fontSize: 13,
      fontWeight: '700',
      flexShrink: 1,
    },
    locateFab: {
      position: 'absolute',
      right: 16,
      zIndex: 8,
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.white,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.navy[900],
      shadowOpacity: 0.12,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 2},
      elevation: 4,
    },
    driverRouteLine: {
      position: 'absolute',
      left: '18%',
      right: '28%',
      top: '42%',
      height: 5,
      borderRadius: 3,
      backgroundColor: colors.orange[500],
      transform: [{rotate: '-12deg'}],
    },
    driverRouteDot: {
      position: 'absolute',
      left: '16%',
      top: '40%',
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: colors.orange[500],
      borderWidth: 2,
      borderColor: colors.white,
    },
    tripRouteGhost: {
      backgroundColor: colors.blue[500],
      opacity: 0.35,
      right: '12%',
    },
    tripRouteActive: {
      position: 'absolute',
      left: '18%',
      width: '28%',
      top: '42%',
      height: 5,
      borderRadius: 3,
      backgroundColor: colors.orange[500],
      transform: [{rotate: '-12deg'}],
    },
    tripCarPin: {
      position: 'absolute',
      left: '42%',
      top: '36%',
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.orange[500],
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 3,
      borderColor: colors.white,
      zIndex: 4,
    },
    tripDropPin: {
      position: 'absolute',
      right: '10%',
      top: '28%',
      zIndex: 3,
    },
    navBanner: {
      position: 'absolute',
      left: 16,
      zIndex: 8,
      maxWidth: '62%',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      backgroundColor: colors.navy[900],
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 16,
    },
    navCopy: {
      flexShrink: 1,
    },
    navTitle: {
      color: colors.white,
      fontSize: 13,
      fontWeight: '800',
    },
    navSub: {
      color: colors.navy[300],
      fontSize: 11,
      fontWeight: '500',
      marginTop: 2,
    },
    sosPill: {
      position: 'absolute',
      right: 16,
      zIndex: 8,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.white,
      borderWidth: 1.5,
      borderColor: colors.red[500],
      paddingHorizontal: 12,
      paddingVertical: 9,
      borderRadius: 20,
    },
    sosPillText: {
      color: colors.red[500],
      fontSize: 13,
      fontWeight: '800',
    },
  });
}
