import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.isDark ? colors.navy.darkBg1 : colors.green.pale,
      overflow: 'hidden',
    },
    mintWash: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      backgroundColor: colors.isDark ? colors.navy.darkBg2 : colors.green.pale,
      zIndex: 0,
    },
    softCircle: {
      position: 'absolute',
      backgroundColor: colors.isDark ? colors.alpha.green12 : colors.green.tint,
      zIndex: 0,
    },
    scrollFlex: {
      flex: 1,
      zIndex: 1,
      backgroundColor: 'transparent',
    },
    scrollContent: {
      flexGrow: 1,
    },
    heroContent: {
      alignItems: 'center',
      paddingHorizontal: 28,
      paddingBottom: 28,
      zIndex: 2,
    },
    checkBadge: {
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: colors.isDark ? colors.alpha.green25 : colors.green.badge,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 18,
    },
    title: {
      color: colors.isDark ? colors.green[400] : colors.green[800],
      fontSize: 30,
      fontWeight: '800',
      marginBottom: 10,
      textAlign: 'center',
      letterSpacing: -0.3,
    },
    meta: {
      color: colors.isDark ? colors.green.bright : colors.green[650],
      fontSize: 14,
      fontWeight: '500',
      textAlign: 'center',
      lineHeight: 21,
    },
    body: {
      paddingHorizontal: 20,
      paddingTop: 8,
      paddingBottom: 24,
      backgroundColor: colors.background,
      flexGrow: 1,
    },
    tripCard: {
      flexDirection: 'row',
      marginBottom: 18,
    },
    timeline: {
      width: 16,
      alignItems: 'center',
      marginRight: 12,
      paddingTop: 5,
      paddingBottom: 5,
    },
    pickupDot: {
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: colors.orange[500],
    },
    timelineLine: {
      width: 2,
      flex: 1,
      backgroundColor: colors.border,
      marginVertical: 5,
    },
    dropSquare: {
      width: 12,
      height: 12,
      borderRadius: 3,
      backgroundColor: colors.isDark ? colors.white : colors.navy[800],
    },
    tripCopy: {
      flex: 1,
      minWidth: 0,
      gap: 18,
    },
    tripBlock: {},
    tripLabel: {
      color: colors.muted,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.8,
      marginBottom: 4,
    },
    tripAddress: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
      lineHeight: 21,
    },
    fareCard: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 18,
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 8,
      marginBottom: 12,
      backgroundColor: colors.card,
    },
    fareTitle: {
      color: colors.muted,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.8,
      marginBottom: 8,
    },
    fareRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 8,
    },
    fareLabel: {
      color: colors.muted,
      fontSize: 14,
      fontWeight: '500',
      flex: 1,
      paddingRight: 12,
    },
    fareValue: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '700',
    },
    fareLabelPromo: {
      color: colors.green[600],
      fontWeight: '700',
    },
    fareValuePromo: {
      color: colors.green[600],
    },
    paidBox: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      backgroundColor: colors.isDark ? colors.alpha.green15 : colors.green[100],
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 13,
      marginBottom: 8,
    },
    paidCopy: {
      flex: 1,
      minWidth: 0,
    },
    paidTitle: {
      color: colors.green[600],
      fontSize: 15,
      fontWeight: '800',
      marginBottom: 2,
    },
    paidSub: {
      color: colors.isDark ? colors.text : colors.green[500],
      fontSize: 12,
      fontWeight: '500',
    },
    footer: {
      paddingHorizontal: 20,
      paddingTop: 14,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
      backgroundColor: colors.card,
    },
    totalRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 14,
    },
    totalLabel: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '800',
    },
    totalValue: {
      color: colors.text,
      fontSize: 22,
      fontWeight: '800',
    },
    rateBtn: {
      backgroundColor: colors.orange[500],
      borderRadius: 16,
      paddingVertical: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    rateText: {
      color: colors.white,
      fontSize: 16,
      fontWeight: '800',
    },
  });
}

