import { StyleSheet } from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.surface,
    },
    profile: {
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.isDark ? colors.navy[850] : colors.orange[50],
      marginHorizontal: 12,
      borderRadius: 18,
      marginBottom: 6,
    },
    profileRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    avatarContainer: {
      position: 'relative',
      marginRight: 12,
    },
    avatar: {
      width: 50,
      height: 50,
      borderRadius: 25,
      borderWidth: 2,
      borderColor: colors.primary,
    },
    avatarFallback: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: colors.isDark ? colors.orange[400] : colors.orange[200],
    },
    avatarInitial: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.white,
      fontSize: 18,
    },
    roleBadgeDot: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      width: 14,
      height: 14,
      borderRadius: 7,
      borderWidth: 2,
      borderColor: colors.surface,
    },
    roleBadgeDotDriver: {
      backgroundColor: colors.green[500],
    },
    roleBadgeDotPassenger: {
      backgroundColor: colors.primary,
    },
    profileInfo: {
      flex: 1,
      justifyContent: 'center',
    },
    nameRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    name: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 17,
    },
    roleTag: {
      alignSelf: 'flex-start',
      backgroundColor: colors.isDark ? colors.alpha.orange18 : colors.orange[150],
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 6,
      marginTop: 4,
      marginBottom: 3,
    },
    roleTagText: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.primary,
      fontSize: 10,
      letterSpacing: 0.5,
    },
    email: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.textMuted,
      fontSize: 12,
    },
    profileChevron: {
      marginLeft: 6,
    },
    scrollItems: {
      paddingTop: 8,
      paddingHorizontal: 12,
      paddingBottom: 16,
    },
    scrollView: {
      flex: 1,
    },
    item: {
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: 14,
      paddingVertical: 11,
      paddingHorizontal: 12,
      marginBottom: 4,
      position: 'relative',
    },
    itemActive: {
      backgroundColor: colors.isDark ? colors.alpha.orange22 : colors.orange[175],
    },
    iconBox: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: colors.isDark ? colors.navy[800] : colors.slate[50],
      alignItems: 'center',
      justifyContent: 'center',
    },
    iconBoxActive: {
      backgroundColor: colors.isDark ? colors.alpha.orange30 : colors.orange[250],
    },
    itemLabel: {
      fontFamily: colors.fonts.sora.bold,
      marginLeft: 12,
      color: colors.text,
      fontSize: 15,
      flex: 1,
    },
    itemLabelActive: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.primary,
    },
    activePillIndicator: {
      width: 4,
      height: 20,
      borderRadius: 2,
      backgroundColor: colors.primary,
      marginLeft: 6,
    },
    footer: {
      paddingHorizontal: 16,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      backgroundColor: colors.surface,
    },
    themeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 8,
      paddingHorizontal: 2,
      marginBottom: 8,
    },
    themeLeft: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    themeIconBox: {
      width: 34,
      height: 34,
      borderRadius: 10,
      backgroundColor: colors.isDark ? colors.navy[800] : colors.slate[50],
      alignItems: 'center',
      justifyContent: 'center',
    },
    themeTextWrap: {
      marginLeft: 12,
    },
    themeLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 15,
    },
    themeSub: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.textMuted,
      fontSize: 12,
      marginTop: 1,
    },
    logoutBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.isDark ? colors.alpha.red18 : colors.red[50],
      borderRadius: 14,
      paddingVertical: 12,
      paddingHorizontal: 14,
    },
    logoutIconBox: {
      width: 32,
      height: 32,
      borderRadius: 8,
      backgroundColor: colors.isDark ? colors.alpha.red25 : colors.red[100],
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    logoutText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.isDark ? colors.red[400] : colors.red[600],
      fontSize: 15,
    },
    versionText: {
      fontFamily: colors.fonts.sora.semiBold,
      color: colors.textMuted,
      fontSize: 12,
      textAlign: 'center',
      marginTop: 12,
    },
  });
}
