import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    backdrop: {
      flex: 1,
      backgroundColor: colors.alpha.black55,
      justifyContent: 'flex-end',
    },
    sheet: {
      backgroundColor: colors.card,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      maxHeight: '82%',
      minHeight: 420,
      paddingTop: 12,
      paddingHorizontal: 20,
      shadowColor: colors.isDark ? colors.black : colors.navy[900],
      shadowOffset: {width: 0, height: -4},
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 20,
    },
    dragHandle: {
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.border,
      alignSelf: 'center',
      marginBottom: 14,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 16,
    },
    title: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 18,
      color: colors.text,
    },
    closeButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.isDark ? colors.surface : colors.gray[100],
      borderWidth: colors.isDark ? 1 : 0,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.isDark ? colors.surface : colors.gray[50],
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 12,
      height: 46,
      marginBottom: 14,
      gap: 8,
    },
    searchInput: {
      flex: 1,
      fontFamily: colors.fonts.sora.regular,
      fontSize: 15,
      color: colors.text,
      paddingVertical: 0,
    },
    list: {
      paddingBottom: 24,
    },
    item: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 14,
      paddingHorizontal: 10,
      borderRadius: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    itemSelected: {
      backgroundColor: colors.isDark ? colors.alpha.orange20 : colors.orange.subtleBg,
    },
    flagEmoji: {
      fontFamily: colors.fonts.sora.regular,
      fontSize: 24,
      marginRight: 12,
    },
    flagImg: {
      width: 26,
      height: 18,
      borderRadius: 3,
      marginRight: 12,
    },
    countryName: {
      flex: 1,
      fontFamily: colors.fonts.sora.regular,
      fontSize: 15,
      color: colors.text,
    },
    countryNameSelected: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.primary,
    },
    dialCode: {
      fontFamily: colors.fonts.sora.regular,
      fontSize: 14,
      color: colors.textMuted,
      marginLeft: 8,
      marginRight: 8,
    },
    emptyContainer: {
      paddingVertical: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    emptyText: {
      fontFamily: colors.fonts.sora.regular,
      fontSize: 14,
      color: colors.textMuted,
    },
  });
}
