import { StyleSheet } from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.card,
    },
    headerBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.text,
    },

    // Progress Header
    progressSection: {
      paddingHorizontal: 20,
      paddingTop: 16,
      paddingBottom: 12,
      // backgroundColor: colors.card,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    stepKickerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 4,
    },
    stepKicker: {
      fontSize: 12,
      fontWeight: '800',
      color: colors.orange[500],
      letterSpacing: 0.8,
      textTransform: 'uppercase',
      marginBottom: 4,
    },
    percentText: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.gray[500],
      textAlign: 'right',
      marginTop: 6,
    },
    stepTitle: {
      fontSize: 22,
      fontWeight: '800',
      color: colors.text,
      marginBottom: 4,
    },
    stepSubtitle: {
      fontSize: 13,
      color: colors.gray[500],
      lineHeight: 18,
      marginBottom: 12,
    },
    progressBarRow: {
      flexDirection: 'row',
      gap: 6,
    },
    progressSegment: {
      flex: 1,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.gray[200],
    },
    progressSegmentActive: {
      backgroundColor: colors.orange[500],
    },

    scroll: {
      padding: 20,
    },

    // Card containers
    card: {
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },

    // Profile Photo Card
    profileCard: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: 16,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: colors.border,
    },
    avatarWrap: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: colors.gray[100],
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarTextWrap: {
      flex: 1,
      marginLeft: 14,
      marginRight: 8,
    },
    avatarTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.text,
    },
    avatarSub: {
      fontSize: 12,
      color: colors.gray[500],
      marginTop: 2,
    },
    uploadPillBtn: {
      backgroundColor: colors.orange.accentBg,
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 20,
    },
    uploadPillText: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.orange[600],
    },

    // Input fields
    fieldGroup: {
      marginBottom: 20,
    },
    labelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 6,
    },
    fieldLabel: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 6,
    },
    inputWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.card,
      borderWidth: 1.5,
      borderColor: colors.border,
      borderRadius: 14,
      paddingHorizontal: 14,
      height: 52,
    },
    inputWrapFocus: {
      borderColor: colors.orange[500],
    },
    inputWrapSuccess: {
      borderColor: colors.green[500],
    },
    textInput: {
      flex: 1,
      fontSize: 15,
      fontWeight: '600',
      color: colors.text,
      paddingVertical: 0,
    },
    fieldSubtext: {
      fontSize: 12,
      color: colors.gray[500],
      marginTop: 6,
    },

    // Verified Mobile Card
    verifiedMobileCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: 14,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: colors.border,
    },
    checkIconWrap: {
      width: 36,
      height: 36,
      borderRadius: 14,
      backgroundColor: colors.green.mint,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    mobileCopy: {
      flex: 1,
    },
    mobileNumber: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.text,
    },
    mobileSub: {
      fontSize: 12,
      color: colors.gray[500],
      marginTop: 2,
    },
    verifiedPill: {
      backgroundColor: colors.green.mint,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 12,
    },
    verifiedPillText: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.green[700],
    },

    // Country Picker Mobile Input Row
    mobileInputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: colors.border,
      height: 52,
      paddingHorizontal: 12,
      gap: 10,
    },
    countryPickerPrefix: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    countryDialCode: {
      fontFamily: colors.fonts?.sora?.bold || 'System',
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
    },
    prefixDividerLine: {
      width: 1,
      height: 20,
      backgroundColor: colors.border,
      marginLeft: 4,
    },
    mobileTextInputField: {
      flex: 1,
      fontFamily: colors.fonts?.sora?.regular || 'System',
      fontSize: 15,
      color: colors.text,
      paddingVertical: 0,
    },
    verifyActionBtn: {
      backgroundColor: colors.primary,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 12,
    },
    verifyActionBtnText: {
      fontFamily: colors.fonts?.sora?.bold || 'System',
      fontSize: 12,
      fontWeight: '700',
      color: colors.white,
    },

    // Side-by-side Upload Cards (DL Front / Back)
    twoColGrid: {
      flexDirection: 'row',
      gap: 12,
      marginBottom: 16,
    },
    docUploadBox: {
      flex: 1,
      backgroundColor: colors.white,
      borderRadius: 16,
      padding: 12,
      borderWidth: 1.5,
      borderColor: colors.border,
    },
    docUploadBoxVerified: {
      borderColor: '#86EFAC',
    },
    docUploadBoxError: {
      borderColor: '#FCA5A5',
      backgroundColor: '#FFF5F5',
    },
    docIllustration: {
      width: '100%',
      height: 70,
      borderRadius: 10,
      backgroundColor: colors.gray[100],
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 10,
      overflow: 'hidden',
    },
    docIllustrationFront: {
      width: '100%',
      height: 70,
      borderRadius: 10,
      backgroundColor: '#F1F5F9',
      justifyContent: 'center',
      paddingHorizontal: 10,
      marginBottom: 10,
      overflow: 'hidden',
    },
    docIllustrationBackError: {
      backgroundColor: '#94A3B8',
    },
    idCardSkeletonFront: {
      width: '100%',
      justifyContent: 'center',
    },
    skeletonLineTop: {
      width: '85%',
      height: 8,
      borderRadius: 4,
      backgroundColor: '#CBD5E1',
    },
    skeletonLineMid: {
      width: '60%',
      height: 6,
      borderRadius: 3,
      backgroundColor: '#CBD5E1',
      marginTop: 6,
    },
    skeletonBlockBottom: {
      width: '35%',
      height: 14,
      borderRadius: 4,
      backgroundColor: '#CBD5E1',
      marginTop: 12,
    },
    idCardSkeletonBack: {
      width: '100%',
      justifyContent: 'center',
    },
    skeletonLineTopWhite: {
      width: '80%',
      height: 5,
      borderRadius: 2.5,
      backgroundColor: 'rgba(255, 255, 255, 0.45)',
    },
    skeletonLineMidWhite: {
      width: '50%',
      height: 4,
      borderRadius: 2,
      backgroundColor: 'rgba(255, 255, 255, 0.45)',
      marginTop: 4,
    },
    skeletonIconWrap: {
      alignItems: 'center',
      justifyContent: 'center',
      marginVertical: 4,
    },
    skeletonBlockBottomWhite: {
      width: '35%',
      height: 12,
      borderRadius: 3,
      backgroundColor: 'rgba(255, 255, 255, 0.45)',
    },
    docTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 8,
    },
    docActionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      width: '100%',
    },
    statusPillVerified: {
      backgroundColor: '#DCFCE7',
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 12,
      alignSelf: 'flex-start',
    },
    statusPillVerifiedText: {
      fontSize: 12,
      fontWeight: '600',
      color: '#16A34A',
    },
    statusPillBlurred: {
      backgroundColor: '#FEE2E2',
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 12,
      alignSelf: 'flex-start',
    },
    statusPillBlurredText: {
      fontSize: 12,
      fontWeight: '600',
      color: '#EF4444',
    },
    btnPillGray: {
      backgroundColor: '#F1F5F9',
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 12,
    },
    btnPillGrayText: {
      fontSize: 12,
      fontWeight: '600',
      color: '#475569',
    },
    btnPillRed: {
      backgroundColor: '#FEE2E2',
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 12,
    },
    btnPillRedText: {
      fontSize: 12,
      fontWeight: '600',
      color: '#DC2626',
    },
    docBtnText: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.gray[600],
    },
    docBtnTextRed: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.danger,
    },

    // Warning Banner
    warningBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FEE2E2',
      borderRadius: 16,
      padding: 14,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: '#FCA5A5',
    },
    warningBannerIcon: {
      marginRight: 10,
    },
    warningBannerText: {
      flex: 1,
      fontSize: 12.5,
      fontWeight: '500',
      color: '#991B1B',
      lineHeight: 18,
    },

    // Checklist Section
    checklistCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: 18,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: colors.border,
    },
    checklistHeader: {
      fontSize: 12,
      fontWeight: '700',
      color: '#64748B',
      letterSpacing: 0.8,
      textTransform: 'uppercase',
      marginBottom: 14,
    },
    checkRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    checkIconMargin: {
      marginRight: 10,
    },
    checkText: {
      fontSize: 13.5,
      fontWeight: '500',
      color: colors.text,
      flex: 1,
    },

    // Vehicle Type Grid (Step 3)
    vehicleGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
      marginBottom: 20,
    },
    vehicleCard: {
      width: '48%',
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: 14,
      borderWidth: 1.5,
      borderColor: colors.border,
      position: 'relative',
    },
    vehicleCardActive: {
      borderColor: colors.orange[500],
      backgroundColor: colors.orange.subtleBg,
    },
    vehicleIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: colors.gray[100],
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 10,
    },
    vehicleIconWrapActive: {
      backgroundColor: colors.white,
    },
    vehicleName: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
    },
    vehicleMeta: {
      fontSize: 11,
      color: colors.gray[500],
      marginTop: 2,
    },
    vehicleCheckMark: {
      position: 'absolute',
      top: 20,
      right: 10,
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: colors.orange[600],
      alignItems: 'center',
      justifyContent: 'center',
    },

    // Horizontal Upload Row Cards
    docRowCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: 14,
      marginBottom: 12,
      borderWidth: 1.5,
      borderColor: colors.border,
    },
    docRowCardVerified: {
      borderColor: '#86EFAC',
    },
    docRowThumb: {
      width: 64,
      height: 64,
      borderRadius: 14,
      backgroundColor: '#F1F5F9',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 14,
    },
    docRowThumbTall: {
      width: 64,
      height: 84,
      borderRadius: 14,
      backgroundColor: '#F1F5F9',
      justifyContent: 'center',
      paddingHorizontal: 8,
      marginRight: 14,
      overflow: 'hidden',
    },
    tallDocSkeleton: {
      width: '100%',
      justifyContent: 'center',
    },
    plateIllustrationBadge: {
      width: 44,
      height: 24,
      borderRadius: 6,
      backgroundColor: '#CBD5E1',
      alignItems: 'center',
      justifyContent: 'center',
    },
    plateIllustrationText: {
      fontSize: 11,
      fontWeight: '800',
      color: '#1E293B',
    },
    docRowCopy: {
      flex: 1,
    },
    docRowTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 2,
    },
    docRowMeta: {
      fontSize: 12,
      color: colors.gray[500],
      marginBottom: 2,
    },
    docRowMetaSub: {
      fontSize: 11.5,
      color: colors.gray[400],
      marginBottom: 4,
    },
    statusPillRequired: {
      backgroundColor: '#F1F5F9',
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderRadius: 12,
      alignSelf: 'flex-start',
    },
    statusPillRequiredText: {
      fontSize: 11,
      fontWeight: '600',
      color: '#64748B',
    },
    docRowFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 8,
      width: '100%',
    },
    docRowButtonsGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    btnPillGray: {
      backgroundColor: '#F1F5F9',
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 12,
    },
    btnPillGrayText: {
      fontSize: 12,
      fontWeight: '600',
      color: '#475569',
    },
    btnPillOrange: {
      backgroundColor: '#FFF7ED',
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 12,
    },
    btnPillOrangeText: {
      fontSize: 12,
      fontWeight: '700',
      color: '#EA580C',
    },
    docRowAction: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    successSubtextRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 6,
      gap: 6,
    },
    successSubtext: {
      fontSize: 13,
      fontWeight: '500',
      color: '#15803D',
    },

    // Expiry Notice Box (Amber)
    amberNoticeBox: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      backgroundColor: '#FFFBEB',
      borderRadius: 16,
      padding: 16,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: '#FDE68A',
    },
    amberNoticeCopy: {
      flex: 1,
    },
    amberNoticeTitle: {
      fontSize: 13.5,
      fontWeight: '700',
      color: '#78350F',
      marginBottom: 2,
    },
    amberNoticeText: {
      fontSize: 12.5,
      color: '#92400E',
      lineHeight: 17,
    },

    // Bank Branch Card (Green light)
    bankBranchCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.green.mint,
      borderRadius: 16,
      padding: 14,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: colors.green[200],
    },
    bankBranchIconWrap: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: colors.white,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    bankBranchTitle: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.text,
    },
    bankBranchSub: {
      fontSize: 12,
      color: colors.gray[600],
      marginTop: 2,
    },
    bankBranchVerified: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.green[700],
      marginTop: 2,
    },

    // Review & Submit Styles (Step 6)
    reviewCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: 14,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    reviewIconWrap: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: colors.green.mint,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    reviewCopy: {
      flex: 1,
    },
    reviewTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.text,
    },
    reviewMeta: {
      fontSize: 12,
      color: colors.gray[500],
      marginTop: 2,
    },
    reviewRight: {
      alignItems: 'flex-end',
      gap: 6,
    },
    reviewCountText: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.green[700],
    },
    editPillBtn: {
      backgroundColor: colors.gray[100],
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderRadius: 12,
    },
    editPillText: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.gray[700],
    },
    confirmCheckboxCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },
    confirmRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
    },
    checkboxBox: {
      width: 22,
      height: 22,
      borderRadius: 6,
      borderWidth: 1.5,
      borderColor: colors.gray[400],
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
      marginTop: 1,
    },
    checkboxBoxActive: {
      backgroundColor: colors.orange[500],
      borderColor: colors.orange[500],
    },
    confirmText: {
      flex: 1,
      fontSize: 13,
      fontWeight: '600',
      color: colors.text,
      lineHeight: 18,
    },
    termsLinkText: {
      fontSize: 12.5,
      fontWeight: '700',
      color: colors.orange[600],
      marginTop: 8,
      marginLeft: 34,
    },
    verifyInfoBox: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      backgroundColor: colors.orange.subtleBg,
      borderRadius: 14,
      padding: 14,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: colors.amber[200],
    },
    verifyInfoText: {
      flex: 1,
      fontSize: 12.5,
      color: colors.amber[900],
      marginLeft: 10,
      lineHeight: 17,
      fontWeight: '500',
    },

    // Info Card
    infoCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.card,
      borderRadius: 14,
      padding: 14,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: colors.border,
    },
    infoCardText: {
      flex: 1,
      fontSize: 12,
      color: colors.gray[600],
      marginLeft: 10,
      lineHeight: 17,
    },

    // Bottom Navigation Bar
    footer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingTop: 14,
      backgroundColor: colors.card,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      gap: 12,
    },
    btnBack: {
      flex: 1,
      height: 52,
    },
    btnBackText: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.text,
    },
    btnNext: {
      flex: 2,
      height: 52,
    },
    btnNextFull: {
      flex: 1,
      height: 52,
    },
    btnNextText: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.white,
    },
  });
}
