import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.gray[100],
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 12,
      paddingBottom: 12,
      backgroundColor: colors.white,
    },
    headerBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      color: colors.navy[900],
      fontSize: 17,
      fontWeight: '700',
    },
    scroll: {
      paddingHorizontal: 16,
      paddingTop: 16,
    },
    heroCard: {
      backgroundColor: colors.navy[900],
      borderRadius: 22,
      paddingVertical: 20,
      paddingHorizontal: 18,
      marginBottom: 14,
      overflow: 'hidden',
      minHeight: 132,
      justifyContent: 'center',
    },
    heroGlow: {
      position: 'absolute',
      right: -48,
      top: -28,
      width: 180,
      height: 180,
      borderRadius: 90,
      backgroundColor: colors.green[600],
      opacity: 0.45,
    },
    heroCheck: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: 'rgba(38, 168, 94, 0.28)',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 12,
    },
    heroTitle: {
      color: colors.white,
      fontSize: 22,
      fontWeight: '800',
      letterSpacing: -0.3,
      paddingRight: 48,
    },
    heroMeta: {
      color: colors.navy[300],
      fontSize: 13,
      fontWeight: '500',
      marginTop: 6,
      paddingRight: 40,
    },
    card: {
      backgroundColor: colors.white,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.gray[200],
      padding: 16,
      marginBottom: 12,
    },
    cardTitle: {
      color: colors.navy[900],
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 14,
    },
    proofRow: {
      flexDirection: 'row',
      gap: 14,
      alignItems: 'flex-start',
    },
    photoCol: {
      width: 112,
      alignItems: 'center',
    },
    photoBox: {
      width: 112,
      height: 112,
      borderRadius: 14,
      backgroundColor: colors.gray[100],
      alignItems: 'center',
      justifyContent: 'center',
    },
    photoLabel: {
      color: colors.gray[500],
      fontSize: 11,
      fontWeight: '500',
      textAlign: 'center',
      marginTop: 8,
    },
    proofCopy: {
      flex: 1,
      minWidth: 0,
      justifyContent: 'space-between',
      paddingVertical: 2,
      gap: 12,
    },
    proofLabel: {
      color: colors.gray[500],
      fontSize: 12,
      fontWeight: '500',
    },
    proofValue: {
      color: colors.navy[900],
      fontSize: 15,
      fontWeight: '700',
      marginTop: 2,
    },
    proofValueGreen: {
      color: colors.green[600],
    },
    receiptMeta: {
      color: colors.gray[500],
      fontSize: 12,
      fontWeight: '400',
      marginTop: -8,
      marginBottom: 14,
    },
    fareRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      marginBottom: 10,
    },
    fareLabel: {
      flex: 1,
      color: colors.gray[500],
      fontSize: 13,
      fontWeight: '400',
    },
    fareAmount: {
      color: colors.gray[600],
      fontSize: 13,
      fontWeight: '600',
    },
    divider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.gray[200],
      marginVertical: 6,
      marginBottom: 12,
    },
    paidRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      marginBottom: 10,
    },
    paidLabel: {
      flex: 1,
      color: colors.navy[900],
      fontSize: 14,
      fontWeight: '700',
    },
    paidAmount: {
      color: colors.navy[900],
      fontSize: 16,
      fontWeight: '800',
    },
    downloadText: {
      color: colors.orange[600],
      fontSize: 14,
      fontWeight: '700',
    },
    rateRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    stars: {
      flexDirection: 'row',
      gap: 6,
    },
    tipText: {
      color: colors.orange[600],
      fontSize: 14,
      fontWeight: '700',
    },
    footer: {
      paddingHorizontal: 16,
      paddingTop: 10,
      backgroundColor: colors.gray[100],
    },
    sendBtn: {
      backgroundColor: colors.orange[500],
      borderRadius: 16,
      paddingVertical: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sendText: {
      color: colors.white,
      fontSize: 16,
      fontWeight: '700',
    },
  });
}
