import { StyleSheet } from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.slate[50],
    },

    scrollContent: {
      paddingBottom: 110,
    },

    // Top Dark Navy Hero
    navyHero: {
      backgroundColor: colors.navy[850],
      borderBottomLeftRadius: 32,
      borderBottomRightRadius: 32,
      paddingHorizontal: 16,
      paddingBottom: 24,
      position: 'relative',
      overflow: 'hidden',
    },
    heroDeco: {
      position: 'absolute',
      right: -40,
      top: -20,
      width: 200,
      height: 200,
      borderRadius: 100,
      backgroundColor: colors.alpha.white04,
    },
    menuBtn: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: colors.alpha.white10,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
    },
    profileRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
    },
    avatarCircle: {
      width: 64,
      height: 64,
      borderRadius: 32,
      borderWidth: 2,
      borderColor: colors.primary,
      backgroundColor: colors.slate[800],
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    avatarText: {
      color: colors.white,
      fontSize: 20,
      fontWeight: '900',
    },
    profileInfo: {
      flex: 1,
      marginRight: 10,
    },
    nameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 3,
    },
    nameText: {
      fontSize: 20,
      fontWeight: '900',
      color: colors.white,
    },
    statsText: {
      fontSize: 12.5,
      fontWeight: '500',
      color: colors.navy[350],
      marginBottom: 3,
    },
    contactText: {
      fontSize: 12,
      fontWeight: '500',
      color: colors.slate[500],
    },
    editBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.alpha.white10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    kycBanner: {
      backgroundColor: colors.alpha.green95,
      borderRadius: 20,
      paddingHorizontal: 12,
      paddingVertical: 7,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      marginTop: 16,
      alignSelf: 'flex-start',
    },
    kycText: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.green[350] || colors.green[400],
    },

    // Section Titles
    sectionTitle: {
      fontSize: 11.5,
      fontWeight: '700',
      color: colors.slate[500],
      letterSpacing: 0.6,
      textTransform: 'uppercase',
      marginHorizontal: 16,
      marginTop: 22,
      marginBottom: 10,
    },

    // Vehicle Card
    card: {
      backgroundColor: colors.white,
      borderRadius: 22,
      padding: 18,
      marginHorizontal: 16,
      shadowColor: colors.black,
      shadowOpacity: 0.04,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    vehicleHead: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    vehicleLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      flex: 1,
    },
    vehicleIconBox: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: colors.slate[50],
      borderWidth: 1,
      borderColor: colors.slate[100],
      alignItems: 'center',
      justifyContent: 'center',
    },
    vehicleTitle: {
      fontSize: 16,
      fontWeight: '800',
      color: colors.slate[900],
    },
    vehicleSub: {
      fontSize: 13,
      fontWeight: '500',
      color: colors.slate[500],
      marginTop: 2,
    },
    platePill: {
      backgroundColor: colors.navy[850],
      borderRadius: 8,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    plateText: {
      color: colors.white,
      fontSize: 13,
      fontWeight: '900',
      letterSpacing: 0.8,
    },
    warnBox: {
      backgroundColor: colors.amber[50],
      borderWidth: 1,
      borderColor: colors.amber[100],
      borderRadius: 14,
      padding: 12,
      marginTop: 14,
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
    },
    warnText: {
      flex: 1,
      fontSize: 12.5,
      fontWeight: '500',
      color: colors.amber[800],
      lineHeight: 17,
    },
    vehicleActionBtn: {
      borderWidth: 1.5,
      borderColor: colors.navy[850],
      borderRadius: 14,
      height: 46,
      marginTop: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.white,
    },
    vehicleActionText: {
      color: colors.navy[850],
      fontSize: 14.5,
      fontWeight: '800',
    },

    // List Items Card
    listCard: {
      backgroundColor: colors.white,
      borderRadius: 22,
      marginHorizontal: 16,
      paddingHorizontal: 16,
      shadowColor: colors.black,
      shadowOpacity: 0.04,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    listItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 14,
    },
    listBorder: {
      borderBottomWidth: 1,
      borderBottomColor: colors.slate[100],
    },
    listLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      flex: 1,
      marginRight: 8,
    },
    listIconBox: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: colors.slate[50],
      borderWidth: 1,
      borderColor: colors.slate[100],
      alignItems: 'center',
      justifyContent: 'center',
    },
    listInfo: {
      flex: 1,
    },
    listTitle: {
      fontSize: 15,
      fontWeight: '800',
      color: colors.slate[900],
    },
    listSub: {
      fontSize: 12.5,
      fontWeight: '500',
      color: colors.slate[500],
      marginTop: 2,
    },
  });
}
