import { StyleSheet } from 'react-native';

export default colors =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.card,
    },
    headerBtn: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: colors.isDark ? colors.gray[800] : colors.gray[100],
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 18,
      color: colors.text,
      textAlign: 'center',
    },
    headerRightPlaceholder: {
      width: 40,
    },
    scrollContent: {
      padding: 20,
      paddingBottom: 40,
    },
    subtitleText: {
      fontFamily: colors.fonts.sora.regular,
      fontSize: 13,
      color: colors.isDark ? colors.gray[300] : colors.gray[600],
      lineHeight: 19,
      marginBottom: 20,
      textAlign: 'center',
    },

    // Viewfinder / Scanner Area
    scannerContainer: {
      width: '100%',
      aspectRatio: 4 / 3,
      borderRadius: 20,
      overflow: 'hidden',
      backgroundColor: '#000000',
      borderWidth: 2,
      borderColor: colors.border,
      position: 'relative',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 24,
    },
    capturedImage: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
    },
    liveCameraPreview: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      width: '100%',
      height: '100%',
    },
    liveTorchBtn: {
      position: 'absolute',
      top: 14,
      right: 14,
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: 'rgba(0, 0, 0, 0.65)',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 10,
    },
    liveStatusBadge: {
      position: 'absolute',
      bottom: 12,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(15, 23, 42, 0.88)',
      paddingHorizontal: 14,
      paddingVertical: 7,
      borderRadius: 20,
      gap: 8,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.15)',
    },
    pulseDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: '#22C55E',
    },
    liveStatusText: {
      fontFamily: colors.fonts.sora.medium,
      fontSize: 12,
      color: colors.white,
    },
    viewfinderOverlay: {
      ...StyleSheet.absoluteFillObject,
      alignItems: 'center',
      justifyContent: 'center',
      // backgroundColor: 'rgba(0, 0, 0, 0.35)',
    },
    targetFrame: {
      width: '82%',
      height: 90,
      borderRadius: 14,
      borderWidth: 2,
      borderColor: colors.orange[500],
      borderStyle: 'dashed',
      position: 'relative',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255, 112, 6, 0.08)',
    },
    scanLaserLine: {
      position: 'absolute',
      left: 8,
      right: 8,
      height: 2.5,
      borderRadius: 2,
      backgroundColor: colors.orange[500],
      shadowColor: colors.orange[500],
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.9,
      shadowRadius: 8,
      elevation: 4,
    },
    scanLaserLineInactive: {
      opacity: 0.45,
    },
    pulseDotScanning: {
      backgroundColor: colors.orange[500],
    },
    targetCornerTL: {
      position: 'absolute',
      top: -2,
      left: -2,
      width: 18,
      height: 18,
      borderTopWidth: 4,
      borderLeftWidth: 4,
      borderColor: colors.orange[500],
      borderTopLeftRadius: 6,
    },
    targetCornerTR: {
      position: 'absolute',
      top: -2,
      right: -2,
      width: 18,
      height: 18,
      borderTopWidth: 4,
      borderRightWidth: 4,
      borderColor: colors.orange[500],
      borderTopRightRadius: 6,
    },
    targetCornerBL: {
      position: 'absolute',
      bottom: -2,
      left: -2,
      width: 18,
      height: 18,
      borderBottomWidth: 4,
      borderLeftWidth: 4,
      borderColor: colors.orange[500],
      borderBottomLeftRadius: 6,
    },
    targetCornerBR: {
      position: 'absolute',
      bottom: -2,
      right: -2,
      width: 18,
      height: 18,
      borderBottomWidth: 4,
      borderRightWidth: 4,
      borderColor: colors.orange[500],
      borderBottomRightRadius: 6,
    },
    frameHintText: {
      fontFamily: colors.fonts.sora.medium,
      fontSize: 11.5,
      color: colors.white,
      textAlign: 'center',
      textShadowColor: 'rgba(0,0,0,0.8)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 3,
    },
    emptyStateIconWrap: {
      width: 68,
      height: 68,
      borderRadius: 34,
      backgroundColor: 'rgba(255, 255, 255, 0.12)',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 12,
    },
    emptyStatePrompt: {
      fontFamily: colors.fonts.sora.semiBold,
      fontSize: 14,
      color: colors.white,
      marginBottom: 4,
    },
    emptyStateSubtext: {
      fontFamily: colors.fonts.sora.regular,
      fontSize: 12,
      color: '#94A3B8',
    },

    // Processing / Detecting Overlay
    detectingOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0, 0, 0, 0.72)',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 20,
    },
    detectingSpinner: {
      marginBottom: 14,
    },
    detectingTitle: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 16,
      color: colors.white,
      marginBottom: 6,
    },
    detectingSubtitle: {
      fontFamily: colors.fonts.sora.regular,
      fontSize: 12.5,
      color: '#CBD5E1',
      textAlign: 'center',
    },

    // Action Buttons Row (Scan / Upload)
    actionButtonsRow: {
      flexDirection: 'row',
      gap: 12,
      marginBottom: 20,
    },
    actionBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderRadius: 14,
      backgroundColor: colors.card,
      borderWidth: 1.5,
      borderColor: colors.border,
      gap: 8,
    },
    actionBtnPrimary: {
      backgroundColor: colors.orange[500],
      borderColor: colors.orange[500],
    },
    actionBtnDanger: {
      backgroundColor: '#DC2626',
      borderColor: '#DC2626',
    },
    emptyStateContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      padding: 24,
    },
    actionBtnText: {
      fontFamily: colors.fonts.sora.semiBold,
      fontSize: 14,
      color: colors.text,
    },
    actionBtnTextPrimary: {
      color: colors.white,
    },

    // Result Card
    resultCard: {
      backgroundColor: colors.card,
      borderRadius: 20,
      padding: 20,
      borderWidth: 1.5,
      borderColor: colors.border,
      marginBottom: 24,
      alignItems: 'center',
    },
    resultHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      width: '100%',
      marginBottom: 16,
    },
    resultLabel: {
      fontFamily: colors.fonts.sora.semiBold,
      fontSize: 13,
      color: colors.isDark ? colors.gray[300] : colors.gray[600],
      textTransform: 'uppercase',
      letterSpacing: 0.8,
    },
    confidenceBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#DCFCE7',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
      gap: 4,
    },
    confidenceText: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 11.5,
      color: '#15803D',
    },

    // Authentic Number Plate Graphic Card
    plateGraphicContainer: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      borderRadius: 12,
      borderWidth: 3,
      borderColor: '#1E293B',
      overflow: 'hidden',
      paddingVertical: 12,
      paddingHorizontal: 14,
      marginBottom: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
    },
    plateIndStripe: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingRight: 12,
      borderRightWidth: 1.5,
      borderRightColor: '#CBD5E1',
      marginRight: 14,
    },
    plateIndChakra: {
      width: 14,
      height: 14,
      borderRadius: 7,
      borderWidth: 1.5,
      borderColor: '#1E3A8A',
      marginBottom: 2,
    },
    plateIndText: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 10,
      color: '#1E3A8A',
      letterSpacing: 0.5,
    },
    plateNumberText: {
      flex: 1,
      fontFamily: colors.fonts.sora.bold,
      fontSize: 22,
      color: '#0F172A',
      letterSpacing: 2,
      textAlign: 'center',
    },
    plateNumberInput: {
      flex: 1,
      fontFamily: colors.fonts.sora.bold,
      fontSize: 20,
      color: '#0F172A',
      letterSpacing: 2,
      textAlign: 'center',
      paddingVertical: 0,
    },
    editHintText: {
      fontFamily: colors.fonts.sora.regular,
      fontSize: 11,
      color: colors.isDark ? colors.gray[400] : colors.gray[500],
      marginTop: 2,
      marginBottom: 6,
    },
    normalizedHint: {
      fontFamily: colors.fonts.sora.regular,
      fontSize: 11.5,
      color: colors.isDark ? colors.gray[400] : colors.gray[500],
    },

    // Error Box
    errorCard: {
      backgroundColor: '#FEF2F2',
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: '#FECACA',
      padding: 16,
      marginBottom: 24,
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
    },
    errorIconWrap: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: '#FEE2E2',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 2,
    },
    errorCopy: {
      flex: 1,
    },
    errorTitle: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 13.5,
      color: '#991B1B',
      marginBottom: 4,
    },
    errorDesc: {
      fontFamily: colors.fonts.sora.regular,
      fontSize: 12,
      color: '#B91C1C',
      lineHeight: 17,
    },

    // Bottom Action Buttons
    confirmSection: {
      marginTop: 4,
    },
    confirmBtn: {
      marginBottom: 12,
    },
    rescanBtn: {
      paddingVertical: 14,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 14,
      backgroundColor: colors.isDark ? colors.gray[800] : colors.gray[100],
    },
    retryBtn: {
      marginTop: 4,
    },
    rescanBtnText: {
      fontFamily: colors.fonts.sora.semiBold,
      fontSize: 14,
      color: colors.text,
    },

    // Tips card
    tipsCard: {
      backgroundColor: colors.isDark ? colors.alpha.orange10 : '#FFF7ED',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.isDark ? colors.alpha.orange30 : '#FFEDD5',
      padding: 16,
      marginTop: 10,
    },
    tipsHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 8,
    },
    tipsTitle: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 13,
      color: colors.orange[700] || '#C2410C',
    },
    tipsItem: {
      fontFamily: colors.fonts.sora.regular,
      fontSize: 11.5,
      color: colors.isDark ? colors.gray[300] : '#7C2D12',
      lineHeight: 18,
      marginBottom: 3,
    },
  });
