import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: '#071C31',
    },
    scroll: {
      paddingHorizontal: 18,
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginBottom: 18,
    },
    closeBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(255,255,255,0.12)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      color: colors.white,
      fontSize: 22,
      fontWeight: '800',
      letterSpacing: -0.3,
    },
    sosBlock: {
      alignItems: 'center',
      marginBottom: 22,
      paddingTop: 8,
    },
    sosCircle: {
      width: 168,
      height: 168,
      borderRadius: 84,
      backgroundColor: colors.white,
      borderWidth: 2.5,
      borderColor: colors.red[500],
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 18,
      shadowColor: '#E73D3D',
      shadowOpacity: 0.45,
      shadowRadius: 24,
      shadowOffset: {width: 0, height: 6},
      elevation: 12,
    },
    sosCircleHolding: {
      transform: [{scale: 0.96}],
      shadowOpacity: 0.65,
    },
    sosTitle: {
      color: colors.red[500],
      fontSize: 34,
      fontWeight: '900',
      letterSpacing: 1,
      marginTop: 6,
    },
    sosHoldHint: {
      color: colors.gray[400],
      fontSize: 13,
      fontWeight: '500',
      marginTop: 2,
    },
    sosHeadline: {
      color: colors.white,
      fontSize: 20,
      fontWeight: '800',
      textAlign: 'center',
      marginBottom: 8,
      letterSpacing: -0.2,
    },
    sosBody: {
      color: colors.navy[300],
      fontSize: 14,
      fontWeight: '400',
      textAlign: 'center',
      lineHeight: 20,
      paddingHorizontal: 10,
      maxWidth: 320,
    },
    sosCircleAlerted: {
      width: 168,
      height: 168,
      borderRadius: 84,
      backgroundColor: colors.red[500],
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 18,
      shadowColor: '#FF2D2D',
      shadowOpacity: 0.9,
      shadowRadius: 36,
      shadowOffset: {width: 0, height: 0},
      elevation: 20,
      boxShadow: [
        {
          offsetX: 0,
          offsetY: 0,
          blurRadius: 40,
          spreadDistance: 6,
          color: 'rgba(255, 45, 45, 0.7)',
        },
      ],
    },
    sosTitleAlerted: {
      color: colors.white,
      fontSize: 34,
      fontWeight: '900',
      letterSpacing: 1,
      marginTop: 6,
    },
    sosHoldHintAlerted: {
      color: 'rgba(255,255,255,0.85)',
      fontSize: 13,
      fontWeight: '500',
      marginTop: 2,
    },
    sosBodyAlerted: {
      color: '#E8C4A8',
      fontSize: 14,
      fontWeight: '400',
      textAlign: 'center',
      lineHeight: 20,
      paddingHorizontal: 10,
      maxWidth: 320,
    },
    statusCard: {
      backgroundColor: 'rgba(255,255,255,0.04)',
      borderRadius: 18,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.35)',
      paddingHorizontal: 14,
      paddingVertical: 6,
      marginBottom: 12,
    },
    statusRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: 'rgba(255,255,255,0.12)',
    },
    statusRowLast: {
      borderBottomWidth: 0,
    },
    statusCheck: {
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: colors.green[500],
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 1,
    },
    statusSpinner: {
      width: 22,
      height: 22,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 1,
    },
    statusCopy: {
      flex: 1,
      minWidth: 0,
    },
    statusTitle: {
      color: colors.white,
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 3,
      lineHeight: 19,
    },
    statusMeta: {
      color: 'rgba(232,196,168,0.7)',
      fontSize: 12,
      fontWeight: '500',
    },
    contactsCard: {
      backgroundColor: 'rgba(255,255,255,0.06)',
      borderRadius: 18,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      paddingHorizontal: 14,
      paddingTop: 12,
      paddingBottom: 4,
      marginBottom: 12,
    },
    contactsHead: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    contactsLabel: {
      color: colors.navy[400],
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1.1,
    },
    manageText: {
      color: colors.orange[500],
      fontSize: 14,
      fontWeight: '700',
    },
    contactRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingVertical: 12,
    },
    contactRowBorder: {
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: 'rgba(255,255,255,0.1)',
    },
    avatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(255,255,255,0.12)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarText: {
      color: colors.white,
      fontSize: 13,
      fontWeight: '700',
    },
    contactCopy: {
      flex: 1,
      minWidth: 0,
    },
    contactName: {
      color: colors.white,
      fontSize: 15,
      fontWeight: '700',
      marginBottom: 2,
    },
    contactMeta: {
      color: colors.navy[300],
      fontSize: 12,
      fontWeight: '500',
    },
    checkWrap: {
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: colors.green[500],
      alignItems: 'center',
      justifyContent: 'center',
    },
    quickRow: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 12,
    },
    quickBtn: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
      backgroundColor: 'rgba(255,255,255,0.06)',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      paddingVertical: 14,
      paddingHorizontal: 6,
    },
    quickBtnAlerted: {
      backgroundColor: 'rgba(255,255,255,0.04)',
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.35)',
    },
    quickLabel: {
      color: colors.white,
      fontSize: 13,
      fontWeight: '700',
      marginTop: 4,
    },
    quickSub: {
      color: colors.navy[300],
      fontSize: 12,
      fontWeight: '500',
    },
    locationCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: 'rgba(255,255,255,0.06)',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      paddingVertical: 14,
      paddingHorizontal: 14,
      marginBottom: 14,
    },
    locationCardAlerted: {
      backgroundColor: 'rgba(255,255,255,0.04)',
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.35)',
    },
    locationCopy: {
      flex: 1,
      minWidth: 0,
    },
    locationTitle: {
      color: colors.white,
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 3,
    },
    locationMeta: {
      color: colors.navy[300],
      fontSize: 12,
      fontWeight: '500',
    },
    shareBtn: {
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.35)',
      borderRadius: 16,
      paddingVertical: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255,255,255,0.04)',
    },
    shareText: {
      color: colors.white,
      fontSize: 16,
      fontWeight: '700',
    },
  });
}
