import { StyleSheet } from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: colors.navy[900],
    },
    list: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: colors.navy[900],
    },
    bottomFill: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: colors.navy[900],
      zIndex: 0,
    },
    page: {
      flexDirection: 'column',
      backgroundColor: colors.navy[900],
    },
    header: {
      position: 'absolute',
      left: 20,
      right: 20,
      zIndex: 4,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    logo: {
      width: 40,
      height: 40,
      borderRadius: 12,
      overflow: 'hidden',
    },
    skip: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingTop: 9,
      paddingRight: 18,
      paddingBottom: 9,
      paddingLeft: 18,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.orange.borderSoft,
      backgroundColor: colors.alpha.white75,
    },
    skipLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.navy[900],
      fontSize: 14,
      fontWeight: '700',
    },
    hero: {
      flex: 1,
      minHeight: 0,
      backgroundColor: colors.orange.lightBadge,
      overflow: 'hidden',
    },
    heroFill: {
      flex: 1,
      minHeight: 0,
    },
    heroFillPay: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 24,
    },
    heroImage: {
      width: '100%',
      height: '100%',
    },
    payImage: {
      width: '100%',
      maxWidth: 280,
      maxHeight: '100%',
      aspectRatio: 322 / 228,
    },
    wave: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: -1,
      width: '100%',
      zIndex: 2,
    },
    panel: {
      flexGrow: 0,
      flexShrink: 0,
      backgroundColor: colors.navy[900],
      paddingHorizontal: 24,
    },
    badge: {
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.alpha.orangeBrand12,
      borderWidth: 1,
      borderColor: colors.alpha.orangeBrand28,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 20,
    },
    badgeDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.orange[500],
    },
    badgeLabel: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.orange[400],
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 1.1,
    },
    title: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.white,
      fontWeight: '800',
      letterSpacing: -0.4,
    },
    body: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.alpha.slateAlpha88,
      fontSize: 15,
      lineHeight: 22,
      marginTop: 10,
    },
    dots: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 8,
    },
    dot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.alpha.white22,
    },
    dotActive: {
      width: 22,
      backgroundColor: colors.orange[600],
    },
    cta: {
      minHeight: 52,
      height: 52,
      borderRadius: 16,
      backgroundColor: colors.orange[600],
    },
  });
}
