import {StyleSheet, Dimensions} from 'react-native';

const SCREEN_H = Dimensions.get('window').height;

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: 'transparent',
    },
    backdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: colors.overlay,
    },
    mapBg: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: colors.map?.land || colors.background,
    },
    mapImage: {
      ...StyleSheet.absoluteFillObject,
      width: '100%',
      height: '100%',
      opacity: colors.isDark ? 0.6 : 0.85,
    },
    backBtn: {
      position: 'absolute',
      left: 16,
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.card,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.shadow,
      shadowOpacity: 0.14,
      shadowRadius: 10,
      shadowOffset: {width: 0, height: 3},
      elevation: 5,
      zIndex: 5,
    },
    sheet: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      maxHeight: SCREEN_H * 0.82,
      backgroundColor: colors.card,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      shadowColor: colors.shadow,
      shadowOpacity: 0.16,
      shadowRadius: 20,
      shadowOffset: {width: 0, height: -4},
      elevation: 16,
    },
    handle: {
      alignSelf: 'center',
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.border,
      marginTop: 10,
      marginBottom: 12,
    },
    handleHit: {
      paddingVertical: 4,
      paddingHorizontal: 40,
      alignSelf: 'center',
    },
    scroll: {
      paddingHorizontal: 20,
      paddingBottom: 8,
    },
    statusBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      gap: 6,
      backgroundColor: colors.isDark ? colors.alpha.orange25 : colors.orange[100],
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 999,
      marginBottom: 10,
    },
    statusDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: colors.primary,
    },
    statusText: {
      color: colors.isDark ? colors.orange[300] : colors.orange[700],
      fontSize: 12,
      fontWeight: '700',
    },
    etaTitle: {
      color: colors.text,
      fontSize: 26,
      fontWeight: '800',
      letterSpacing: -0.4,
    },
    orderMeta: {
      color: colors.muted,
      fontSize: 13,
      fontWeight: '400',
      marginTop: 4,
      marginBottom: 18,
    },
    timeline: {
      marginBottom: 16,
    },
    timelineRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      minHeight: 42,
    },
    timelineTrack: {
      width: 14,
      alignItems: 'center',
    },
    timelineDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      marginTop: 4,
    },
    timelineDotDone: {
      backgroundColor: colors.green[500],
    },
    timelineDotActive: {
      backgroundColor: colors.primary,
    },
    timelineDotPending: {
      backgroundColor: colors.border,
    },
    timelineLine: {
      width: 2,
      flex: 1,
      minHeight: 26,
      backgroundColor: colors.border,
      marginTop: 4,
    },
    timelineCopy: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
      paddingBottom: 12,
    },
    timelineTitle: {
      flex: 1,
      color: colors.text,
      fontSize: 14,
      fontWeight: '600',
    },
    timelineTitlePending: {
      color: colors.muted,
    },
    timelineTime: {
      color: colors.muted,
      fontSize: 13,
      fontWeight: '500',
    },
    timelineTimeActive: {
      color: colors.primary,
      fontWeight: '700',
    },
    timelineTimePending: {
      color: colors.muted,
    },
    codeCard: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      backgroundColor: colors.isDark ? colors.alpha.orange14 : colors.orange[50],
      borderWidth: 1,
      borderColor: colors.isDark ? colors.alpha.orange35 : colors.orange[200],
      borderRadius: 16,
      paddingVertical: 14,
      paddingHorizontal: 14,
      marginBottom: 14,
    },
    codeCopy: {
      flex: 1,
      minWidth: 0,
    },
    codeLabel: {
      color: colors.isDark ? colors.orange[300] : colors.orange[700],
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1,
      marginBottom: 4,
    },
    codeValue: {
      color: colors.text,
      fontSize: 28,
      fontWeight: '800',
      letterSpacing: 6,
    },
    codeHint: {
      color: colors.isDark ? colors.orange[300] : colors.orange[700],
      fontSize: 12,
      fontWeight: '600',
      maxWidth: 110,
      textAlign: 'right',
      lineHeight: 17,
    },
    riderCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
      marginBottom: 8,
    },
    riderTop: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginBottom: 14,
    },
    avatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.isDark ? colors.alpha.orange25 : colors.orange[100],
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarText: {
      color: colors.primary,
      fontSize: 15,
      fontWeight: '800',
    },
    riderCopy: {
      flex: 1,
      minWidth: 0,
    },
    riderName: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '700',
    },
    riderMeta: {
      color: colors.muted,
      fontSize: 12,
      fontWeight: '400',
      marginTop: 2,
    },
    actionRow: {
      flexDirection: 'row',
      gap: 8,
    },
    actionBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      backgroundColor: colors.isDark ? colors.highlight : colors.navy[50],
      borderRadius: 12,
      paddingVertical: 11,
      paddingHorizontal: 6,
    },
    actionText: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '600',
    },
    footer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingTop: 12,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
      backgroundColor: colors.card,
    },
    footerPaid: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
    },
    cancelText: {
      color: colors.red[500],
      fontSize: 14,
      fontWeight: '700',
    },
  });
}
