export const PLATFORMS = ['all', 'instagram', 'tiktok', 'youtube'];

export const PLATFORM_META = {
  all: {name: 'All', tint: 'rgba(255,255,255,0.08)'},
  instagram: {name: 'Instagram', tint: 'rgba(236,72,153,0.22)'},
  tiktok: {name: 'TikTok', tint: 'rgba(34,211,238,0.18)'},
  youtube: {name: 'YouTube', tint: 'rgba(239,68,68,0.2)'},
};

const POSTS = [
  {
    id: 'ig-1',
    platform: 'instagram',
    author: '@fit.with.maya',
    title: 'Day 40 of the gym transformation',
    likes: '18.9K',
    comments: '412',
    views: '1.1M',
    score: 94,
    tier: 'HOT',
    duration: null,
    isTop: true,
    thumb: '#4C1D3D',
  },
  {
    id: 'tt-1',
    platform: 'tiktok',
    author: '@liftedkai',
    title: 'Hook in 1.2s — this audio is still climbing',
    likes: '240K',
    comments: '8.1K',
    views: '6.4M',
    score: 91,
    tier: 'HOT',
    duration: '0:18',
    isTop: true,
    thumb: '#164E63',
  },
  {
    id: 'yt-1',
    platform: 'youtube',
    author: 'Form Lab',
    title: 'I filmed 30 days of gym transformation shorts',
    likes: '92K',
    comments: '3.4K',
    views: '77M',
    score: 88,
    tier: 'RISING',
    duration: '0:41',
    isTop: true,
    thumb: '#7F1D1D',
  },
  {
    id: 'ig-2',
    platform: 'instagram',
    author: '@iron.notes',
    title: 'Split-screen before / after that actually loops',
    likes: '6.2K',
    comments: '188',
    views: '420K',
    score: 82,
    tier: 'RISING',
    duration: null,
    isTop: false,
    thumb: '#3F1D4D',
  },
  {
    id: 'tt-2',
    platform: 'tiktok',
    author: '@coach.ren',
    title: 'Silent-start edit beats the voiceover version',
    likes: '70.6K',
    comments: '2.2K',
    views: '2.1M',
    score: 79,
    tier: 'WARM',
    duration: '0:22',
    isTop: false,
    thumb: '#0F3A4A',
  },
  {
    id: 'yt-2',
    platform: 'youtube',
    author: 'Peak Cut',
    title: 'Long-form recap cut to 22s wins the feed',
    likes: '21K',
    comments: '640',
    views: '4.8M',
    score: 76,
    tier: 'WARM',
    duration: '0:22',
    isTop: false,
    thumb: '#5B1A1A',
  },
  {
    id: 'ig-3',
    platform: 'instagram',
    author: '@reels.lab',
    title: 'Text-on-screen hook drives 3x saves',
    likes: '1.4K',
    comments: '54',
    views: '98K',
    score: 71,
    tier: 'WARM',
    duration: null,
    isTop: false,
    thumb: '#2A1A3A',
  },
  {
    id: 'tt-3',
    platform: 'tiktok',
    author: '@night.set',
    title: 'POV audio trend still climbing overnight',
    likes: '31K',
    comments: '910',
    views: '890K',
    score: 68,
    tier: 'WATCH',
    duration: '0:15',
    isTop: false,
    thumb: '#12343F',
  },
  {
    id: 'yt-3',
    platform: 'youtube',
    author: 'Reps TV',
    title: 'Why this transformation short keeps getting recommended',
    likes: '8.4K',
    comments: '210',
    views: '1.9M',
    score: 64,
    tier: 'WATCH',
    duration: '0:58',
    isTop: false,
    thumb: '#3F1515',
  },
];

export const SEARCH_STATS = {
  all: {
    kicker: 'COMBINED REACH',
    value: '85.9',
    unit: 'M',
    unitLabel: 'views',
    live: true,
    mix: [
      {platform: 'instagram', label: 'Instagram', share: 5.6, count: '12'},
      {platform: 'tiktok', label: 'TikTok', share: 50.5, count: '109'},
      {platform: 'youtube', label: 'YouTube', share: 43.9, count: '96'},
    ],
    metrics: [
      {label: 'TOTAL POSTS', value: '217'},
      {label: 'TOTAL LIKES', value: '4.3M'},
      {label: 'COMMENTS', value: '24.5K'},
    ],
    retrieved: '217 results',
    remaining: 212,
  },
  instagram: {
    kicker: 'PEAK LIKES',
    value: '18.9',
    unit: 'K',
    unitLabel: '',
    live: false,
    hint: 'Highest performing post',
    avgLabel: 'AVG LIKES',
    avgValue: '1.4K',
    avgHint: 'Typical engagement',
    retrieved: 'Instagram posts retrieved',
    remaining: 30,
  },
  tiktok: {
    kicker: 'PEAK LIKES',
    value: '240',
    unit: 'K',
    unitLabel: '',
    live: false,
    hint: 'Highest performing TikTok',
    avgLabel: 'AVG LIKES',
    avgValue: '70.6K',
    avgHint: 'Typical engagement',
    retrieved: 'TikTok videos fetched',
    remaining: 74,
  },
  youtube: {
    kicker: 'PEAK VIEWS',
    value: '77',
    unit: 'M',
    unitLabel: '',
    live: false,
    hint: 'Highest view count',
    avgLabel: 'AVG VIEWS',
    avgValue: '4.8M',
    avgHint: 'Typical result',
    retrieved: 'YouTube videos fetched',
    remaining: 66,
  },
};

export function mockKeywordSearch({keyword, platform = 'all'}) {
  const q = String(keyword || '').trim().toLowerCase();
  let rows = POSTS.filter(item =>
    !q
      ? true
      : `${item.title} ${item.author} ${item.platform}`.toLowerCase().includes(q) ||
        'gym transformation'.includes(q) ||
        q.split(' ').some(part => item.title.toLowerCase().includes(part)),
  );
  if (platform && platform !== 'all') {
    rows = rows.filter(item => item.platform === platform);
  }
  return {
    keyword: keyword || 'gym transformation',
    platform,
    stats: SEARCH_STATS[platform] || SEARCH_STATS.all,
    posts: rows.length ? rows : POSTS.filter(item => platform === 'all' || item.platform === platform),
  };
}
