import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingBottom: 12,
      backgroundColor: colors.card,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      color: colors.text,
      fontSize: 18,
      fontWeight: '700',
    },
    scroll: {
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    alertBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.isDark ? colors.red.darkBg : colors.red.soft,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.isDark ? colors.red[900] : colors.red[250],
      paddingHorizontal: 12,
      paddingVertical: 12,
      marginBottom: 16,
    },
    alertLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      marginRight: 10,
    },
    alertIcon: {
      marginRight: 10,
    },
    alertTextCol: {
      flex: 1,
    },
    alertTitle: {
      color: colors.isDark ? colors.red[350] : colors.red.primary,
      fontSize: 13.5,
      fontWeight: '700',
      marginBottom: 2,
    },
    alertSub: {
      color: colors.isDark ? colors.red.lightText : colors.red.primary,
      fontSize: 11.5,
      fontWeight: '400',
      lineHeight: 15,
    },
    callBtn: {
      backgroundColor: colors.red.primary,
      borderRadius: 12,
      paddingVertical: 8,
      paddingHorizontal: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    callBtnText: {
      color: colors.white,
      fontSize: 12.5,
      fontWeight: '700',
    },
    sectionLabel: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.8,
      marginBottom: 8,
    },
    rideCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
      marginBottom: 16,
    },
    rideTop: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    rideIcon: {
      marginRight: 12,
    },
    rideInfo: {
      flex: 1,
    },
    rideTitle: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 3,
    },
    rideSub: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '400',
    },
    changeRideLink: {
      color: colors.primary,
      fontSize: 13,
      fontWeight: '700',
      marginTop: 8,
    },
    categoriesGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: 10,
      marginBottom: 16,
    },
    categoryCard: {
      width: '48.5%',
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.card,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 12,
      paddingHorizontal: 12,
      minHeight: 48,
    },
    categoryCardSelected: {
      borderColor: colors.primary,
      borderWidth: 1.5,
      backgroundColor: colors.isDark ? colors.alpha.orange22 : colors.orange.subtleBg,
    },
    categoryIcon: {
      marginRight: 8,
    },
    categoryText: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '500',
      flex: 1,
      lineHeight: 16,
    },
    categoryTextSelected: {
      fontWeight: '700',
      color: colors.text,
    },
    textAreaCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
      marginBottom: 12,
      minHeight: 100,
      justifyContent: 'space-between',
    },
    textInput: {
      color: colors.text,
      fontSize: 12.5,
      lineHeight: 18,
      padding: 0,
      margin: 0,
      textAlignVertical: 'top',
    },
    charCount: {
      alignSelf: 'flex-end',
      color: colors.textMuted,
      fontSize: 11,
      marginTop: 8,
    },
    photoBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderWidth: 1.5,
      borderStyle: 'dashed',
      borderColor: colors.border,
      borderRadius: 16,
      backgroundColor: colors.card,
      height: 48,
      marginBottom: 12,
    },
    photoBtnText: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '600',
    },
    anonymousCard: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
      marginBottom: 20,
    },
    anonymousInfo: {
      flex: 1,
      marginRight: 10,
    },
    anonymousTitle: {
      color: colors.text,
      fontSize: 13.5,
      fontWeight: '700',
      marginBottom: 2,
    },
    anonymousSub: {
      color: colors.textMuted,
      fontSize: 11.5,
      fontWeight: '400',
    },
    toggleTrack: {
      width: 44,
      height: 24,
      borderRadius: 12,
      padding: 2,
      justifyContent: 'center',
    },
    toggleTrackActive: {
      backgroundColor: colors.primary,
    },
    toggleTrackInactive: {
      backgroundColor: colors.isDark ? colors.navy.borderMuted : colors.navy.borderSoft,
    },
    toggleThumb: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: colors.white,
      shadowColor: colors.black,
      shadowOffset: {width: 0, height: 1},
      shadowOpacity: 0.2,
      shadowRadius: 1.5,
      elevation: 2,
    },
    toggleThumbActive: {
      alignSelf: 'flex-end',
    },
    toggleThumbInactive: {
      alignSelf: 'flex-start',
    },
  });
}
