import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: '#F3F6FA',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingBottom: 12,
      backgroundColor: '#FFFFFF',
    },
    headerBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      color: '#0F2840',
      fontSize: 18,
      fontWeight: '700',
    },
    scroll: {
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    alertBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: '#FFF1F1',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#FECACA',
      paddingHorizontal: 12,
      paddingVertical: 12,
      marginBottom: 16,
    },
    alertLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      marginRight: 10,
    },
    alertIcon: {
      marginRight: 10,
    },
    alertTextCol: {
      flex: 1,
    },
    alertTitle: {
      color: '#E53935',
      fontSize: 13.5,
      fontWeight: '700',
      marginBottom: 2,
    },
    alertSub: {
      color: '#E53935',
      fontSize: 11.5,
      fontWeight: '400',
      lineHeight: 15,
    },
    callBtn: {
      backgroundColor: '#E53935',
      borderRadius: 12,
      paddingVertical: 8,
      paddingHorizontal: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    callBtnText: {
      color: '#FFFFFF',
      fontSize: 12.5,
      fontWeight: '700',
    },
    sectionLabel: {
      color: '#7E8B9E',
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.8,
      marginBottom: 8,
    },
    rideCard: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#E8ECF2',
      padding: 14,
      marginBottom: 16,
    },
    rideTop: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    rideIcon: {
      marginRight: 12,
    },
    rideInfo: {
      flex: 1,
    },
    rideTitle: {
      color: '#0F2840',
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 3,
    },
    rideSub: {
      color: '#6E7C91',
      fontSize: 12,
      fontWeight: '400',
    },
    changeRideLink: {
      color: '#FF7006',
      fontSize: 13,
      fontWeight: '700',
      marginTop: 8,
    },
    categoriesGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: 10,
      marginBottom: 16,
    },
    categoryCard: {
      width: '48.5%',
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      borderRadius: 14,
      borderWidth: 1,
      borderColor: '#E8ECF2',
      paddingVertical: 12,
      paddingHorizontal: 12,
      minHeight: 48,
    },
    categoryCardSelected: {
      borderColor: '#FF7006',
      borderWidth: 1.5,
      backgroundColor: '#FFF5ED',
    },
    categoryIcon: {
      marginRight: 8,
    },
    categoryText: {
      color: '#0F2840',
      fontSize: 12,
      fontWeight: '500',
      flex: 1,
      lineHeight: 16,
    },
    categoryTextSelected: {
      fontWeight: '700',
      color: '#0F2840',
    },
    textAreaCard: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#E8ECF2',
      padding: 14,
      marginBottom: 12,
      minHeight: 100,
      justifyContent: 'space-between',
    },
    textInput: {
      color: '#0F2840',
      fontSize: 12.5,
      lineHeight: 18,
      padding: 0,
      margin: 0,
      textAlignVertical: 'top',
    },
    charCount: {
      alignSelf: 'flex-end',
      color: '#8A96A6',
      fontSize: 11,
      marginTop: 8,
    },
    photoBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderWidth: 1.5,
      borderStyle: 'dashed',
      borderColor: '#D3DAE4',
      borderRadius: 16,
      backgroundColor: '#FFFFFF',
      height: 48,
      marginBottom: 12,
    },
    photoBtnText: {
      color: '#6E7C91',
      fontSize: 13,
      fontWeight: '600',
    },
    anonymousCard: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#E8ECF2',
      padding: 14,
      marginBottom: 20,
    },
    anonymousInfo: {
      flex: 1,
      marginRight: 10,
    },
    anonymousTitle: {
      color: '#0F2840',
      fontSize: 13.5,
      fontWeight: '700',
      marginBottom: 2,
    },
    anonymousSub: {
      color: '#6E7C91',
      fontSize: 11.5,
      fontWeight: '400',
    },
    toggleTrack: {
      width: 44,
      height: 24,
      borderRadius: 12,
      padding: 2,
      justifyContent: 'center',
    },
    toggleTrackActive: {
      backgroundColor: '#FF7006',
    },
    toggleTrackInactive: {
      backgroundColor: '#B5BFC9',
    },
    toggleThumb: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: '#FFFFFF',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 1},
      shadowOpacity: 0.2,
      shadowRadius: 1.5,
      elevation: 2,
    },
    toggleThumbActive: {
      alignSelf: 'flex-end',
    },
    toggleThumbInactive: {
      alignSelf: 'flex-start',
    },
  });
}
