import { StyleSheet } from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.map.land,
    },
    mapMarkers: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 2,
    },
    locationMarker: {
      position: 'absolute',
      top: 200,
      left: '50%',
      width: 108,
      height: 108,
      marginLeft: -54,
      alignItems: 'center',
      justifyContent: 'center',
    },
    locationHalo: {
      position: 'absolute',
      width: 70,
      height: 70,
      borderRadius: 54,
      backgroundColor: colors.alpha.blue20,
    },
    locationCore: {
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: colors.blue[500],
      borderWidth: 4,
      borderColor: colors.white,
      shadowColor: colors.navy[900],
      shadowOpacity: 0.25,
      shadowRadius: 5,
      shadowOffset: { width: 0, height: 2 },
      elevation: 6,
    },
    header: {
      position: 'absolute',
      left: 16,
      right: 16,
      zIndex: 5,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      overflow: 'visible',
    },
    menuBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.isDark ? colors.navy[700] : colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.navy[900],
      shadowOpacity: 0.1,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 3,
    },
    greetingPill: {
      flex: 1,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.isDark ? colors.navy[700] : colors.border,
      borderRadius: 999,
      paddingVertical: 8,
      paddingHorizontal: 14,
      shadowColor: colors.navy[900],
      shadowOpacity: 0.08,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    greetingKicker: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.textMuted,
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 1,
    },
    greetingName: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 14,
      fontWeight: '800',
      marginTop: 1,
    },
    headerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      overflow: 'visible',
    },
    iconCircle: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.isDark ? colors.navy[850] : colors.navy[900],
      borderWidth: 1,
      borderColor: colors.isDark ? colors.navy[700] : colors.transparent,
      alignItems: 'center',
      justifyContent: 'center',
    },
    bellWrap: {
      width: 44,
      height: 44,
      position: 'relative',
      overflow: 'visible',
    },
    badge: {
      position: 'absolute',
      top: -4,
      right: -4,
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: colors.red[500],
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: colors.white,
      zIndex: 3,
    },
    badgeText: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.white,
      fontSize: 11,
      fontWeight: '800',
      lineHeight: 12,
      includeFontPadding: false,
      textAlign: 'center',
    },
    avatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.isDark ? colors.navy[850] : colors.navy[800],
      borderWidth: 1,
      borderColor: colors.isDark ? colors.navy[700] : colors.transparent,
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarText: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.white,
      fontSize: 13,
      fontWeight: '800',
    },
    statusChip: {
      position: 'absolute',
      left: 16,
      zIndex: 5,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderRadius: 999,
      paddingVertical: 10,
      paddingHorizontal: 14,
      shadowColor: colors.navy[900],
      shadowOpacity: 0.12,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 3 },
      elevation: 4,
    },
    statusChipDark: {
      backgroundColor: colors.navy[900],
    },
    statusChipWarn: {
      backgroundColor: colors.amber[100],
    },
    statusDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    statusChipText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.white,
      fontSize: 12,
      fontWeight: '700',
      flexShrink: 1,
    },
    statusChipTextWarn: {
      color: colors.amber[750],
    },
    demandChip: {
      position: 'absolute',
      left: 16,
      zIndex: 5,
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      gap: 8,
      backgroundColor: colors.orange[500],
      borderRadius: 999,
      paddingVertical: 10,
      paddingHorizontal: 14,
      shadowColor: colors.orange[700],
      shadowOpacity: 0.28,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 3 },
      elevation: 4,
    },
    demandText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.white,
      fontSize: 12,
      fontWeight: '700',
    },
    locateFab: {
      position: 'absolute',
      right: 16,
      zIndex: 6,
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.isDark ? colors.navy[700] : colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.navy[900],
      shadowOpacity: 0.16,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 8,
    },
    sheetWrap: {
      position: 'absolute',
      left: 0,
      right: 0,
      zIndex: 4,
    },
    sheet: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingTop: 10,
      paddingHorizontal: 16,
      paddingBottom: 8,
      maxHeight: '100%',
      borderWidth: colors.isDark ? 1 : 0,
      borderColor: colors.isDark ? colors.navy[700] : colors.border,
      borderBottomWidth: 0,
      overflow: 'hidden',
      shadowColor: colors.navy[900],
      shadowOpacity: 0.08,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: -4 },
      elevation: 8,
    },
    grabber: {
      alignSelf: 'center',
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.isDark ? colors.navy[700] : colors.gray[200],
      marginBottom: 12,
    },
    sheetScroll: {
      paddingBottom: 16,
    },
    onlineCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: colors.isDark ? colors.alpha.green18 : colors.green[100],
      borderRadius: 24,
      borderWidth: 1.5,
      borderColor: colors.isDark ? colors.green[600] : colors.green[500],
      paddingVertical: 16,
      paddingHorizontal: 14,
      marginBottom: 12,
    },
    awayCard: {
      backgroundColor: colors.isDark ? colors.navy[850] : colors.navy[50],
      borderColor: colors.isDark ? colors.navy[700] : colors.navy[200],
    },
    offlineCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: colors.isDark ? colors.alpha.red18 : colors.red[100],
      borderRadius: 22,
      borderWidth: 1.5,
      borderColor: colors.red[500],
      paddingVertical: 14,
      paddingHorizontal: 14,
      marginBottom: 12,
    },
    statusIcon: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: colors.green[500],
      alignItems: 'center',
      justifyContent: 'center',
    },
    statusIconAway: {
      backgroundColor: colors.navy[200],
    },
    statusIconWarn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.red[200],
      alignItems: 'center',
      justifyContent: 'center',
    },
    statusCopy: {
      flex: 1,
      minWidth: 0,
    },
    onlineTitle: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.isDark ? colors.green[400] : colors.green[600],
      fontSize: 16,
      fontWeight: '800',
    },
    onlineSub: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.isDark ? colors.green[300] : colors.green[600],
      fontSize: 12,
      fontWeight: '500',
      lineHeight: 17,
      marginTop: 2,
    },
    awayTitle: {
      color: colors.text,
    },
    awaySub: {
      color: colors.textMuted,
    },
    offlineTitle: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.isDark ? colors.red[400] : colors.red[600],
      fontSize: 16,
      fontWeight: '800',
    },
    offlineSub: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.isDark ? colors.red[300] : colors.red[500],
      fontSize: 12,
      fontWeight: '500',
      lineHeight: 17,
      marginTop: 2,
    },
    statsRow: {
      flexDirection: 'row',
      alignItems: 'stretch',
      gap: 8,
      marginBottom: 12,
    },
    stat: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      backgroundColor: colors.surface,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: colors.isDark ? colors.navy[700] : colors.border,
      paddingVertical: 12,
      paddingHorizontal: 4,
    },
    statValue: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 14,
      fontWeight: '800',
    },
    statValueMuted: {
      color: colors.textMuted,
    },
    statLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.textMuted,
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 0.6,
    },
    streakCard: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      borderWidth: 1.5,
      borderColor: colors.isDark ? colors.navy[700] : colors.border,
      padding: 14,
    },
    streakTop: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 12,
    },
    streakTitle: {
      fontFamily: colors.fonts.sora.extraBold,
      flex: 1,
      color: colors.text,
      fontSize: 14,
      fontWeight: '800',
    },
    progressPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.isDark ? colors.alpha.orange18 : colors.orange[100],
      borderRadius: 999,
      paddingVertical: 5,
      paddingHorizontal: 10,
    },
    progressDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: colors.orange[600],
    },
    progressPillText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.isDark ? colors.orange[400] : colors.orange[600],
      fontSize: 11,
      fontWeight: '700',
    },
    streakMeta: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 10,
    },
    streakCount: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 20,
      fontWeight: '800',
    },
    streakReward: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.orange[600],
      fontSize: 20,
      fontWeight: '800',
    },
    segmentTrack: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginBottom: 10,
    },
    segment: {
      flex: 1,
      height: 10,
      borderRadius: 0,
    },
    segmentStart: {
      borderTopLeftRadius: 999,
      borderBottomLeftRadius: 999,
    },
    segmentEnd: {
      borderTopRightRadius: 999,
      borderBottomRightRadius: 999,
    },
    segmentOn: {
      backgroundColor: colors.orange[600],
    },
    segmentOff: {
      backgroundColor: colors.isDark ? colors.navy[800] : colors.gray[200],
    },
    streakHint: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '500',
      lineHeight: 17,
    },
    requireCard: {
      backgroundColor: colors.red[100],
      borderRadius: 20,
      borderWidth: 1.5,
      borderColor: colors.red[500],
      padding: 14,
    },
    requireHead: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 12,
    },
    requireTitle: {
      fontFamily: colors.fonts.sora.extraBold,
      flex: 1,
      color: colors.red[600],
      fontSize: 14,
      fontWeight: '800',
      lineHeight: 19,
    },
    requireRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
      marginBottom: 10,
    },
    requireDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: colors.red[500],
      marginTop: 6,
    },
    requireDotReview: {
      backgroundColor: colors.amber[600],
    },
    requireText: {
      fontFamily: colors.fonts.sora.semiBold,
      flex: 1,
      color: colors.red[600],
      fontSize: 13,
      fontWeight: '600',
      lineHeight: 18,
    },
    requireLink: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.red[600],
      fontSize: 13,
      fontWeight: '800',
    },
    requireMuted: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.red[600],
      fontSize: 13,
      fontWeight: '700',
    },
    requireReview: {
      color: colors.amber[600],
    },
    fixBtn: {
      marginTop: 6,
      borderRadius: 16,
      backgroundColor: colors.red[500],
      minHeight: 48,
    },
  });
}
