import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.navy[25],
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingBottom: 12,
      backgroundColor: colors.white,
    },
    headerBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      color: colors.navy[900],
      fontSize: 17,
      fontWeight: '700',
    },
    scroll: {
      paddingHorizontal: 20,
      paddingTop: 18,
      paddingBottom: 16,
    },
    title: {
      color: colors.navy[900],
      fontSize: 20,
      fontWeight: '800',
      marginBottom: 6,
    },
    hint: {
      color: colors.gray[500],
      fontSize: 14,
      lineHeight: 20,
      marginBottom: 16,
    },
    preview: {
      backgroundColor: colors.navy[900],
      borderRadius: 22,
      minHeight: 190,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 18,
      marginBottom: 14,
      overflow: 'hidden',
    },
    previewFilled: {
      backgroundColor: 'transparent',
      padding: 0,
    },
    previewImage: {
      width: '100%',
      height: 190,
      borderRadius: 22,
      backgroundColor: colors.white,
    },
    paper: {
      width: '100%',
      height: 118,
      borderRadius: 8,
      backgroundColor: colors.white,
      padding: 16,
      justifyContent: 'space-evenly',
    },
    line: {
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.navy[100],
    },
    corner: {
      position: 'absolute',
      width: 22,
      height: 22,
      borderColor: colors.primary,
    },
    cornerTL: {
      top: 16,
      left: 16,
      borderTopWidth: 3,
      borderLeftWidth: 3,
      borderTopLeftRadius: 4,
    },
    cornerTR: {
      top: 16,
      right: 16,
      borderTopWidth: 3,
      borderRightWidth: 3,
      borderTopRightRadius: 4,
    },
    cornerBL: {
      bottom: 44,
      left: 16,
      borderBottomWidth: 3,
      borderLeftWidth: 3,
      borderBottomLeftRadius: 4,
    },
    cornerBR: {
      bottom: 44,
      right: 16,
      borderBottomWidth: 3,
      borderRightWidth: 3,
      borderBottomRightRadius: 4,
    },
    edges: {
      marginTop: 14,
      backgroundColor: colors.green[600],
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 999,
    },
    edgesText: {
      color: colors.white,
      fontSize: 12,
      fontWeight: '700',
    },
    sourceRow: {
      flexDirection: 'row',
      backgroundColor: colors.white,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: colors.gray[200],
      marginBottom: 12,
      overflow: 'hidden',
    },
    sourceBtn: {
      flex: 1,
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    sourceOn: {
      backgroundColor: colors.orange[50],
      borderWidth: 1.5,
      borderColor: colors.primary,
      borderRadius: 14,
      margin: 4,
    },
    sourceLabel: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.navy[800],
    },
    sourceLabelOn: {
      color: colors.primary,
    },
    fileCard: {
      backgroundColor: colors.white,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: colors.gray[200],
      padding: 14,
      marginBottom: 12,
    },
    fileRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    fileIcon: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: colors.orange[100],
      alignItems: 'center',
      justifyContent: 'center',
    },
    fileCopy: {
      flex: 1,
    },
    fileName: {
      color: colors.navy[900],
      fontSize: 14,
      fontWeight: '700',
    },
    fileMeta: {
      color: colors.gray[500],
      fontSize: 12,
      marginTop: 2,
    },
    filePct: {
      color: colors.primary,
      fontSize: 13,
      fontWeight: '800',
      marginTop: 4,
      textAlign: 'right',
    },
    track: {
      height: 8,
      borderRadius: 999,
      backgroundColor: colors.navy[100],
      overflow: 'hidden',
      marginTop: 10,
    },
    fill: {
      height: '100%',
      borderRadius: 999,
      backgroundColor: colors.primary,
    },
    checklist: {
      backgroundColor: colors.white,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: colors.gray[200],
      padding: 14,
    },
    checkLabel: {
      color: colors.gray[500],
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 0.7,
      marginBottom: 10,
    },
    checkRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 8,
    },
    checkText: {
      flex: 1,
      color: colors.navy[800],
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '600',
    },
    footer: {
      flexDirection: 'row',
      gap: 12,
      paddingHorizontal: 20,
      paddingTop: 10,
      backgroundColor: colors.white,
      borderTopWidth: 1,
      borderTopColor: colors.gray[100],
    },
    footerBtn: {
      flex: 1,
      borderRadius: 16,
    },
    retake: {
      backgroundColor: colors.white,
      borderWidth: 1.5,
      borderColor: colors.navy[800],
    },
  });
}
