import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 12,
      paddingBottom: 10,
      backgroundColor: colors.card,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      color: colors.text,
      fontSize: 17,
      fontWeight: '700',
    },
    scroll: {
      paddingHorizontal: 20,
      paddingTop: 12,
    },
    tripToggle: {
      flexDirection: 'row',
      backgroundColor: colors.isDark ? colors.surface : colors.gray[100],
      borderRadius: 14,
      padding: 4,
      marginBottom: 22,
      borderWidth: colors.isDark ? 1 : 0,
      borderColor: colors.border,
    },
    tripTab: {
      flex: 1,
      paddingVertical: 11,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tripTabActive: {
      backgroundColor: colors.isDark ? colors.cardHighlight : colors.white,
      shadowColor: colors.isDark ? '#000000' : colors.navy[900],
      shadowOpacity: 0.06,
      shadowRadius: 6,
      shadowOffset: {width: 0, height: 1},
      elevation: 2,
    },
    tripTabText: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '600',
    },
    tripTabTextActive: {
      color: colors.text,
      fontWeight: '700',
    },
    section: {
      marginBottom: 20,
    },
    sectionLabel: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1.1,
      marginBottom: 10,
    },
    card: {
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
    },
    airportRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingBottom: 14,
    },
    pinIcon: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.isDark ? 'rgba(255, 112, 6, 0.2)' : colors.orange[100],
      alignItems: 'center',
      justifyContent: 'center',
    },
    airportCopy: {
      flex: 1,
      minWidth: 0,
    },
    airportName: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
    },
    airportMeta: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '400',
      marginTop: 2,
    },
    divider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.border,
      marginBottom: 12,
    },
    terminalRow: {
      flexDirection: 'row',
      gap: 10,
    },
    terminalChip: {
      flex: 1,
      paddingVertical: 11,
      paddingHorizontal: 10,
      borderRadius: 12,
      backgroundColor: colors.isDark ? colors.surface : colors.gray[100],
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: colors.isDark ? colors.border : 'transparent',
    },
    terminalChipActive: {
      backgroundColor: colors.isDark ? 'rgba(255, 112, 6, 0.2)' : colors.white,
      borderColor: colors.primary,
    },
    terminalText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '600',
    },
    terminalTextActive: {
      color: colors.primary,
      fontWeight: '700',
    },
    detailRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
    },
    detailIcon: {
      marginTop: 2,
    },
    detailCopy: {
      flex: 1,
      minWidth: 0,
    },
    detailTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
    },
    detailMeta: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '400',
      marginTop: 3,
      lineHeight: 18,
    },
    detailNote: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '400',
      marginTop: 12,
      lineHeight: 17,
    },
    pickupCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
    },
    pickupCopy: {
      flex: 1,
      minWidth: 0,
    },
    editBtn: {
      paddingVertical: 6,
      paddingHorizontal: 4,
    },
    editText: {
      color: colors.primary,
      fontSize: 14,
      fontWeight: '700',
    },
    surchargeCard: {
      backgroundColor: colors.isDark ? '#1C2534' : colors.orange[50],
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.isDark ? colors.border : 'transparent',
      padding: 14,
    },
    surchargeHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 12,
    },
    surchargeTitle: {
      color: colors.primary,
      fontSize: 14,
      fontWeight: '700',
    },
    surchargeRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 12,
      marginBottom: 8,
    },
    surchargeLabel: {
      flex: 1,
      color: colors.text,
      fontSize: 13,
      fontWeight: '400',
      lineHeight: 18,
    },
    surchargeValue: {
      color: colors.primary,
      fontSize: 13,
      fontWeight: '700',
    },
    surchargeFooter: {
      color: colors.primary,
      fontSize: 12,
      fontWeight: '500',
      marginTop: 4,
    },
    footer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      paddingHorizontal: 20,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      backgroundColor: colors.card,
    },
    fareCopy: {
      flex: 1,
      minWidth: 0,
    },
    fareLabel: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '500',
    },
    fareValue: {
      color: colors.text,
      fontSize: 26,
      fontWeight: '800',
      marginTop: 2,
      letterSpacing: -0.4,
    },
    fareNote: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '400',
      marginTop: 2,
    },
    bookBtn: {
      backgroundColor: colors.primary,
      paddingVertical: 14,
      paddingHorizontal: 36,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    bookText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '700',
    },
  });
}
