import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scroll: {
      paddingHorizontal: 20,
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 16,
    },
    iconBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.card,
      borderWidth: colors.isDark ? 1 : 0,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    iconBtnOutline: {
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
    },
    title: {
      fontFamily: colors.fonts.sora.extraBold,
      flex: 1,
      textAlign: 'left',
      color: colors.text,
      fontSize: 26,
      letterSpacing: -0.4,
    },
    balanceCard: {
      backgroundColor: colors.navy[925],
      borderRadius: 28,
      paddingTop: 20,
      paddingHorizontal: 20,
      paddingBottom: 18,
      marginBottom: 16,
      overflow: 'hidden',
    },
    balanceDecor: {
      position: 'absolute',
      top: 10,
      right: -55,
      width: 160,
      height: 160,
      borderRadius: 80,
      backgroundColor: colors.alpha.orangeBrand22,
    },
    balanceTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 14,
      zIndex: 1,
    },
    balanceLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.blue.slate,
      fontSize: 11,
      letterSpacing: 1.2,
    },
    balanceLoader: {
      paddingVertical: 10,
      alignItems: 'flex-start',
      marginBottom: 6,
      zIndex: 1,
    },
    balanceValue: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.white,
      fontSize: 36,
      letterSpacing: -0.8,
      marginBottom: 6,
      zIndex: 1,
    },
    balanceMeta: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.blue.slate,
      fontSize: 13,
      marginBottom: 20,
      zIndex: 1,
    },
    balanceActions: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
      gap: 8,
      zIndex: 1,
    },
    addMoneyBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 5,
      backgroundColor: colors.orange[500],
      borderRadius: 999,
      paddingVertical: 10,
      paddingHorizontal: 14,
    },
    addMoneyText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.white,
      fontSize: 13,
    },
    historyBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 5,
      backgroundColor: colors.alpha.white06,
      borderRadius: 999,
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderWidth: 1,
      borderColor: colors.alpha.white22,
    },
    historyText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.white,
      fontSize: 13,
    },
    tabs: {
      flexDirection: 'row',
      backgroundColor: colors.isDark ? colors.surface : colors.gray[100],
      borderRadius: 14,
      padding: 4,
      marginBottom: 14,
      height: 46,
      alignItems: 'center',
    },
    tab: {
      flex: 1,
      height: 38,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tabActive: {
      backgroundColor: colors.card,
      shadowColor: colors.isDark ? colors.black : colors.navy[900],
      shadowOpacity: 0.08,
      shadowRadius: 6,
      shadowOffset: {width: 0, height: 1},
      elevation: 2,
    },
    tabText: {
      fontFamily: colors.fonts.sora.semiBold,
      color: colors.textMuted,
      fontSize: 13,
    },
    tabTextActive: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
    },
    txnList: {
      gap: 10,
    },
    txnCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 14,
      paddingHorizontal: 12,
    },
    txnIcon: {
      width: 42,
      height: 42,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    txnCopy: {
      flex: 1,
      minWidth: 0,
    },
    txnTitle: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 14,
      marginBottom: 3,
    },
    txnMeta: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.textMuted,
      fontSize: 12,
    },
    txnRight: {
      alignItems: 'flex-end',
    },
    txnAmount: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 14,
      marginBottom: 3,
    },
    txnAmountCredit: {
      color: colors.green[500],
    },
    txnStatus: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.textSub,
      fontSize: 11,
    },
  });
}
