import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.white,
    },
    scroll: {
      paddingHorizontal: 20,
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 16,
    },
    iconBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.gray[100],
      alignItems: 'center',
      justifyContent: 'center',
    },
    iconBtnOutline: {
      backgroundColor: colors.white,
      borderWidth: 1,
      borderColor: colors.gray[200],
    },
    title: {
      flex: 1,
      textAlign: 'left',
      color: colors.navy[900],
      fontSize: 26,
      fontWeight: '800',
      letterSpacing: -0.4,
    },
    balanceCard: {
      backgroundColor: '#0B2135',
      borderRadius: 28,
      paddingTop: 20,
      paddingHorizontal: 20,
      paddingBottom: 18,
      marginBottom: 16,
      overflow: 'hidden',
    },
    balanceDecor: {
      position: 'absolute',
      top: 10,
      right: -55,
      width: 160,
      height: 160,
      borderRadius: 80,
      backgroundColor: 'rgba(255, 140, 60, 0.22)',
    },
    balanceTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 14,
      zIndex: 1,
    },
    balanceLabel: {
      color: '#9AA8B8',
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1.2,
    },
    balanceValue: {
      color: colors.white,
      fontSize: 36,
      fontWeight: '800',
      letterSpacing: -0.8,
      marginBottom: 6,
      zIndex: 1,
    },
    balanceMeta: {
      color: '#9AA8B8',
      fontSize: 13,
      fontWeight: '500',
      marginBottom: 20,
      zIndex: 1,
    },
    balanceActions: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
      gap: 8,
      zIndex: 1,
    },
    addMoneyBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 5,
      backgroundColor: colors.orange[500],
      borderRadius: 999,
      paddingVertical: 10,
      paddingHorizontal: 14,
    },
    addMoneyText: {
      color: colors.white,
      fontSize: 13,
      fontWeight: '700',
    },
    historyBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 5,
      backgroundColor: 'rgba(255,255,255,0.06)',
      borderRadius: 999,
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.22)',
    },
    historyText: {
      color: colors.white,
      fontSize: 13,
      fontWeight: '700',
    },
    tabs: {
      flexDirection: 'row',
      backgroundColor: colors.gray[100],
      borderRadius: 14,
      padding: 4,
      marginBottom: 14,
      height: 46,
      alignItems: 'center',
    },
    tab: {
      flex: 1,
      height: 38,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tabActive: {
      backgroundColor: colors.white,
      shadowColor: colors.navy[900],
      shadowOpacity: 0.08,
      shadowRadius: 6,
      shadowOffset: {width: 0, height: 1},
      elevation: 2,
    },
    tabText: {
      color: colors.gray[500],
      fontSize: 13,
      fontWeight: '600',
    },
    tabTextActive: {
      color: colors.navy[900],
      fontWeight: '700',
    },
    txnList: {
      gap: 10,
    },
    txnCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: colors.white,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.gray[200],
      paddingVertical: 14,
      paddingHorizontal: 12,
    },
    txnIcon: {
      width: 42,
      height: 42,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    txnCopy: {
      flex: 1,
      minWidth: 0,
    },
    txnTitle: {
      color: colors.navy[900],
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 3,
    },
    txnMeta: {
      color: colors.gray[500],
      fontSize: 12,
      fontWeight: '500',
    },
    txnRight: {
      alignItems: 'flex-end',
    },
    txnAmount: {
      color: colors.navy[900],
      fontSize: 14,
      fontWeight: '800',
      marginBottom: 3,
    },
    txnAmountCredit: {
      color: colors.green[600],
    },
    txnStatus: {
      color: colors.gray[500],
      fontSize: 11,
      fontWeight: '500',
    },
  });
}
