import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      width: '100%',
      height: '100%',
      justifyContent: 'flex-end',
      backgroundColor: 'rgba(0, 0, 0, 0.55)',
    },
    backdrop: {
      ...StyleSheet.absoluteFillObject,
    },
    sheet: {
      width: '100%',
      backgroundColor: colors.white,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingHorizontal: 18,
      paddingTop: 6,
      overflow: 'hidden',
      zIndex: 2,
      elevation: 24,
      shadowColor: colors.navy[900],
      shadowOpacity: 0.16,
      shadowRadius: 20,
      shadowOffset: {width: 0, height: -4},
    },
    grabberHit: {
      alignItems: 'center',
      paddingTop: 2,
      paddingBottom: 6,
    },
    grabber: {
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.gray[300],
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    title: {
      color: colors.navy[900],
      fontSize: 20,
      fontWeight: '800',
      letterSpacing: -0.3,
    },
    resetText: {
      color: colors.orange[600],
      fontSize: 14,
      fontWeight: '700',
    },
    scroll: {
      flexGrow: 0,
      flexShrink: 1,
    },
    scrollContent: {
      paddingBottom: 4,
    },
    sectionLabel: {
      color: colors.gray[400],
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1.1,
      marginBottom: 8,
    },
    sectionLabelFare: {
      color: colors.gray[400],
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1.1,
    },
    sortList: {
      gap: 0,
    },
    sortRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 9,
    },
    sortLabel: {
      color: colors.navy[800],
      fontSize: 15,
      fontWeight: '500',
    },
    sortLabelActive: {
      color: colors.navy[900],
      fontWeight: '700',
    },
    radioOuter: {
      width: 22,
      height: 22,
      borderRadius: 11,
      borderWidth: 2,
      borderColor: colors.gray[300],
      alignItems: 'center',
      justifyContent: 'center',
    },
    radioOuterActive: {
      borderColor: colors.orange[500],
    },
    radioInner: {
      width: 11,
      height: 11,
      borderRadius: 6,
      backgroundColor: colors.orange[500],
    },
    divider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.gray[200],
      marginVertical: 12,
    },
    chipsWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    serviceRow: {
      flexDirection: 'row',
      gap: 6,
    },
    serviceRowSpaced: {
      marginTop: 8,
    },
    serviceChip: {
      flex: 1,
      paddingVertical: 8,
      paddingHorizontal: 2,
      borderRadius: 999,
      borderWidth: 1.5,
      borderColor: colors.gray[200],
      backgroundColor: colors.white,
      alignItems: 'center',
      justifyContent: 'center',
    },
    serviceChipSpacer: {
      flex: 1,
    },
    chip: {
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: 999,
      borderWidth: 1.5,
      borderColor: colors.gray[200],
      backgroundColor: colors.white,
    },
    chipActive: {
      borderColor: colors.orange[500],
      backgroundColor: colors.white,
    },
    chipText: {
      color: colors.navy[800],
      fontSize: 12,
      fontWeight: '600',
    },
    chipTextActive: {
      color: colors.orange[600],
      fontWeight: '700',
    },
    fareHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 10,
    },
    fareValue: {
      color: colors.navy[900],
      fontSize: 14,
      fontWeight: '800',
    },
    sliderBlock: {
      marginBottom: 4,
    },
    sliderTrackHit: {
      height: 28,
      justifyContent: 'center',
      position: 'relative',
    },
    sliderTrack: {
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.orange[100],
      width: '100%',
    },
    sliderFill: {
      position: 'absolute',
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.orange[500],
      top: 11,
    },
    sliderThumb: {
      position: 'absolute',
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: colors.white,
      borderWidth: 3,
      top: 3,
      shadowColor: colors.navy[900],
      shadowOpacity: 0.12,
      shadowRadius: 3,
      shadowOffset: {width: 0, height: 1},
      elevation: 3,
    },
    sliderLabels: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 6,
    },
    sliderLabel: {
      color: colors.gray[400],
      fontSize: 12,
      fontWeight: '500',
    },
    footer: {
      flexDirection: 'row',
      gap: 10,
      paddingTop: 12,
    },
    clearBtn: {
      flex: 1,
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: colors.gray[300],
      backgroundColor: colors.white,
      paddingVertical: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    clearText: {
      color: colors.navy[900],
      fontSize: 15,
      fontWeight: '700',
    },
    applyBtn: {
      flex: 1.15,
      borderRadius: 14,
      backgroundColor: colors.orange[500],
      paddingVertical: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    applyText: {
      color: colors.white,
      fontSize: 15,
      fontWeight: '700',
    },
  });
}
