import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scroll: {
      paddingHorizontal: 20,
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 16,
    },
    iconBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.card,
      borderWidth: colors.isDark ? 1 : 0,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    iconBtnOutline: {
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
    },
    title: {
      fontFamily: colors.fonts.sora.extraBold,
      flex: 1,
      textAlign: 'center',
      color: colors.text,
      fontSize: 26,
      letterSpacing: -0.4,
    },
    headerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    searchBox: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      backgroundColor: colors.isDark ? colors.surface : colors.gray[100],
      borderRadius: 16,
      borderWidth: colors.isDark ? 1 : 0,
      borderColor: colors.border,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 14,
    },
    searchInput: {
      fontFamily: colors.fonts.sora.regular,
      flex: 1,
      color: colors.text,
      fontSize: 15,
      padding: 0,
      margin: 0,
    },
    tabs: {
      flexDirection: 'row',
      backgroundColor: colors.isDark ? colors.surface : colors.gray[100],
      borderRadius: 14,
      padding: 4,
      marginBottom: 20,
      height: 48,
      alignItems: 'center',
    },
    tab: {
      flex: 1,
      height: 40,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tabActive: {
      backgroundColor: colors.card,
      shadowColor: colors.isDark ? colors.black : colors.navy[900],
      shadowOpacity: 0.08,
      shadowRadius: 6,
      shadowOffset: {width: 0, height: 1},
      elevation: 2,
    },
    tabText: {
      fontFamily: colors.fonts.sora.semiBold,
      color: colors.textMuted,
      fontSize: 13,
    },
    tabTextActive: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
    },
    monthLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.textSub,
      fontSize: 11,
      letterSpacing: 1.1,
      marginBottom: 10,
    },
    rideList: {
      gap: 12,
    },
    rideCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
    },
    rideTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 14,
    },
    rideWhen: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.textMuted,
      fontSize: 13,
    },
    statusPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 999,
    },
    statusDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
    },
    statusText: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 12,
    },
    routeBlock: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 14,
    },
    routeTimeline: {
      width: 14,
      alignItems: 'center',
      paddingTop: 4,
    },
    pickupDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.orange[500],
    },
    routeLine: {
      width: 2,
      flex: 1,
      minHeight: 28,
      backgroundColor: colors.isDark ? colors.navy[700] : colors.gray[300],
      marginVertical: 4,
    },
    dropDot: {
      width: 10,
      height: 10,
      borderRadius: 2,
      backgroundColor: colors.isDark ? colors.orange[400] : colors.navy[800],
    },
    routeCopy: {
      flex: 1,
      minWidth: 0,
      gap: 14,
    },
    stopLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.textSub,
      fontSize: 10,
      letterSpacing: 0.8,
      marginBottom: 2,
    },
    stopAddress: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 14,
      lineHeight: 19,
    },
    rideFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.borderLight,
      paddingTop: 12,
    },
    rideMeta: {
      fontFamily: colors.fonts.sora.medium,
      flex: 1,
      color: colors.textMuted,
      fontSize: 13,
    },
    rideFare: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 15,
    },
    emptyWrap: {
      alignItems: 'center',
      paddingHorizontal: 32,
      paddingTop: 80,
      paddingBottom: 40,
    },
    emptyIcon: {
      width: 108,
      height: 108,
      borderRadius: 54,
      backgroundColor: colors.isDark ? colors.surface : colors.gray[100],
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 22,
    },
    emptyTitle: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 22,
      textAlign: 'center',
      letterSpacing: -0.3,
    },
    emptyBody: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.textMuted,
      fontSize: 15,
      textAlign: 'center',
      lineHeight: 22,
      marginTop: 10,
      marginBottom: 22,
      maxWidth: 290,
    },
    bookBtn: {
      paddingVertical: 13,
      paddingHorizontal: 24,
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: colors.border,
      backgroundColor: colors.card,
    },
    bookText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 16,
    },
  });
}
