import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 18,
      paddingTop: 10,
      paddingBottom: 14,
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    backBtn: {
      width: 38,
      height: 38,
      borderRadius: 12,
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 26,
      letterSpacing: -0.5,
    },
    markAllBtn: {
      paddingVertical: 6,
      paddingHorizontal: 8,
    },
    markAllText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.primary,
      fontSize: 14,
    },
    pillsScroll: {
      paddingHorizontal: 18,
      paddingBottom: 14,
      gap: 8,
      flexDirection: 'row',
    },
    pill: {
      paddingHorizontal: 18,
      paddingVertical: 9,
      borderRadius: 22,
      backgroundColor: colors.card,
      borderWidth: 1.5,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    pillActive: {
      borderColor: colors.primary,
      backgroundColor: colors.isDark ? colors.alpha.orange20 : colors.orange.subtleBg,
    },
    pillText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.textMuted,
      fontSize: 14,
    },
    pillTextActive: {
      color: colors.primary,
    },
    scroll: {
      paddingHorizontal: 18,
      paddingTop: 6,
      paddingBottom: 40,
    },
    sectionTitle: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.textSub,
      fontSize: 11.5,
      letterSpacing: 0.8,
      marginBottom: 10,
      marginTop: 6,
    },
    sectionTitleLater: {
      marginTop: 18,
    },
    card: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      backgroundColor: colors.card,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 14,
      paddingVertical: 14,
      marginBottom: 10,
      shadowColor: colors.isDark ? colors.black : colors.navy.textDark,
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.04,
      shadowRadius: 6,
      elevation: 1.5,
    },
    cardUnread: {
      borderColor: colors.isDark ? colors.orange[600] : colors.orange[400],
      backgroundColor: colors.isDark ? colors.alpha.orange10 : colors.orange.subtleBg,
    },
    unreadDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.primary,
      marginLeft: 6,
    },
    iconBox: {
      width: 44,
      height: 44,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    cardBody: {
      flex: 1,
      paddingRight: 6,
    },
    titleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 3,
    },
    timeWrap: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    itemTitle: {
      fontFamily: colors.fonts.sora.bold,
      flex: 1,
      color: colors.text,
      fontSize: 14.5,
      marginRight: 6,
    },
    itemTime: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.textSub,
      fontSize: 12,
    },
    itemSubtitle: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.textMuted,
      fontSize: 13,
      lineHeight: 18,
    },
    emptyBox: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 60,
    },
    emptyText: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.subtext,
      fontSize: 14,
      marginTop: 10,
    },
  });
}
