import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    hero: {
      backgroundColor: colors.navy[950],
      borderBottomLeftRadius: 36,
      borderBottomRightRadius: 36,
      paddingHorizontal: 18,
      paddingBottom: 20,
      position: 'relative',
      overflow: 'hidden',
    },
    glow: {
      position: 'absolute',
      top: 0,
      right: 0,
      width: 240,
      height: 260,
      opacity: 0.85,
    },
    menuBtn: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: colors.alpha.white12,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 24,
    },
    userRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    avatarRing: {
      width: 72,
      height: 72,
      borderRadius: 36,
      borderWidth: 2.5,
      borderColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 14,
    },
    avatarInner: {
      width: 62,
      height: 62,
      borderRadius: 31,
      backgroundColor: colors.navy[800],
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    avatarPhoto: {
      width: 62,
      height: 62,
      borderRadius: 31,
    },
    avatarInitials: {
      color: colors.white,
      fontSize: 20,
      fontWeight: '700',
    },
    userInfo: {
      flex: 1,
      marginRight: 8,
    },
    nameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    userName: {
      color: colors.white,
      fontSize: 19,
      fontWeight: '700',
    },
    userSub: {
      color: colors.alpha.white78,
      fontSize: 12.5,
      fontWeight: '400',
      marginTop: 3,
    },
    userEmail: {
      color: colors.alpha.white65,
      fontSize: 12,
      fontWeight: '400',
      marginTop: 2,
    },
    editBtn: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: colors.alpha.white14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    roleBar: {
      backgroundColor: colors.alpha.overlay55,
      borderRadius: 22,
      padding: 4,
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 34,
      height: 54,
    },
    roleTab: {
      flex: 1,
      height: '100%',
      borderRadius: 18,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
    },
    roleTabActive: {
      backgroundColor: colors.white,
      shadowColor: colors.black,
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.12,
      shadowRadius: 3,
      elevation: 2,
    },
    roleText: {
      color: colors.blue.gray,
      fontSize: 15,
      fontWeight: '600',
    },
    roleTextActive: {
      color: colors.navy.darkBg3,
      fontWeight: '700',
    },
    approvedBadge: {
      backgroundColor: colors.green[600],
      borderRadius: 12,
      paddingHorizontal: 8,
      paddingVertical: 3.5,
      marginLeft: 4,
    },
    approvedText: {
      color: colors.white,
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 0.5,
    },
    scroll: {
      paddingHorizontal: 16,
      paddingTop: 14,
    },
    sectionLabel: {
      color: colors.textSub,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.8,
      marginBottom: 10,
    },
    card: {
      backgroundColor: colors.card,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: 'hidden',
      marginBottom: 18,
    },
    rowItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 14,
    },
    rowBorder: {
      borderBottomWidth: 1,
      borderBottomColor: colors.borderLight,
    },
    rowIconBox: {
      width: 38,
      height: 38,
      borderRadius: 12,
      backgroundColor: colors.iconBg,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    rowBody: {
      flex: 1,
      marginRight: 8,
    },
    rowTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
      marginBottom: 2,
    },
    rowSub: {
      color: colors.textMuted,
      fontSize: 13.5,
      fontWeight: '400',
      lineHeight: 18,
    },
    toggleTrack: {
      width: 44,
      height: 24,
      borderRadius: 12,
      padding: 2,
      justifyContent: 'center',
    },
    toggleTrackActive: {
      backgroundColor: colors.primary,
    },
    toggleTrackInactive: {
      backgroundColor: colors.isDark ? colors.navy.borderMuted : colors.navy.borderSoft,
    },
    toggleThumb: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: colors.white,
      shadowColor: colors.black,
      shadowOffset: {width: 0, height: 1},
      shadowOpacity: 0.2,
      shadowRadius: 1.5,
      elevation: 2,
    },
    toggleThumbActive: {
      alignSelf: 'flex-end',
    },
    toggleThumbInactive: {
      alignSelf: 'flex-start',
    },
    deleteIconBox: {
      backgroundColor: colors.isDark ? colors.alpha.red18 : colors.red.badge,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: colors.overlay,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 20,
    },
    modalCard: {
      width: '100%',
      maxWidth: 350,
      backgroundColor: colors.surface,
      borderRadius: 28,
      paddingHorizontal: 22,
      paddingTop: 28,
      paddingBottom: 20,
      alignItems: 'center',
      shadowColor: colors.black,
      shadowOffset: {width: 0, height: 10},
      shadowOpacity: 0.25,
      shadowRadius: 20,
      elevation: 10,
    },
    modalIconRing: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: colors.isDark ? colors.alpha.red18 : colors.red.badge,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
    },
    modalTitle: {
      color: colors.text,
      fontSize: 20,
      fontWeight: '800',
      textAlign: 'center',
      marginBottom: 8,
    },
    modalSub: {
      color: colors.textMuted,
      fontSize: 14,
      fontWeight: '400',
      textAlign: 'center',
      lineHeight: 20,
      marginBottom: 18,
      paddingHorizontal: 6,
    },
    modalInfoBox: {
      width: '100%',
      backgroundColor: colors.cardHighlight,
      borderRadius: 16,
      padding: 16,
      marginBottom: 22,
      gap: 12,
    },
    modalInfoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    modalInfoText: {
      flex: 1,
      color: colors.text,
      fontSize: 13,
      fontWeight: '500',
      lineHeight: 18,
    },
    modalDeleteBtn: {
      width: '100%',
      height: 50,
      borderRadius: 14,
      backgroundColor: colors.red[600],
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 8,
    },
    modalDeleteBtnText: {
      color: colors.white,
      fontSize: 15,
      fontWeight: '700',
    },
    modalKeepBtn: {
      paddingVertical: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modalKeepBtnText: {
      color: colors.primary,
      fontSize: 15,
      fontWeight: '700',
    },
  });
}
