import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: '#F3F6FA',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingBottom: 12,
      backgroundColor: '#FFFFFF',
    },
    headerBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      color: '#0F2840',
      fontSize: 18,
      fontWeight: '700',
    },
    scroll: {
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    statusCard: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#E8ECF2',
      padding: 14,
      marginBottom: 16,
    },
    statusIconContainer: {
      marginRight: 12,
      marginTop: 2,
    },
    statusBody: {
      flex: 1,
    },
    statusTitle: {
      color: '#0F2840',
      fontSize: 14.5,
      fontWeight: '700',
      marginBottom: 3,
    },
    statusSub: {
      color: '#6E7C91',
      fontSize: 12,
      fontWeight: '400',
      lineHeight: 16,
    },
    sectionLabel: {
      color: '#7E8B9E',
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.8,
      marginBottom: 10,
    },
    contactCard: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#E8ECF2',
      paddingHorizontal: 14,
      paddingTop: 12,
      paddingBottom: 10,
      marginBottom: 10,
    },
    contactTop: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
    },
    avatar: {
      width: 42,
      height: 42,
      borderRadius: 21,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    avatarText: {
      fontSize: 14,
      fontWeight: '700',
    },
    contactInfo: {
      flex: 1,
    },
    contactName: {
      color: '#0F2840',
      fontSize: 14.5,
      fontWeight: '700',
      marginBottom: 2,
    },
    contactMeta: {
      color: '#6E7C91',
      fontSize: 11.5,
      fontWeight: '400',
    },
    menuBtn: {
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
    },
    togglesRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingTop: 4,
      borderTopWidth: 1,
      borderTopColor: '#F4F6F9',
    },
    toggleItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    toggleText: {
      color: '#0F2840',
      fontSize: 11.5,
      fontWeight: '500',
    },
    toggleTrack: {
      width: 44,
      height: 24,
      borderRadius: 12,
      padding: 2,
      justifyContent: 'center',
    },
    toggleTrackActive: {
      backgroundColor: '#FF7006',
    },
    toggleTrackInactive: {
      backgroundColor: '#B5BFC9',
    },
    toggleThumb: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: '#FFFFFF',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 1},
      shadowOpacity: 0.2,
      shadowRadius: 1.5,
      elevation: 2,
    },
    toggleThumbActive: {
      alignSelf: 'flex-end',
    },
    toggleThumbInactive: {
      alignSelf: 'flex-start',
    },
    addCard: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      borderWidth: 1.5,
      borderStyle: 'dashed',
      borderColor: '#FF7006',
      borderRadius: 16,
      backgroundColor: '#FFFFFF',
      height: 50,
      marginTop: 2,
      marginBottom: 14,
    },
    addText: {
      color: '#FF7006',
      fontSize: 14,
      fontWeight: '700',
    },
    privacyCard: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#E8ECF2',
      padding: 14,
      marginBottom: 12,
    },
    privacyTitle: {
      color: '#0F2840',
      fontSize: 13.5,
      fontWeight: '700',
      marginBottom: 10,
    },
    privacyRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 8,
    },
    privacyRowLast: {
      marginBottom: 0,
    },
    privacyText: {
      flex: 1,
      color: '#0F2840',
      fontSize: 12,
      fontWeight: '400',
      lineHeight: 16,
    },
    privacyTextMuted: {
      color: '#6E7C91',
    },
    footer: {
      paddingHorizontal: 16,
      paddingTop: 10,
      backgroundColor: '#FFFFFF',
      borderTopWidth: 1,
      borderTopColor: '#F0F3F7',
    },
    saveBtn: {
      backgroundColor: '#FF7006',
      borderRadius: 16,
      height: 52,
      alignItems: 'center',
      justifyContent: 'center',
    },
    saveText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '700',
    },
  });
}
