import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.gray[50],
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 12,
      paddingBottom: 10,
      backgroundColor: colors.white,
    },
    headerBtn: {
      width: 44,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      color: colors.navy[900],
      fontSize: 17,
      fontWeight: '700',
    },
    scroll: {
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    statusCard: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      backgroundColor: colors.white,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.gray[200],
      padding: 14,
      marginBottom: 20,
    },
    statusIcon: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: colors.blue[100],
      alignItems: 'center',
      justifyContent: 'center',
    },
    statusTitle: {
      color: colors.navy[900],
      fontSize: 15,
      fontWeight: '700',
      marginBottom: 4,
    },
    statusSub: {
      color: colors.gray[500],
      fontSize: 13,
      fontWeight: '500',
      lineHeight: 18,
    },
    sectionLabel: {
      color: colors.gray[400],
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1.1,
      marginBottom: 12,
    },
    contactCard: {
      backgroundColor: colors.white,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.gray[200],
      padding: 14,
      marginBottom: 12,
    },
    contactTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      marginBottom: 14,
    },
    avatar: {
      width: 46,
      height: 46,
      borderRadius: 23,
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarText: {
      fontSize: 14,
      fontWeight: '800',
    },
    contactInfo: {
      flex: 1,
      paddingTop: 2,
    },
    contactName: {
      color: colors.navy[900],
      fontSize: 15,
      fontWeight: '700',
      marginBottom: 3,
    },
    contactMeta: {
      color: colors.gray[500],
      fontSize: 13,
      fontWeight: '500',
    },
    menuBtn: {
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: -4,
      marginRight: -4,
    },
    toggleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 6,
    },
    toggleLabel: {
      color: colors.navy[800],
      fontSize: 13,
      fontWeight: '600',
      flex: 1,
      paddingRight: 12,
    },
    addCard: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderWidth: 1.5,
      borderStyle: 'dashed',
      borderColor: colors.orange[400],
      borderRadius: 16,
      backgroundColor: colors.white,
      paddingVertical: 16,
      marginTop: 4,
      marginBottom: 16,
    },
    addText: {
      color: colors.orange[600],
      fontSize: 15,
      fontWeight: '700',
    },
    privacyCard: {
      backgroundColor: colors.white,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.gray[200],
      padding: 14,
      marginBottom: 8,
    },
    privacyTitle: {
      color: colors.navy[900],
      fontSize: 15,
      fontWeight: '700',
      marginBottom: 12,
    },
    privacyRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      marginBottom: 10,
    },
    privacyRowLast: {
      marginBottom: 0,
    },
    privacyText: {
      flex: 1,
      color: colors.navy[800],
      fontSize: 13,
      fontWeight: '500',
      lineHeight: 18,
    },
    privacyTextMuted: {
      color: colors.gray[500],
    },
    footer: {
      paddingHorizontal: 16,
      paddingTop: 10,
      backgroundColor: colors.white,
      borderTopWidth: 1,
      borderTopColor: colors.gray[100],
    },
    saveBtn: {
      backgroundColor: colors.orange[500],
      borderRadius: 16,
      paddingVertical: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    saveText: {
      color: colors.white,
      fontSize: 16,
      fontWeight: '700',
    },
  });
}
