import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingBottom: 12,
      backgroundColor: colors.card,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      color: colors.text,
      fontSize: 18,
      fontWeight: '700',
    },
    headerSpacer: {
      width: 40,
    },
    scroll: {
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    searchBox: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.inputBg,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 14,
      height: 48,
      marginBottom: 14,
      gap: 10,
    },
    searchInput: {
      flex: 1,
      color: colors.text,
      fontSize: 14,
      padding: 0,
      margin: 0,
    },
    lastTripCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.isDark ? colors.card : colors.navy[900],
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
      marginBottom: 18,
      gap: 12,
    },
    lastTripIcon: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: colors.isDark ? colors.iconBg : colors.navy[700],
      alignItems: 'center',
      justifyContent: 'center',
    },
    lastTripBody: {
      flex: 1,
    },
    lastTripTitle: {
      color: colors.white,
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 3,
    },
    lastTripSub: {
      color: colors.alpha.white72,
      fontSize: 12,
      fontWeight: '400',
    },
    sectionLabel: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.8,
      marginBottom: 10,
    },
    topicsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: 12,
      marginBottom: 20,
    },
    topicCard: {
      width: '48.5%',
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 14,
      paddingHorizontal: 14,
    },
    topicIcon: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: colors.iconBg,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 10,
    },
    currencyText: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '700',
    },
    topicTitle: {
      color: colors.text,
      fontSize: 13.5,
      fontWeight: '700',
    },
    faqCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 16,
      overflow: 'hidden',
    },
    faqItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 14,
    },
    faqItemBorder: {
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    faqText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '500',
      flex: 1,
      marginRight: 10,
    },
    footer: {
      paddingHorizontal: 16,
      paddingTop: 10,
      backgroundColor: colors.card,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    chatBtn: {
      backgroundColor: colors.primary,
      borderRadius: 16,
      height: 52,
      alignItems: 'center',
      justifyContent: 'center',
    },
    chatBtnText: {
      color: colors.white,
      fontSize: 16,
      fontWeight: '700',
    },
  });
}
