import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: '#F3F6FA',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingBottom: 12,
      backgroundColor: '#FFFFFF',
    },
    headerBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      color: '#0F2840',
      fontSize: 18,
      fontWeight: '700',
    },
    headerSpacer: {
      width: 40,
    },
    scroll: {
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    searchBox: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#F3F6FA',
      borderRadius: 14,
      borderWidth: 1,
      borderColor: '#E8ECF2',
      paddingHorizontal: 14,
      height: 48,
      marginBottom: 14,
      gap: 10,
    },
    searchInput: {
      flex: 1,
      color: '#0F2840',
      fontSize: 14,
      padding: 0,
      margin: 0,
    },
    lastTripCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#0E2841',
      borderRadius: 18,
      padding: 14,
      marginBottom: 18,
      gap: 12,
    },
    lastTripIcon: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: '#1C3B57',
      alignItems: 'center',
      justifyContent: 'center',
    },
    lastTripBody: {
      flex: 1,
    },
    lastTripTitle: {
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 3,
    },
    lastTripSub: {
      color: 'rgba(255, 255, 255, 0.72)',
      fontSize: 12,
      fontWeight: '400',
    },
    sectionLabel: {
      color: '#7E8B9E',
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.8,
      marginBottom: 10,
    },
    topicsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: 12,
      marginBottom: 20,
    },
    topicCard: {
      width: '48.5%',
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#E8ECF2',
      paddingVertical: 14,
      paddingHorizontal: 14,
    },
    topicIcon: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: '#F0F4F8',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 10,
    },
    currencyText: {
      color: '#0F2840',
      fontSize: 16,
      fontWeight: '700',
    },
    topicTitle: {
      color: '#0F2840',
      fontSize: 13.5,
      fontWeight: '700',
    },
    faqCard: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#E8ECF2',
      marginBottom: 16,
      overflow: 'hidden',
    },
    faqItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 14,
    },
    faqItemBorder: {
      borderBottomWidth: 1,
      borderBottomColor: '#F0F3F7',
    },
    faqText: {
      color: '#0F2840',
      fontSize: 13,
      fontWeight: '500',
      flex: 1,
      marginRight: 10,
    },
    footer: {
      paddingHorizontal: 16,
      paddingTop: 10,
      backgroundColor: '#FFFFFF',
      borderTopWidth: 1,
      borderTopColor: '#F0F3F7',
    },
    chatBtn: {
      backgroundColor: '#FF7006',
      borderRadius: 16,
      height: 52,
      alignItems: 'center',
      justifyContent: 'center',
    },
    chatBtnText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '700',
    },
  });
}
