import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.gray[50],
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 12,
      paddingBottom: 10,
      backgroundColor: colors.white,
    },
    headerBtn: {
      width: 44,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      color: colors.navy[900],
      fontSize: 17,
      fontWeight: '700',
    },
    scroll: {
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    hero: {
      backgroundColor: '#123C38',
      borderRadius: 18,
      paddingVertical: 18,
      paddingHorizontal: 16,
      marginBottom: 20,
      gap: 8,
    },
    heroIcon: {
      width: 28,
      height: 28,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 2,
    },
    heroTitle: {
      color: colors.white,
      fontSize: 18,
      fontWeight: '800',
    },
    heroSub: {
      color: 'rgba(255,255,255,0.82)',
      fontSize: 13,
      fontWeight: '500',
      lineHeight: 19,
    },
    sectionLabel: {
      color: colors.gray[400],
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1.1,
      marginBottom: 12,
    },
    toolsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: 12,
      marginBottom: 14,
    },
    toolCard: {
      width: '48.2%',
      backgroundColor: colors.white,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.gray[200],
      paddingVertical: 14,
      paddingHorizontal: 12,
      minHeight: 118,
    },
    toolIcon: {
      width: 36,
      height: 36,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 10,
    },
    toolTitle: {
      color: colors.navy[900],
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 4,
    },
    toolSub: {
      color: colors.gray[500],
      fontSize: 12,
      fontWeight: '500',
      lineHeight: 16,
    },
    insuranceCard: {
      backgroundColor: colors.white,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.gray[200],
      padding: 14,
      marginBottom: 8,
    },
    insuranceTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      marginBottom: 14,
    },
    insuranceIcon: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: colors.green[100],
      alignItems: 'center',
      justifyContent: 'center',
    },
    insuranceTitle: {
      color: colors.navy[900],
      fontSize: 15,
      fontWeight: '700',
      marginBottom: 4,
    },
    insuranceSub: {
      color: colors.gray[500],
      fontSize: 13,
      fontWeight: '500',
      lineHeight: 18,
    },
    insuranceFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderTopWidth: 1,
      borderTopColor: colors.gray[100],
      paddingTop: 12,
    },
    policyLink: {
      color: colors.orange[600],
      fontSize: 14,
      fontWeight: '700',
    },
    policyId: {
      color: colors.gray[400],
      fontSize: 12,
      fontWeight: '600',
    },
    footer: {
      paddingHorizontal: 16,
      paddingTop: 10,
      backgroundColor: colors.white,
      borderTopWidth: 1,
      borderTopColor: colors.gray[100],
    },
    sosBtn: {
      backgroundColor: colors.red[500],
      borderRadius: 16,
      paddingVertical: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sosText: {
      color: colors.white,
      fontSize: 16,
      fontWeight: '700',
    },
  });
}
