import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: '#F3F6FA',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingBottom: 12,
      backgroundColor: '#FFFFFF',
    },
    headerBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      color: '#0F2840',
      fontSize: 18,
      fontWeight: '700',
    },
    content: {
      flex: 1,
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 10,
      gap: 10,
    },
    hero: {
      backgroundColor: '#0C2D39',
      borderRadius: 18,
      paddingTop: 14,
      paddingBottom: 14,
      paddingHorizontal: 16,
      position: 'relative',
      overflow: 'hidden',
    },
    heroCircle: {
      position: 'absolute',
      right: -30,
      top: -30,
      width: 170,
      height: 170,
      borderRadius: 85,
      backgroundColor: '#123D4D',
      opacity: 0.85,
    },
    heroIcon: {
      width: 30,
      height: 30,
      alignItems: 'flex-start',
      justifyContent: 'center',
      marginBottom: 4,
    },
    heroTitle: {
      color: '#FFFFFF',
      fontSize: 17,
      fontWeight: '700',
      marginBottom: 3,
    },
    heroSub: {
      color: 'rgba(255, 255, 255, 0.8)',
      fontSize: 12,
      fontWeight: '400',
      lineHeight: 16,
      maxWidth: '92%',
    },
    toolsSection: {
      marginTop: 0,
    },
    sectionLabel: {
      color: '#7E8B9E',
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.8,
      marginTop: 0,
      marginBottom: 6,
    },
    toolsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: 8,
    },
    toolCard: {
      width: '48.5%',
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#E8ECF2',
      paddingVertical: 10,
      paddingHorizontal: 12,
      justifyContent: 'flex-start',
    },
    toolIcon: {
      width: 34,
      height: 34,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 6,
    },
    toolTitle: {
      color: '#0F2840',
      fontSize: 13.5,
      fontWeight: '700',
      marginBottom: 2,
    },
    toolSub: {
      color: '#6E7C91',
      fontSize: 11,
      fontWeight: '400',
      lineHeight: 14.5,
    },
    insuranceCard: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#E8ECF2',
      paddingVertical: 11,
      paddingHorizontal: 14,
      marginTop: 0,
    },
    insuranceTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginBottom: 10,
    },
    insuranceIcon: {
      marginRight: 10,
      marginTop: 2,
    },
    insuranceBody: {
      flex: 1,
    },
    insuranceTitle: {
      color: '#0F2840',
      fontSize: 13.5,
      fontWeight: '700',
      marginBottom: 2,
    },
    insuranceSub: {
      color: '#6E7C91',
      fontSize: 11.5,
      fontWeight: '400',
      lineHeight: 15,
    },
    insuranceFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingTop: 2,
    },
    policyLink: {
      color: '#FF7006',
      fontSize: 13,
      fontWeight: '700',
    },
    policyId: {
      color: '#8A96A6',
      fontSize: 11.5,
      fontWeight: '500',
    },
    footer: {
      paddingHorizontal: 16,
      paddingTop: 10,
      backgroundColor: '#FFFFFF',
    },
    sosBtn: {
      backgroundColor: '#E53935',
      borderRadius: 18,
      height: 52,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sosText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '700',
    },
  });
}
