import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingBottom: 12,
      backgroundColor: colors.card,
      borderBottomWidth: colors.isDark ? 1 : 0,
      borderBottomColor: colors.border,
    },
    headerBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      fontFamily: colors.fonts.sora.bold,
      flex: 1,
      textAlign: 'center',
      color: colors.text,
      fontSize: 18,
    },
    content: {
      flex: 1,
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 10,
      gap: 10,
    },
    hero: {
      backgroundColor: colors.navy.safetyDark1,
      borderRadius: 18,
      paddingTop: 14,
      paddingBottom: 14,
      paddingHorizontal: 16,
      position: 'relative',
      overflow: 'hidden',
    },
    heroCircle: {
      position: 'absolute',
      right: -30,
      top: -30,
      width: 170,
      height: 170,
      borderRadius: 85,
      backgroundColor: colors.navy.safetyDark2,
      opacity: 0.85,
    },
    heroIcon: {
      width: 30,
      height: 30,
      alignItems: 'flex-start',
      justifyContent: 'center',
      marginBottom: 4,
    },
    heroTitle: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.white,
      fontSize: 17,
      marginBottom: 3,
    },
    heroSub: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.alpha.white80,
      fontSize: 12,
      lineHeight: 16,
      maxWidth: '92%',
    },
    toolsSection: {
      marginTop: 0,
    },
    sectionLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.textSub,
      fontSize: 11,
      letterSpacing: 0.8,
      marginTop: 0,
      marginBottom: 6,
    },
    toolsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: 8,
    },
    toolCard: {
      width: '48.5%',
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 10,
      paddingHorizontal: 12,
      justifyContent: 'flex-start',
    },
    toolIcon: {
      width: 34,
      height: 34,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 6,
    },
    toolTitle: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 13.5,
      marginBottom: 2,
    },
    toolSub: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.textMuted,
      fontSize: 11,
      lineHeight: 14.5,
    },
    insuranceCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 11,
      paddingHorizontal: 14,
      marginTop: 0,
    },
    insuranceTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginBottom: 10,
    },
    insuranceIcon: {
      marginRight: 10,
      marginTop: 2,
    },
    insuranceBody: {
      flex: 1,
    },
    insuranceTitle: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 13.5,
      marginBottom: 2,
    },
    insuranceSub: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.textMuted,
      fontSize: 11.5,
      lineHeight: 15,
    },
    insuranceFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingTop: 2,
    },
    policyLink: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.primary,
      fontSize: 13,
    },
    policyId: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.textSub,
      fontSize: 11.5,
    },
    footer: {
      paddingHorizontal: 16,
      paddingTop: 10,
      backgroundColor: colors.card,
      borderTopWidth: colors.isDark ? 1 : 0,
      borderTopColor: colors.border,
    },
    sosBtn: {
      backgroundColor: colors.red.primary,
      borderRadius: 18,
      height: 52,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sosText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.white,
      fontSize: 16,
    },
  });
}
