import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    backBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      fontSize: 18,
      fontFamily: 'Sora-Bold',
      color: colors.text,
      textAlign: 'center',
    },
    supportBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    content: {
      flex: 1,
      paddingHorizontal: 20,
      paddingTop: 8,
    },
    passengerCard: {
      backgroundColor: colors.isDark ? colors.surface : colors.navy[900],
      borderRadius: 18,
      padding: 16,
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: colors.isDark ? 1 : 0,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 4},
      shadowOpacity: 0.1,
      shadowRadius: 10,
      elevation: 4,
    },
    avatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.isDark ? 'rgba(255,255,255,0.12)' : 'rgba(255,255,255,0.18)',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    avatarText: {
      color: colors.white,
      fontFamily: 'Sora-Bold',
      fontSize: 16,
    },
    passengerDetails: {
      flex: 1,
      marginRight: 8,
    },
    passengerName: {
      color: colors.white,
      fontFamily: 'Sora-Bold',
      fontSize: 15,
      marginBottom: 3,
    },
    routeText: {
      color: 'rgba(255, 255, 255, 0.72)',
      fontSize: 12,
      fontFamily: 'Sora-Regular',
      lineHeight: 16,
    },
    fareContainer: {
      alignItems: 'flex-end',
    },
    cashLabel: {
      color: 'rgba(255, 255, 255, 0.6)',
      fontSize: 11,
      fontFamily: 'Sora-SemiBold',
      letterSpacing: 0.5,
      marginBottom: 2,
    },
    fareAmount: {
      color: colors.orange[500],
      fontFamily: 'Sora-Bold',
      fontSize: 20,
    },
    instructionSection: {
      marginTop: 20,
      alignItems: 'center',
      paddingHorizontal: 8,
    },
    instructionTitle: {
      fontSize: 22,
      fontFamily: 'Sora-Bold',
      fontWeight: '800',
      color: colors.isDark ? '#FFFFFF' : '#0B1E36',
      textAlign: 'center',
      marginBottom: 8,
      letterSpacing: -0.4,
    },
    instructionSub: {
      fontSize: 13.5,
      fontFamily: 'Sora-Regular',
      color: colors.isDark ? colors.navy[300] : '#64748B',
      textAlign: 'center',
      lineHeight: 19,
      paddingHorizontal: 12,
    },
    otpSectionWrapper: {
      position: 'relative',
      marginTop: 22,
      alignSelf: 'center',
    },
    otpSection: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 10,
    },
    otpBox: {
      width: 56,
      height: 68,
      borderRadius: 16,
      backgroundColor: colors.isDark ? colors.card : '#F8FAFC',
      borderWidth: 1.5,
      borderColor: colors.isDark ? colors.border : '#E2E8F0',
      alignItems: 'center',
      justifyContent: 'center',
    },
    otpBoxActive: {
      borderColor: colors.primary,
      borderWidth: 2,
      backgroundColor: colors.isDark ? 'rgba(255,112,6,0.08)' : '#FFFFFF',
    },
    otpBoxFilled: {
      borderColor: colors.isDark ? colors.border : '#CBD5E1',
    },
    otpBoxError: {
      borderColor: '#EF4444',
      borderWidth: 1.5,
      backgroundColor: colors.isDark ? 'rgba(239,68,68,0.12)' : '#FEF2F2',
    },
    otpDigit: {
      fontSize: 26,
      fontFamily: 'Sora-Bold',
      fontWeight: '800',
      color: colors.isDark ? '#FFFFFF' : '#0B1E36',
    },
    otpDigitError: {
      color: '#DC2626',
    },
    cursor: {
      fontSize: 26,
      fontFamily: 'Sora-Regular',
      color: colors.primary,
      marginTop: -2,
    },
    attemptBadge: {
      alignSelf: 'center',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.isDark ? colors.card : '#F1F5F9',
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 20,
      marginTop: 18,
      borderWidth: colors.isDark ? 1 : 0,
      borderColor: colors.border,
    },
    attemptBadgeLocked: {
      backgroundColor: colors.isDark ? 'rgba(239,68,68,0.16)' : '#FEE2E2',
      borderColor: colors.isDark ? '#EF4444' : '#FECDD3',
      borderWidth: 1,
    },
    attemptText: {
      fontSize: 12.5,
      fontFamily: 'Sora-SemiBold',
      color: colors.muted,
    },
    attemptTextLocked: {
      color: '#DC2626',
      fontFamily: 'Sora-Bold',
    },
    errorRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
      marginTop: 16,
      paddingHorizontal: 4,
    },
    errorText: {
      flex: 1,
      fontSize: 13,
      fontFamily: 'Sora-SemiBold',
      color: '#DC2626',
      lineHeight: 18,
    },
    supportCard: {
      marginTop: 14,
      borderRadius: 20,
      padding: 16,
      backgroundColor: colors.isDark ? 'rgba(239,68,68,0.1)' : '#FFF1F2',
      borderWidth: 1,
      borderColor: colors.isDark ? 'rgba(239,68,68,0.25)' : '#FECDD3',
    },
    supportCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    supportCardTitle: {
      fontSize: 14.5,
      fontFamily: 'Sora-Bold',
      color: colors.isDark ? '#FCA5A5' : '#991B1B',
      flex: 1,
    },
    supportCardSub: {
      fontSize: 12,
      fontFamily: 'Sora-Regular',
      color: colors.isDark ? '#FCA5A5' : '#991B1B',
      lineHeight: 17.5,
      marginTop: 8,
      marginBottom: 14,
      opacity: 0.9,
    },
    callSupportBtn: {
      backgroundColor: '#E11D48',
      borderRadius: 14,
      height: 46,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    callSupportText: {
      color: '#FFFFFF',
      fontFamily: 'Sora-Bold',
      fontSize: 14,
    },
    hiddenInput: {
      position: 'absolute',
      top: -9999,
      left: -9999,
      width: 1,
      height: 1,
      opacity: 0,
    },
    footer: {
      backgroundColor: colors.isDark ? colors.surface : '#FFFFFF',
      borderTopWidth: 1,
      borderTopColor: colors.isDark ? colors.border : '#E2E8F0',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: -3},
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 10,
      paddingHorizontal: 20,
      paddingTop: 16,
      gap: 14,
      alignItems: 'center',
    },
    startTripBtn: {
      width: '100%',
      height: 54,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
    },
    startTripBtnDisabled: {
      backgroundColor: colors.isDark ? colors.card : '#E2E8F0',
    },
    startTripBtnText: {
      color: colors.white,
      fontFamily: 'Sora-Bold',
      fontSize: 16,
    },
    startTripBtnTextDisabled: {
      color: colors.isDark ? colors.muted : '#94A3B8',
    },
    cantFindCodeBtn: {
      paddingVertical: 8,
      paddingHorizontal: 12,
    },
    cantFindCodeText: {
      fontSize: 14,
      fontFamily: 'Sora-SemiBold',
      color: colors.isDark ? colors.navy[200] : '#475569',
      textAlign: 'center',
    },
    cancelPenaltyText: {
      color: '#DC2626',
      fontFamily: 'Sora-Bold',
      fontSize: 14.5,
      textAlign: 'center',
    },
  });
}
