import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    backBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      fontSize: 18,
      fontFamily: colors.fonts.sora.regular,
      color: colors.text,
      textAlign: 'center',
    },
    supportBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    content: {
      flex: 1,
      paddingHorizontal: 20,
      paddingTop: 8,
    },
    passengerCard: {
      backgroundColor: colors.navy[850],
      borderRadius: 18,
      padding: 16,
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 0,
      borderColor: colors.border,
      shadowColor: colors.black,
      shadowOffset: {width: 0, height: 4},
      shadowOpacity: 0.1,
      shadowRadius: 10,
      elevation: 4,
    },
    avatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.alpha.white18,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    avatarText: {
      color: colors.white,
      fontFamily: colors.fonts.sora.regular,
      fontSize: 16,
    },
    passengerDetails: {
      flex: 1,
      marginRight: 8,
    },
    passengerName: {
      color: colors.white,
      fontFamily: colors.fonts.sora.regular,
      fontSize: 15,
      marginBottom: 3,
    },
    routeText: {
      color: colors.alpha.white72,
      fontSize: 12,
      fontFamily: colors.fonts.sora.regular,
      lineHeight: 16,
    },
    fareContainer: {
      alignItems: 'flex-end',
    },
    cashLabel: {
      color: colors.alpha.white60,
      fontSize: 11,
      fontFamily: colors.fonts.sora.regular,
      letterSpacing: 0.5,
      marginBottom: 2,
    },
    fareAmount: {
      color: colors.orange[500],
      fontFamily: colors.fonts.sora.regular,
      fontSize: 20,
    },
    instructionSection: {
      marginTop: 20,
      alignItems: 'center',
      paddingHorizontal: 8,
    },
    instructionTitle: {
      fontSize: 22,
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      textAlign: 'center',
      marginBottom: 8,
      letterSpacing: -0.4,
    },
    instructionSub: {
      fontSize: 13.5,
      fontFamily: colors.fonts.sora.regular,
      color: colors.textMuted,
      textAlign: 'center',
      lineHeight: 19,
      paddingHorizontal: 12,
    },
    otpSectionWrapper: {
      position: 'relative',
      marginTop: 22,
      alignSelf: 'center',
    },
    otpSection: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 10,
    },
    otpBox: {
      width: 56,
      height: 68,
      borderRadius: 16,
      backgroundColor: colors.surface,
      borderWidth: 1.5,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    otpBoxActive: {
      borderColor: colors.primary,
      borderWidth: 2,
      backgroundColor: colors.surface,
    },
    otpBoxFilled: {
      borderColor: colors.isDark ? colors.orange[500] : colors.orange[600],
      borderWidth: 2,
    },
    otpBoxError: {
      borderColor: colors.red[500],
      borderWidth: 1.5,
      backgroundColor: colors.isDark ? colors.alpha.red18 : colors.red[150],
    },
    otpDigit: {
      fontSize: 26,
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
    },
    otpDigitError: {
      color: colors.red[600],
    },
    cursor: {
      fontSize: 26,
      fontFamily: colors.fonts.sora.regular,
      color: colors.primary,
      marginTop: -2,
    },
    attemptBadge: {
      alignSelf: 'center',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.surface,
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 20,
      marginTop: 18,
      borderWidth: 1,
      borderColor: colors.border,
    },
    attemptBadgeLocked: {
      backgroundColor: colors.red[200],
      borderColor: colors.red[400],
      borderWidth: 1,
    },
    attemptText: {
      fontSize: 12.5,
      fontFamily: colors.fonts.sora.regular,
      color: colors.textMuted,
    },
    attemptTextLocked: {
      color: colors.red[600],
      fontFamily: 'Sora-Bold',
    },
    errorRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
      marginTop: 16,
      paddingHorizontal: 4,
    },
    errorText: {
      flex: 1,
      fontSize: 13,
      fontFamily: colors.fonts.sora.regular,
      color: colors.red[600],
      lineHeight: 18,
    },
    supportCard: {
      marginTop: 14,
      borderRadius: 20,
      padding: 16,
      backgroundColor: colors.red[50],
      borderWidth: 1,
      borderColor: colors.red[400],
    },
    supportCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    supportCardTitle: {
      fontSize: 14.5,
      fontFamily: colors.fonts.sora.regular,
      color: colors.red[800],
      flex: 1,
    },
    supportCardSub: {
      fontSize: 12,
      fontFamily: colors.fonts.sora.regular,
      color: colors.red[800],
      lineHeight: 17.5,
      marginTop: 8,
      marginBottom: 14,
      opacity: 0.9,
    },
    callSupportBtn: {
      backgroundColor: colors.red[750],
      borderRadius: 14,
      height: 46,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    callSupportText: {
      color: colors.white,
      fontFamily: colors.fonts.sora.regular,
      fontSize: 14,
    },
    hiddenInput: {
      position: 'absolute',
      top: -9999,
      left: -9999,
      width: 1,
      height: 1,
      opacity: 0,
    },
    footer: {
      backgroundColor: colors.surface,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      shadowColor: colors.black,
      shadowOffset: {width: 0, height: -3},
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 10,
      paddingHorizontal: 20,
      paddingTop: 16,
      gap: 14,
      alignItems: 'center',
    },
    startTripBtn: {
      width: '100%',
      height: 54,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
    },
    startTripBtnDisabled: {
      backgroundColor: colors.isDark ? colors.navy[800] : colors.border,
      borderWidth: colors.isDark ? 1 : 0,
      borderColor: colors.isDark ? colors.navy[700] : colors.transparent,
    },
    startTripBtnText: {
      color: colors.white,
      fontFamily: colors.fonts.sora.regular,
      fontSize: 16,
    },
    startTripBtnTextDisabled: {
      color: colors.textMuted,
    },
    cantFindCodeBtn: {
      paddingVertical: 8,
      paddingHorizontal: 12,
    },
    cantFindCodeText: {
      fontSize: 14,
      fontFamily: colors.fonts.sora.regular,
      color: colors.textSecondary,
      textAlign: 'center',
    },
    cancelPenaltyText: {
      color: colors.isDark ? colors.red[400] : colors.red[600],
      fontFamily: colors.fonts.sora.regular,
      fontSize: 14.5,
      textAlign: 'center',
    },
  });
}
