import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 12,
      paddingBottom: 10,
      backgroundColor: colors.card,
      borderBottomWidth: colors.isDark ? 1 : 0,
      borderBottomColor: colors.border,
    },
    headerBtn: {
      width: 44,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      fontFamily: colors.fonts.sora.bold,
      flex: 1,
      textAlign: 'center',
      color: colors.text,
      fontSize: 17,
    },
    scroll: {
      paddingHorizontal: 16,
      paddingTop: 14,
    },
    amountCard: {
      backgroundColor: colors.surface,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 22,
      paddingHorizontal: 20,
      marginBottom: 12,
      alignItems: 'center',
    },
    amountLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.muted,
      fontSize: 11,
      letterSpacing: 1.2,
      marginBottom: 12,
      textAlign: 'center',
    },
    sectionLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.muted,
      fontSize: 11,
      letterSpacing: 1.1,
      marginBottom: 10,
    },
    amountRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 12,
    },
    currency: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 32,
      marginRight: 2,
      marginTop: 4,
    },
    amountInput: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 42,
      padding: 0,
      margin: 0,
      letterSpacing: -0.8,
      minWidth: 40,
      textAlign: 'left',
    },
    amountHint: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.muted,
      fontSize: 13,
      textAlign: 'center',
      lineHeight: 18,
    },
    quickRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 20,
    },
    quickChip: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: colors.border,
      backgroundColor: colors.card,
    },
    quickChipActive: {
      borderColor: colors.orange[500],
      backgroundColor: colors.isDark ? colors.alpha.orange15 : colors.orange[50],
    },
    quickText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 14,
    },
    quickTextActive: {
      color: colors.orange[500],
    },
    methodList: {
      gap: 10,
      marginBottom: 14,
    },
    methodCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: colors.border,
      paddingVertical: 14,
      paddingHorizontal: 14,
    },
    methodCardActive: {
      borderColor: colors.orange[500],
      backgroundColor: colors.isDark ? colors.alpha.orange15 : colors.orange[50],
    },
    methodIcon: {
      width: 42,
      height: 42,
      borderRadius: 12,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    methodIconActive: {
      backgroundColor: colors.card,
    },
    methodCopy: {
      flex: 1,
      minWidth: 0,
    },
    methodTitle: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 15,
      marginBottom: 2,
    },
    methodSub: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.muted,
      fontSize: 13,
    },
    methodCheck: {
      width: 24,
      height: 24,
      borderRadius: 12,
      borderWidth: 2,
      borderColor: colors.orange[500],
      alignItems: 'center',
      justifyContent: 'center',
    },
    infoBanner: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      backgroundColor: colors.isDark ? colors.alpha.blue15 : colors.blue[100],
      borderRadius: 14,
      paddingVertical: 12,
      paddingHorizontal: 14,
    },
    infoText: {
      fontFamily: colors.fonts.sora.medium,
      flex: 1,
      color: colors.isDark ? colors.blue[300] : colors.navy[800],
      fontSize: 13,
      lineHeight: 19,
    },
    footer: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      paddingHorizontal: 16,
      paddingTop: 10,
      backgroundColor: colors.card,
      borderTopWidth: colors.isDark ? 1 : 0,
      borderTopColor: colors.border,
    },
    submitBtn: {
      backgroundColor: colors.orange[500],
      borderRadius: 16,
      paddingVertical: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    submitBtnDisabled: {
      opacity: 0.45,
    },
    submitText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.white,
      fontSize: 16,
    },
  });
}
