import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'transparent',
    },
    backdrop: {
      ...StyleSheet.absoluteFillObject,
    },
    backBtn: {
      position: 'absolute',
      left: 16,
      zIndex: 30,
      elevation: 30,
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.card,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.navy[900],
      shadowOpacity: 0.12,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 2},
    },
    sheetWrap: {
      width: '100%',
    },
    sheet: {
      backgroundColor: colors.card,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingHorizontal: 20,
      paddingTop: 10,
      overflow: 'hidden',
      shadowColor: colors.navy[900],
      shadowOpacity: 0.14,
      shadowRadius: 18,
      shadowOffset: {width: 0, height: -4},
      elevation: 20,
    },
    sheetScroll: {
      flexGrow: 0,
      flexShrink: 1,
    },
    sheetScrollContent: {
      paddingBottom: 8,
    },
    grabber: {
      alignSelf: 'center',
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.border,
      marginBottom: 14,
    },
    grabberHit: {
      alignItems: 'center',
      paddingTop: 2,
      paddingBottom: 6,
    },
    title: {
      color: colors.text,
      fontSize: 24,
      fontWeight: '800',
      marginBottom: 14,
    },
    routeCard: {
      flexDirection: 'row',
      backgroundColor: colors.surface,
      borderRadius: 18,
      paddingVertical: 14,
      paddingHorizontal: 14,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    timeline: {
      width: 18,
      alignItems: 'center',
      paddingTop: 8,
      paddingBottom: 8,
      marginRight: 10,
    },
    dotPickup: {
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: colors.orange[500],
    },
    timelineLine: {
      flex: 1,
      width: 2,
      backgroundColor: colors.isDark ? colors.navy.cardBg : colors.blue[100],
      marginVertical: 4,
    },
    dotDrop: {
      width: 12,
      height: 12,
      borderRadius: 3,
      backgroundColor: colors.isDark ? colors.white : colors.navy[800],
    },
    fields: {
      flex: 1,
    },
    fieldRow: {
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: 36,
      gap: 8,
    },
    fieldValue: {
      flex: 1,
      color: colors.text,
      fontSize: 15,
      fontWeight: '600',
    },
    fieldInput: {
      flex: 1,
      color: colors.text,
      fontSize: 15,
      fontWeight: '600',
      paddingVertical: 0,
    },
    fieldDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.border,
      marginVertical: 10,
    },
    actions: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 16,
    },
    sameErrorRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: -4,
      marginBottom: 12,
    },
    sameErrorText: {
      flex: 1,
      color: colors.red[500],
      fontSize: 13,
      fontWeight: '600',
    },
    outOfAreaCard: {
      backgroundColor: colors.isDark ? colors.alpha.red18 : colors.red[100],
      borderRadius: 18,
      paddingVertical: 20,
      paddingHorizontal: 18,
      alignItems: 'center',
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.isDark ? colors.alpha.red30 : 'transparent',
    },
    outOfAreaIconWrap: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.card,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 12,
    },
    outOfAreaTitle: {
      color: colors.red[500],
      fontSize: 17,
      fontWeight: '800',
      textAlign: 'center',
      marginBottom: 8,
    },
    outOfAreaBody: {
      color: colors.isDark ? colors.text : colors.red[500],
      fontSize: 13,
      lineHeight: 19,
      textAlign: 'center',
      marginBottom: 16,
    },
    notifyBtn: {
      alignSelf: 'stretch',
      backgroundColor: colors.card,
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: colors.border,
      paddingVertical: 12,
      alignItems: 'center',
    },
    notifyBtnText: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '700',
    },
    actionChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 999,
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
    },
    actionChipText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '600',
    },
    actionChipDisabled: {
      opacity: 0.55,
      borderColor: colors.border,
      backgroundColor: colors.surface,
    },
    actionChipTextDisabled: {
      color: colors.muted,
    },
    sectionTitle: {
      color: colors.muted,
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 1.2,
      marginBottom: 6,
    },
    placeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingVertical: 11,
    },
    placeIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    placeCopy: {
      flex: 1,
    },
    placeTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
    },
    placeSub: {
      color: colors.muted,
      fontSize: 13,
      marginTop: 2,
    },
    emptyText: {
      color: colors.muted,
      fontSize: 14,
      paddingVertical: 16,
    },
    confirmBtn: {
      marginTop: 8,
      borderRadius: 999,
      paddingVertical: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    confirmBtnDisabled: {
      backgroundColor: colors.isDark ? colors.navy.cardBg : colors.gray[200],
    },
    confirmBtnActive: {
      backgroundColor: colors.orange[500],
    },
    confirmText: {
      fontSize: 16,
      fontWeight: '700',
    },
    confirmTextDisabled: {
      color: colors.isDark ? colors.muted : colors.white,
    },
    confirmTextActive: {
      color: colors.white,
    },
  });
}

