import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'transparent',
    },
    backdrop: {
      ...StyleSheet.absoluteFillObject,
    },
    backBtn: {
      position: 'absolute',
      left: 16,
      zIndex: 6,
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.white,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.navy[900],
      shadowOpacity: 0.12,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 2},
      elevation: 4,
    },
    routePreview: {
      position: 'absolute',
      left: 24,
      right: 24,
      top: '12%',
      height: 120,
    },
    routeLine: {
      position: 'absolute',
      left: '8%',
      right: '18%',
      top: 36,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.orange[500],
      transform: [{rotate: '-8deg'}],
    },
    routeDot: {
      position: 'absolute',
      width: 12,
      height: 12,
      borderRadius: 6,
      borderWidth: 2,
      borderColor: colors.white,
    },
    routeDotStart: {
      left: '6%',
      top: 40,
      backgroundColor: colors.orange[500],
    },
    routeDotEnd: {
      right: '14%',
      top: 22,
      backgroundColor: colors.navy[800],
    },
    routePin: {
      position: 'absolute',
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: colors.navy[800],
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: colors.white,
    },
    routePinText: {
      color: colors.white,
      fontSize: 12,
      fontWeight: '800',
    },
    sheet: {
      backgroundColor: colors.white,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingHorizontal: 20,
      paddingTop: 10,
      shadowColor: colors.navy[900],
      shadowOpacity: 0.14,
      shadowRadius: 18,
      shadowOffset: {width: 0, height: -4},
      elevation: 20,
    },
    grabber: {
      alignSelf: 'center',
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.gray[200],
      marginBottom: 14,
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      marginBottom: 14,
      gap: 12,
    },
    headerCopy: {
      flex: 1,
    },
    title: {
      color: colors.navy[900],
      fontSize: 24,
      fontWeight: '800',
    },
    subtitle: {
      color: colors.gray[500],
      fontSize: 13,
      marginTop: 4,
    },
    fareBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.blue[100],
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    fareBadgeDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.blue[500],
    },
    fareBadgeText: {
      color: colors.blue[600],
      fontSize: 12,
      fontWeight: '700',
    },
    list: {
      flexGrow: 0,
      flexShrink: 1,
    },
    listContent: {
      paddingBottom: 8,
      gap: 10,
    },
    stopCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      backgroundColor: colors.gray[100],
      borderRadius: 14,
      paddingVertical: 12,
      paddingHorizontal: 12,
      borderWidth: 1.5,
      borderColor: 'transparent',
    },
    stopCardActive: {
      borderColor: colors.orange[500],
      backgroundColor: colors.white,
    },
    dragHandle: {
      paddingRight: 2,
    },
    stopDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
    },
    stopDotPickup: {
      backgroundColor: colors.orange[500],
    },
    stopDotNavy: {
      backgroundColor: colors.navy[800],
    },
    stopCopy: {
      flex: 1,
    },
    stopLabel: {
      color: colors.gray[500],
      fontSize: 12,
      fontWeight: '600',
    },
    stopAddress: {
      color: colors.navy[900],
      fontSize: 14,
      fontWeight: '700',
      marginTop: 2,
    },
    xSpacer: {
      width: 18,
    },
    addStopBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderWidth: 1.5,
      borderStyle: 'dashed',
      borderColor: colors.orange[500],
      borderRadius: 14,
      paddingVertical: 14,
      marginTop: 2,
    },
    addStopText: {
      color: colors.orange[600],
      fontSize: 14,
      fontWeight: '700',
    },
    maxStopsHint: {
      color: colors.gray[500],
      fontSize: 12,
      textAlign: 'center',
      paddingVertical: 8,
    },
    footer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingTop: 12,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.gray[200],
    },
    fareCopy: {
      flex: 1,
    },
    fareLabel: {
      color: colors.gray[500],
      fontSize: 12,
      fontWeight: '600',
    },
    fareValue: {
      color: colors.navy[900],
      fontSize: 28,
      fontWeight: '800',
      marginTop: 2,
    },
    fareHint: {
      color: colors.gray[500],
      fontSize: 11,
      marginTop: 2,
      lineHeight: 15,
    },
    confirmBtn: {
      backgroundColor: colors.orange[500],
      borderRadius: 16,
      paddingHorizontal: 22,
      paddingVertical: 16,
      minWidth: 110,
      alignItems: 'center',
    },
    confirmText: {
      color: colors.white,
      fontSize: 16,
      fontWeight: '800',
    },
  });
}
