import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingBottom: 12,
      backgroundColor: colors.card,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      color: colors.text,
      fontSize: 18,
      fontWeight: '700',
    },
    scroll: {
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    rideCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
      marginBottom: 14,
    },
    rideTop: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
    },
    rideIcon: {
      marginRight: 12,
    },
    rideInfo: {
      flex: 1,
    },
    rideTitle: {
      color: colors.text,
      fontSize: 14.5,
      fontWeight: '700',
      marginBottom: 2,
    },
    rideSub: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '400',
    },
    driverRow: {
      flexDirection: 'row',
      alignItems: 'center',
      borderTopWidth: 1,
      borderTopColor: colors.border,
      paddingTop: 10,
    },
    driverAvatar: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: '#FEE6D6',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
    driverAvatarText: {
      color: '#C2410C',
      fontSize: 11.5,
      fontWeight: '700',
    },
    driverName: {
      color: colors.text,
      fontSize: 12.5,
      fontWeight: '500',
    },
    seriousCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
      marginBottom: 14,
    },
    seriousTitle: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 12,
    },
    seriousRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    seriousChip: {
      flex: 1,
      backgroundColor: colors.inputBg,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    seriousChipSelected: {
      backgroundColor: colors.isDark ? 'rgba(255, 112, 6, 0.22)' : '#FFF5ED',
      borderColor: colors.primary,
      borderWidth: 1.5,
    },
    seriousChipText: {
      color: colors.text,
      fontSize: 12.5,
      fontWeight: '500',
    },
    seriousChipTextSelected: {
      color: colors.primary,
      fontWeight: '700',
    },
    sectionLabel: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.8,
      marginBottom: 8,
    },
    categoriesGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: 10,
      marginBottom: 14,
    },
    categoryCard: {
      width: '48.5%',
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.card,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 12,
      paddingHorizontal: 12,
      minHeight: 46,
    },
    categoryCardSelected: {
      backgroundColor: colors.isDark ? 'rgba(255, 112, 6, 0.22)' : '#FFF5ED',
      borderColor: colors.primary,
      borderWidth: 1.5,
    },
    categoryIcon: {
      marginRight: 8,
    },
    categoryText: {
      color: colors.text,
      fontSize: 12.5,
      fontWeight: '500',
      flex: 1,
    },
    categoryTextSelected: {
      fontWeight: '700',
      color: colors.text,
    },
    textCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
      marginBottom: 12,
      minHeight: 80,
    },
    textInput: {
      color: colors.text,
      fontSize: 12.5,
      lineHeight: 18,
      padding: 0,
      margin: 0,
      textAlignVertical: 'top',
    },
    attachBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderWidth: 1.5,
      borderStyle: 'dashed',
      borderColor: colors.border,
      borderRadius: 16,
      backgroundColor: colors.card,
      height: 48,
      marginBottom: 14,
    },
    attachBtnText: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '600',
    },
    whatNextCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
      marginBottom: 14,
    },
    whatNextTitle: {
      color: colors.text,
      fontSize: 13.5,
      fontWeight: '700',
      marginBottom: 10,
    },
    whatNextRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 8,
    },
    whatNextRowLast: {
      marginBottom: 0,
    },
    whatNextText: {
      flex: 1,
      color: colors.text,
      fontSize: 12,
      fontWeight: '400',
    },
    footer: {
      paddingHorizontal: 16,
      paddingTop: 10,
      backgroundColor: colors.card,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    submitBtn: {
      backgroundColor: colors.primary,
      borderRadius: 16,
      height: 52,
      alignItems: 'center',
      justifyContent: 'center',
    },
    submitText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '700',
    },
  });
}
