import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: '#F3F6FA',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingBottom: 12,
      backgroundColor: '#FFFFFF',
    },
    headerBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      color: '#0F2840',
      fontSize: 18,
      fontWeight: '700',
    },
    scroll: {
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    rideCard: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#E8ECF2',
      padding: 14,
      marginBottom: 14,
    },
    rideTop: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
    },
    rideIcon: {
      marginRight: 12,
    },
    rideInfo: {
      flex: 1,
    },
    rideTitle: {
      color: '#0F2840',
      fontSize: 14.5,
      fontWeight: '700',
      marginBottom: 2,
    },
    rideSub: {
      color: '#6E7C91',
      fontSize: 12,
      fontWeight: '400',
    },
    driverRow: {
      flexDirection: 'row',
      alignItems: 'center',
      borderTopWidth: 1,
      borderTopColor: '#F0F3F7',
      paddingTop: 10,
    },
    driverAvatar: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: '#FEE6D6',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
    driverAvatarText: {
      color: '#C2410C',
      fontSize: 11.5,
      fontWeight: '700',
    },
    driverName: {
      color: '#0F2840',
      fontSize: 12.5,
      fontWeight: '500',
    },
    seriousCard: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#E8ECF2',
      padding: 14,
      marginBottom: 14,
    },
    seriousTitle: {
      color: '#0F2840',
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 12,
    },
    seriousRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    seriousChip: {
      flex: 1,
      backgroundColor: '#F8FAFC',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#E2E8F0',
      paddingVertical: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    seriousChipSelected: {
      backgroundColor: '#FFF5ED',
      borderColor: '#FF7006',
      borderWidth: 1.5,
    },
    seriousChipText: {
      color: '#0F2840',
      fontSize: 12.5,
      fontWeight: '500',
    },
    seriousChipTextSelected: {
      color: '#B45309',
      fontWeight: '700',
    },
    sectionLabel: {
      color: '#7E8B9E',
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.8,
      marginBottom: 8,
    },
    categoriesGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: 10,
      marginBottom: 14,
    },
    categoryCard: {
      width: '48.5%',
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      borderRadius: 14,
      borderWidth: 1,
      borderColor: '#E8ECF2',
      paddingVertical: 12,
      paddingHorizontal: 12,
      minHeight: 46,
    },
    categoryCardSelected: {
      backgroundColor: '#FFF5ED',
      borderColor: '#FF7006',
      borderWidth: 1.5,
    },
    categoryIcon: {
      marginRight: 8,
    },
    categoryText: {
      color: '#0F2840',
      fontSize: 12.5,
      fontWeight: '500',
      flex: 1,
    },
    categoryTextSelected: {
      fontWeight: '700',
      color: '#0F2840',
    },
    textCard: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#E8ECF2',
      padding: 14,
      marginBottom: 12,
      minHeight: 80,
    },
    textInput: {
      color: '#0F2840',
      fontSize: 12.5,
      lineHeight: 18,
      padding: 0,
      margin: 0,
      textAlignVertical: 'top',
    },
    attachBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderWidth: 1.5,
      borderStyle: 'dashed',
      borderColor: '#D3DAE4',
      borderRadius: 16,
      backgroundColor: '#FFFFFF',
      height: 48,
      marginBottom: 14,
    },
    attachBtnText: {
      color: '#6E7C91',
      fontSize: 13,
      fontWeight: '600',
    },
    whatNextCard: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#E8ECF2',
      padding: 14,
      marginBottom: 14,
    },
    whatNextTitle: {
      color: '#0F2840',
      fontSize: 13.5,
      fontWeight: '700',
      marginBottom: 10,
    },
    whatNextRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 8,
    },
    whatNextRowLast: {
      marginBottom: 0,
    },
    whatNextText: {
      flex: 1,
      color: '#0F2840',
      fontSize: 12,
      fontWeight: '400',
    },
    footer: {
      paddingHorizontal: 16,
      paddingTop: 10,
      backgroundColor: '#FFFFFF',
      borderTopWidth: 1,
      borderTopColor: '#F0F3F7',
    },
    submitBtn: {
      backgroundColor: '#FF7006',
      borderRadius: 16,
      height: 52,
      alignItems: 'center',
      justifyContent: 'center',
    },
    submitText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '700',
    },
  });
}
