import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.map.land,
    },
    mapImage: {
      ...StyleSheet.absoluteFillObject,
      width: '100%',
      height: '100%',
    },
    navBanner: {
      position: 'absolute',
      left: 16,
      right: 16,
      zIndex: 6,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.navy[900],
      borderRadius: 18,
      paddingVertical: 12,
      paddingHorizontal: 12,
      gap: 10,
    },
    navLeft: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      minWidth: 0,
    },
    turnIcon: {
      width: 36,
      height: 36,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    turnArrowImage: {
      width: 28,
      height: 28,
    },
    navCopy: {
      flex: 1,
      minWidth: 0,
    },
    navTitle: {
      color: colors.white,
      fontSize: 16,
      fontWeight: '800',
      lineHeight: 20,
    },
    navSub: {
      color: 'rgba(255,255,255,0.55)',
      fontSize: 12,
      fontWeight: '500',
      lineHeight: 16,
      marginTop: 3,
    },
    navRight: {
      alignItems: 'flex-end',
      justifyContent: 'center',
    },
    navEta: {
      color: colors.orange[450],
      fontSize: 15,
      fontWeight: '600',
      lineHeight: 20,
    },
    navDist: {
      color: 'rgba(255,255,255,0.55)',
      fontSize: 12,
      fontWeight: '500',
      lineHeight: 16,
      marginTop: 3,
    },
    mapRoute: {
      position: 'absolute',
      left: 0,
      right: 0,
      alignItems: 'center',
      zIndex: 2,
    },
    routeStage: {
      position: 'relative',
    },
    pickupZone: {
      position: 'absolute',
      right: '8%',
      top: '18%',
      width: 110,
      height: 110,
      borderRadius: 55,
      backgroundColor: 'rgba(38, 168, 94, 0.18)',
      borderWidth: 2,
      borderColor: 'rgba(38, 168, 94, 0.55)',
      borderStyle: 'dashed',
    },
    routeLine: {
      position: 'absolute',
      left: '18%',
      right: '28%',
      top: '48%',
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.orange[600],
      transform: [{rotate: '-18deg'}],
    },
    carMarker: {
      position: 'absolute',
      left: '14%',
      top: '42%',
      width: 48,
      height: 48,
      zIndex: 3,
    },
    pickupPin: {
      position: 'absolute',
      right: '18%',
      top: '28%',
      width: 42,
      height: 52,
      zIndex: 4,
    },
    fabs: {
      position: 'absolute',
      right: 16,
      zIndex: 5,
      gap: 10,
    },
    fab: {
      width: 46,
      height: 46,
      borderRadius: 23,
      backgroundColor: colors.white,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.navy[900],
      shadowOpacity: 0.14,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 3},
      elevation: 4,
    },
    sheet: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: colors.white,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingTop: 14,
      paddingHorizontal: 16,
      zIndex: 8,
      shadowColor: colors.navy[900],
      shadowOpacity: 0.14,
      shadowRadius: 16,
      shadowOffset: {width: 0, height: -4},
      elevation: 14,
    },
    statusBanner: {
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.green[100],
      borderRadius: 999,
      paddingVertical: 8,
      paddingHorizontal: 12,
      marginBottom: 14,
    },
    statusText: {
      color: colors.green[600],
      fontSize: 13,
      fontWeight: '700',
    },
    riderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginBottom: 14,
    },
    avatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.navy[800],
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarText: {
      color: colors.white,
      fontSize: 14,
      fontWeight: '800',
    },
    riderCopy: {
      flex: 1,
      minWidth: 0,
    },
    riderName: {
      color: colors.navy[900],
      fontSize: 16,
      fontWeight: '800',
    },
    riderMeta: {
      color: colors.navy[400],
      fontSize: 13,
      marginTop: 3,
    },
    pickupBox: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      backgroundColor: colors.navy[50],
      borderRadius: 16,
      paddingVertical: 12,
      paddingHorizontal: 12,
      marginBottom: 12,
    },
    pickupCopy: {
      flex: 1,
      minWidth: 0,
    },
    pickupTitle: {
      color: colors.navy[900],
      fontSize: 15,
      fontWeight: '800',
    },
    pickupNote: {
      color: colors.navy[500],
      fontSize: 13,
      fontStyle: 'italic',
      marginTop: 4,
      lineHeight: 18,
    },
    actionRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 14,
    },
    actionBtn: {
      flex: 1,
      minHeight: 46,
      borderRadius: 14,
      backgroundColor: colors.navy[50],
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    actionText: {
      color: colors.navy[800],
      fontSize: 13,
      fontWeight: '700',
    },
    cancelActionBtn: {
      backgroundColor: colors.red[100],
    },
    cancelIcon: {
      width: 18,
      height: 18,
      borderRadius: 9,
      borderWidth: 1.5,
      borderColor: colors.red[700],
      alignItems: 'center',
      justifyContent: 'center',
    },
    cancelActionText: {
      color: colors.red[700],
      fontSize: 13,
      fontWeight: '700',
    },
    arriveBtn: {
      minHeight: 56,
      borderRadius: 16,
      backgroundColor: colors.orange[450],
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      borderWidth: 2,
      borderColor: colors.green[500],
      shadowColor: colors.green[500],
      shadowOpacity: 0.35,
      shadowRadius: 10,
      shadowOffset: {width: 0, height: 4},
      elevation: 6,
      marginBottom: 10,
    },
    arriveText: {
      color: colors.white,
      fontSize: 16,
      fontWeight: '800',
    },
    footerHint: {
      color: colors.navy[400],
      fontSize: 11,
      lineHeight: 15,
      textAlign: 'center',
    },
  });
}
