import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.map.land,
    },
    mapImage: {
      ...StyleSheet.absoluteFillObject,
      width: '100%',
      height: '100%',
    },

    // Top Navigation & SOS row
    topBar: {
      position: 'absolute',
      left: 16,
      right: 16,
      zIndex: 6,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    navBanner: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.navy[850],
      borderRadius: 18,
      paddingVertical: 12,
      paddingHorizontal: 14,
      gap: 12,
      shadowColor: colors.black,
      shadowOpacity: 0.2,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 4},
      elevation: 6,
    },
    turnIconContainer: {
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
    },
    navCopy: {
      flex: 1,
      minWidth: 0,
    },
    navTitle: {
      color: colors.white,
      fontSize: 15,
      fontWeight: '800',
      lineHeight: 19,
    },
    navSub: {
      color: colors.alpha.white65,
      fontSize: 12,
      fontWeight: '500',
      lineHeight: 16,
      marginTop: 2,
    },

    sosBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.white,
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 20,
      borderWidth: 1.5,
      borderColor: colors.red[350],
      shadowColor: colors.black,
      shadowOpacity: 0.12,
      shadowRadius: 6,
      shadowOffset: {width: 0, height: 2},
      elevation: 4,
    },
    sosText: {
      color: colors.red[600],
      fontSize: 14,
      fontWeight: '800',
    },

    // Floating Map Actions
    crosshairFab: {
      position: 'absolute',
      right: 16,
      zIndex: 5,
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.white,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.black,
      shadowOpacity: 0.15,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 3},
      elevation: 5,
    },

    // Map Route elements
    mapRouteContainer: {
      position: 'absolute',
      left: 0,
      right: 0,
      alignItems: 'center',
      zIndex: 2,
    },
    routeStage: {
      position: 'relative',
    },
    dropZone: {
      position: 'absolute',
      right: '12%',
      top: '10%',
      width: 120,
      height: 120,
      borderRadius: 60,
      backgroundColor: colors.alpha.green12,
      borderWidth: 1.5,
      borderColor: colors.alpha.green55,
      borderStyle: 'dashed',
    },
    dropPinContainer: {
      position: 'absolute',
      right: '25%',
      top: '20%',
      zIndex: 4,
      alignItems: 'center',
    },
    dropPin: {
      width: 40,
      height: 50,
    },
    routeCurve: {
      position: 'absolute',
      left: '42%',
      right: '26%',
      top: '38%',
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.orange[650],
      transform: [{rotate: '-42deg'}],
    },
    carMarkerBadge: {
      position: 'absolute',
      left: '38%',
      top: '55%',
      zIndex: 5,
      backgroundColor: colors.orange[650],
      width: 44,
      height: 44,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.orange[650],
      shadowOpacity: 0.4,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 4},
      elevation: 6,
    },

    // Bottom Sheet
    sheet: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: colors.white,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingTop: 10,
      paddingHorizontal: 16,
      zIndex: 8,
      shadowColor: colors.navy[850],
      shadowOpacity: 0.16,
      shadowRadius: 20,
      shadowOffset: {width: 0, height: -6},
      elevation: 16,
    },

    dragHandleWrapper: {
      alignItems: 'center',
      paddingVertical: 4,
      marginBottom: 10,
    },
    dragHandleBar: {
      width: 44,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.slate[300],
    },

    // Destination Row
    destRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 14,
    },
    onTripBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.orange[100],
      borderRadius: 16,
      paddingVertical: 4,
      paddingHorizontal: 10,
    },
    onTripDot: {
      width: 7,
      height: 7,
      borderRadius: 3.5,
      backgroundColor: colors.primary,
    },
    onTripText: {
      color: colors.orange[700],
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 0.5,
    },
    destTitle: {
      flex: 1,
      color: colors.slate[900],
      fontSize: 15.5,
      fontWeight: '800',
    },

    // Progress Bar
    progressBarTrack: {
      height: 6,
      backgroundColor: colors.slate[200],
      borderRadius: 3,
      overflow: 'hidden',
      marginBottom: 16,
    },
    progressBarFill: {
      width: '78%',
      height: '100%',
      backgroundColor: colors.primary,
      borderRadius: 3,
    },

    // Stats Row (Arriving, Left, Running Fare)
    statsContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.slate[50],
      borderRadius: 16,
      paddingVertical: 14,
      paddingHorizontal: 8,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: colors.slate[100],
    },
    statCol: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    statDivider: {
      width: 1,
      height: 32,
      backgroundColor: colors.slate[200],
    },
    statLabel: {
      color: colors.slate[400],
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
      marginBottom: 4,
    },
    statValue: {
      color: colors.slate[900],
      fontSize: 18,
      fontWeight: '800',
    },
    statValueOrange: {
      color: colors.primary,
      fontSize: 19,
      fontWeight: '800',
    },

    // Rider Row & Action Icons
    riderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 16,
    },
    riderInfoLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      flex: 1,
      minWidth: 0,
    },
    avatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.navy[850],
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarText: {
      color: colors.white,
      fontSize: 14,
      fontWeight: '800',
    },
    riderDetails: {
      flex: 1,
      minWidth: 0,
    },
    riderName: {
      color: colors.slate[900],
      fontSize: 15,
      fontWeight: '800',
    },
    riderSub: {
      color: colors.slate[500],
      fontSize: 12.5,
      fontWeight: '500',
      marginTop: 2,
      lineHeight: 16,
    },
    actionIconGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginLeft: 8,
    },
    roundActionBtn: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: colors.slate[100],
      alignItems: 'center',
      justifyContent: 'center',
    },

    // Proximity Banner
    proximityBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.green[150],
      borderRadius: 20,
      paddingVertical: 10,
      paddingHorizontal: 16,
      marginBottom: 16,
    },
    proximityText: {
      color: colors.green[700],
      fontSize: 13.5,
      fontWeight: '700',
    },

    // End Trip Button (with vibrant orange background & green border outline matching design)
    endTripBtn: {
      minHeight: 56,
      borderRadius: 18,
      backgroundColor: colors.primary,
      borderWidth: 2,
      borderColor: colors.green[600],
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      shadowColor: colors.green[600],
      shadowOpacity: 0.3,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 4},
      elevation: 6,
      marginBottom: 8,
    },
    endTripText: {
      color: colors.white,
      fontSize: 16.5,
      fontWeight: '800',
    },

    homeIndicator: {
      width: 134,
      height: 5,
      borderRadius: 2.5,
      backgroundColor: colors.slate[400],
      alignSelf: 'center',
      marginTop: 6,
    },
  });
}
