import { StyleSheet } from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: '#FFFFFF',
    },
    scrollContent: {
      flexGrow: 1,
      paddingBottom: 24,
    },

    // Top Peach/Orange Hero Area
    heroArea: {
      position: 'relative',
      backgroundColor: '#FFF3EA',
      borderBottomLeftRadius: 32,
      borderBottomRightRadius: 32,
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingBottom: 28,
      overflow: 'hidden',
    },
    heroCircleBg: {
      position: 'absolute',
      top: -120,
      width: 320,
      height: 320,
      borderRadius: 160,
      backgroundColor: 'rgba(255, 112, 5, 0.1)',
    },
    rupeeBadge: {
      width: 52,
      height: 52,
      borderRadius: 26,
      alignItems: 'center',
      justifyContent: 'center',
      // marginBottom: 14,
      marginTop: 6,
      zIndex: 2,
    },
    rupeeSymbol: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 24,
      fontWeight: '800',
      color: '#C2410C',
    },
    heroTitle: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 28,
      fontWeight: '800',
      color: '#431407',
      marginBottom: 8,
      textAlign: 'center',
      zIndex: 2,
    },
    heroSub: {
      fontFamily: colors.fonts.sora.semiBold,
      fontSize: 14,
      fontWeight: '600',
      color: '#C2410C',
      textAlign: 'center',
      lineHeight: 20,
      paddingHorizontal: 16,
      zIndex: 2,
    },

    // Trip route brief pill
    tripPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      backgroundColor: '#F1F5F9',
      borderRadius: 14,
      paddingVertical: 11,
      paddingHorizontal: 14,
      marginHorizontal: 16,
      marginTop: 16,
    },
    tripPillText: {
      fontFamily: colors.fonts.sora.semiBold,
      flex: 1,
      fontSize: 13,
      fontWeight: '600',
      color: '#334155',
    },

    // Passenger Pays Card
    card: {
      backgroundColor: '#FFFFFF',
      borderRadius: 18,
      borderWidth: 1,
      borderColor: '#E2E8F0',
      padding: 16,
      marginHorizontal: 16,
      marginTop: 12,
    },
    cardHeader: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 11,
      fontWeight: '700',
      color: '#94A3B8',
      letterSpacing: 0.6,
      textTransform: 'uppercase',
      marginBottom: 12,
    },
    cardRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 10,
    },
    cardRowLabel: {
      fontFamily: colors.fonts.sora.medium,
      fontSize: 14,
      fontWeight: '500',
      color: '#475569',
    },
    cardRowValue: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 15,
      fontWeight: '700',
      color: '#0F172A',
    },
    promoLabel: {
      fontFamily: colors.fonts.sora.semiBold,
      fontSize: 14,
      fontWeight: '600',
      color: '#16A34A',
    },
    promoValue: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 15,
      fontWeight: '700',
      color: '#16A34A',
    },
    cardDivider: {
      height: 1,
      backgroundColor: '#F1F5F9',
      marginVertical: 6,
    },
    totalLabel: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 15,
      fontWeight: '800',
      color: '#0F172A',
    },
    totalValue: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 18,
      fontWeight: '800',
      color: '#0F172A',
    },

    // Your Earning Card (Navy)
    earningCard: {
      backgroundColor: '#0F1E36',
      borderRadius: 18,
      padding: 16,
      marginHorizontal: 16,
      marginTop: 12,
    },
    earningHeader: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 11,
      fontWeight: '700',
      color: '#94A8C2',
      letterSpacing: 0.6,
      textTransform: 'uppercase',
      marginBottom: 12,
    },
    earningLabel: {
      fontFamily: colors.fonts.sora.medium,
      fontSize: 14,
      fontWeight: '500',
      color: 'rgba(255, 255, 255, 0.75)',
    },
    earningValue: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 15,
      fontWeight: '700',
      color: '#FFFFFF',
    },
    deductedValue: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 15,
      fontWeight: '700',
      color: '#FFB077',
    },
    earningDivider: {
      height: 1,
      backgroundColor: 'rgba(255, 255, 255, 0.12)',
      marginVertical: 8,
    },
    keepLabel: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 16,
      fontWeight: '800',
      color: '#FFFFFF',
    },
    keepValue: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 22,
      fontWeight: '800',
      color: '#34D399',
    },

    // Fixed Bottom Action Section with top border and shadow
    actionSection: {
      backgroundColor: '#FFFFFF',
      borderTopWidth: 1,
      borderTopColor: '#EEF2F6',
      paddingHorizontal: 16,
      paddingTop: 14,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.08,
      shadowRadius: 10,
      elevation: 10,
    },
    completeBtn: {
      minHeight: 54,
      borderRadius: 16,
      backgroundColor: '#FF7006',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      shadowColor: '#FF7006',
      shadowOpacity: 0.3,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 6,
      marginBottom: 12,
    },
    completeBtnText: {
      fontFamily: colors.fonts.sora.extraBold,
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '800',
    },
    btnRupee: {
      fontFamily: colors.fonts.sora.extraBold,
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '800',
    },
    secondaryLink: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 4,
      marginBottom: 4,
    },
    secondaryLinkText: {
      fontFamily: colors.fonts.sora.semiBold,
      color: '#64748B',
      fontSize: 14,
      fontWeight: '600',
    },
  });
}
