import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 12,
      paddingBottom: 10,
      backgroundColor: colors.card,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      fontFamily: colors.fonts.sora.bold,
      flex: 1,
      textAlign: 'center',
      color: colors.text,
      fontSize: 17,
    },
    scroll: {
      paddingHorizontal: 20,
      paddingTop: 12,
    },
    tripToggle: {
      flexDirection: 'row',
      backgroundColor: colors.isDark ? colors.surface : colors.gray[100],
      borderRadius: 14,
      padding: 4,
      marginBottom: 16,
      borderWidth: colors.isDark ? 1 : 0,
      borderColor: colors.border,
    },
    tripTab: {
      flex: 1,
      paddingVertical: 11,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tripTabActive: {
      backgroundColor: colors.isDark ? colors.cardHighlight : colors.white,
      shadowColor: colors.isDark ? colors.black : colors.navy[900],
      shadowOpacity: 0.06,
      shadowRadius: 6,
      shadowOffset: {width: 0, height: 1},
      elevation: 2,
    },
    tripTabText: {
      fontFamily: colors.fonts.sora.semiBold,
      color: colors.textMuted,
      fontSize: 14,
    },
    tripTabTextActive: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
    },
    section: {
      marginBottom: 18,
    },
    sectionLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.textMuted,
      fontSize: 11,
      letterSpacing: 1.1,
      marginBottom: 10,
    },
    routeCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 14,
      paddingHorizontal: 14,
      marginBottom: 18,
      gap: 8,
    },
    routeTimeline: {
      width: 14,
      alignItems: 'center',
      marginRight: 4,
    },
    routeDotStart: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.primary,
    },
    routeLine: {
      width: 2,
      flex: 1,
      minHeight: 28,
      backgroundColor: colors.isDark ? colors.navy[700] : colors.gray[300],
      marginVertical: 4,
    },
    routeDotEnd: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.isDark ? colors.white : colors.navy[800],
    },
    routeCopy: {
      flex: 1,
      minWidth: 0,
      gap: 14,
    },
    routeCity: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 15,
    },
    routeMeta: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.textMuted,
      fontSize: 12,
      marginTop: 2,
    },
    swapBtn: {
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
    },
    datesCard: {
      flexDirection: 'row',
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: 'hidden',
    },
    dateCol: {
      flex: 1,
      padding: 14,
    },
    dateDivider: {
      width: 1,
      backgroundColor: colors.border,
    },
    dateLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.textMuted,
      fontSize: 10,
      letterSpacing: 1,
      marginBottom: 6,
    },
    dateValue: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 13,
      lineHeight: 18,
    },
    editText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.primary,
      fontSize: 13,
      marginTop: 8,
    },
    vehicleScroll: {
      paddingRight: 8,
      gap: 8,
    },
    vehicleCard: {
      width: 108,
      backgroundColor: colors.card,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: colors.border,
      padding: 10,
    },
    vehicleCardActive: {
      backgroundColor: colors.isDark ? colors.alpha.orange18 : colors.orange[50],
      borderColor: colors.primary,
    },
    vehicleName: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 13,
      marginTop: 6,
    },
    vehiclePrice: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 14,
      marginTop: 1,
    },
    vehiclePriceActive: {
      color: colors.primary,
    },
    vehicleMeta: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.textMuted,
      fontSize: 10,
      marginTop: 1,
    },
    fareCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
    },
    fareRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 12,
      marginBottom: 10,
    },
    fareRowLast: {
      marginBottom: 0,
    },
    fareLabel: {
      fontFamily: colors.fonts.sora.regular,
      flex: 1,
      color: colors.textMuted,
      fontSize: 13,
      lineHeight: 18,
    },
    fareAmount: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 13,
    },
    footer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      paddingHorizontal: 20,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      backgroundColor: colors.card,
    },
    footerCopy: {
      flex: 1,
      minWidth: 0,
    },
    footerTrip: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.textMuted,
      fontSize: 12,
    },
    footerPrice: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 26,
      marginTop: 2,
      letterSpacing: -0.4,
    },
    footerNote: {
      fontFamily: colors.fonts.sora.semiBold,
      color: colors.isDark ? colors.green[400] : colors.green[600],
      fontSize: 11,
      marginTop: 2,
    },
    bookBtn: {
      backgroundColor: colors.primary,
      paddingVertical: 14,
      paddingHorizontal: 36,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    bookText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.white,
      fontSize: 16,
    },
  });
}
