import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.white,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 12,
      paddingBottom: 10,
    },
    headerBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      color: colors.navy[900],
      fontSize: 17,
      fontWeight: '700',
    },
    scroll: {
      paddingHorizontal: 20,
      paddingTop: 4,
    },
    tripToggle: {
      flexDirection: 'row',
      backgroundColor: colors.gray[100],
      borderRadius: 14,
      padding: 4,
      marginBottom: 16,
    },
    tripTab: {
      flex: 1,
      paddingVertical: 11,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tripTabActive: {
      backgroundColor: colors.white,
      shadowColor: colors.navy[900],
      shadowOpacity: 0.06,
      shadowRadius: 6,
      shadowOffset: {width: 0, height: 1},
      elevation: 2,
    },
    tripTabText: {
      color: colors.gray[500],
      fontSize: 14,
      fontWeight: '600',
    },
    tripTabTextActive: {
      color: colors.navy[900],
      fontWeight: '700',
    },
    section: {
      marginBottom: 18,
    },
    sectionLabel: {
      color: colors.gray[500],
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1.1,
      marginBottom: 10,
    },
    routeCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.white,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.gray[200],
      paddingVertical: 14,
      paddingHorizontal: 14,
      marginBottom: 18,
      gap: 8,
    },
    routeTimeline: {
      width: 14,
      alignItems: 'center',
      marginRight: 4,
    },
    routeDotStart: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.orange[500],
    },
    routeLine: {
      width: 2,
      flex: 1,
      minHeight: 28,
      backgroundColor: colors.gray[300],
      marginVertical: 4,
    },
    routeDotEnd: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.navy[800],
    },
    routeCopy: {
      flex: 1,
      minWidth: 0,
      gap: 14,
    },
    routeCity: {
      color: colors.navy[900],
      fontSize: 15,
      fontWeight: '700',
    },
    routeMeta: {
      color: colors.gray[500],
      fontSize: 12,
      fontWeight: '400',
      marginTop: 2,
    },
    swapBtn: {
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
    },
    datesCard: {
      flexDirection: 'row',
      backgroundColor: colors.white,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.gray[200],
      overflow: 'hidden',
    },
    dateCol: {
      flex: 1,
      padding: 14,
    },
    dateDivider: {
      width: StyleSheet.hairlineWidth,
      backgroundColor: colors.gray[200],
    },
    dateLabel: {
      color: colors.gray[500],
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 1,
      marginBottom: 6,
    },
    dateValue: {
      color: colors.navy[900],
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 18,
    },
    editText: {
      color: colors.orange[600],
      fontSize: 13,
      fontWeight: '700',
      marginTop: 8,
    },
    vehicleScroll: {
      paddingRight: 8,
      gap: 8,
    },
    vehicleCard: {
      width: 108,
      backgroundColor: colors.white,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: colors.gray[200],
      padding: 10,
    },
    vehicleCardActive: {
      backgroundColor: colors.orange[50],
      borderColor: colors.orange[500],
    },
    vehicleName: {
      color: colors.navy[900],
      fontSize: 13,
      fontWeight: '700',
      marginTop: 6,
    },
    vehiclePrice: {
      color: colors.navy[900],
      fontSize: 14,
      fontWeight: '800',
      marginTop: 1,
    },
    vehicleMeta: {
      color: colors.gray[500],
      fontSize: 10,
      fontWeight: '400',
      marginTop: 1,
    },
    fareCard: {
      backgroundColor: colors.white,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.gray[200],
      padding: 14,
    },
    fareRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 12,
      marginBottom: 10,
    },
    fareRowLast: {
      marginBottom: 0,
    },
    fareLabel: {
      flex: 1,
      color: colors.gray[500],
      fontSize: 13,
      fontWeight: '400',
      lineHeight: 18,
    },
    fareAmount: {
      color: colors.navy[900],
      fontSize: 13,
      fontWeight: '700',
    },
    footer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      paddingHorizontal: 20,
      paddingTop: 10,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.gray[200],
      backgroundColor: colors.white,
    },
    footerCopy: {
      flex: 1,
      minWidth: 0,
    },
    footerTrip: {
      color: colors.gray[500],
      fontSize: 12,
      fontWeight: '500',
    },
    footerPrice: {
      color: colors.navy[900],
      fontSize: 26,
      fontWeight: '800',
      marginTop: 2,
      letterSpacing: -0.4,
    },
    footerNote: {
      color: colors.green[600],
      fontSize: 11,
      fontWeight: '600',
      marginTop: 2,
    },
    bookBtn: {
      backgroundColor: colors.orange[500],
      paddingVertical: 14,
      paddingHorizontal: 36,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    bookText: {
      color: colors.white,
      fontSize: 16,
      fontWeight: '700',
    },
  });
}
