import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.gray[50],
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingBottom: 12,
      backgroundColor: colors.white,
    },
    headerBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      color: colors.navy[900],
      fontSize: 17,
      fontWeight: '800',
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: 20,
      paddingTop: 16,
      paddingBottom: 24,
    },
    toggleCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.orange[100],
      borderRadius: 16,
      paddingHorizontal: 14,
      paddingVertical: 14,
      marginBottom: 22,
      gap: 12,
    },
    toggleIcon: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: colors.orange[50],
      alignItems: 'center',
      justifyContent: 'center',
    },
    toggleCopy: {
      flex: 1,
      minWidth: 0,
    },
    toggleTitle: {
      color: colors.navy[900],
      fontSize: 15,
      fontWeight: '800',
      marginBottom: 3,
    },
    toggleSub: {
      color: colors.orange[600],
      fontSize: 13,
      fontWeight: '500',
    },
    sectionLabel: {
      color: colors.gray[500],
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 0.9,
      marginBottom: 10,
    },
    card: {
      backgroundColor: colors.white,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.gray[200],
      paddingHorizontal: 14,
      paddingVertical: 14,
      marginBottom: 18,
    },
    riderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginBottom: 12,
    },
    avatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.blue[100],
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarText: {
      color: colors.navy[800],
      fontSize: 15,
      fontWeight: '800',
    },
    riderCopy: {
      flex: 1,
      minWidth: 0,
    },
    riderName: {
      color: colors.navy[900],
      fontSize: 16,
      fontWeight: '800',
      marginBottom: 2,
    },
    riderPhone: {
      color: colors.gray[500],
      fontSize: 13,
      fontWeight: '500',
    },
    changeText: {
      color: colors.orange[500],
      fontSize: 14,
      fontWeight: '700',
    },
    riderFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.gray[200],
      paddingTop: 12,
    },
    riderFooterText: {
      color: colors.gray[500],
      fontSize: 12,
      fontWeight: '500',
    },
    routeRow: {
      flexDirection: 'row',
      alignItems: 'stretch',
    },
    timeline: {
      width: 14,
      alignItems: 'center',
      marginRight: 12,
      paddingTop: 4,
      paddingBottom: 4,
    },
    pickupDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.orange[500],
    },
    timelineLine: {
      width: 2,
      flex: 1,
      backgroundColor: colors.gray[300],
      marginVertical: 4,
    },
    dropDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.navy[800],
    },
    routeCopy: {
      flex: 1,
      minWidth: 0,
      gap: 14,
    },
    routeTitle: {
      color: colors.navy[900],
      fontSize: 15,
      fontWeight: '800',
      marginBottom: 2,
    },
    routeSub: {
      color: colors.gray[500],
      fontSize: 12,
      fontWeight: '500',
    },
    editBtn: {
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'center',
      marginLeft: 4,
    },
    receivesTitle: {
      color: colors.navy[900],
      fontSize: 16,
      fontWeight: '800',
      marginBottom: 12,
    },
    receiveRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      marginBottom: 10,
    },
    receiveText: {
      flex: 1,
      color: colors.gray[600],
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 20,
    },
    paymentRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    paymentIcon: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: colors.gray[100],
      alignItems: 'center',
      justifyContent: 'center',
    },
    paymentCopy: {
      flex: 1,
      minWidth: 0,
    },
    paymentTitle: {
      color: colors.navy[900],
      fontSize: 15,
      fontWeight: '800',
      marginBottom: 2,
    },
    paymentSub: {
      color: colors.gray[500],
      fontSize: 12,
      fontWeight: '500',
    },
    footer: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingTop: 12,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.gray[200],
      backgroundColor: colors.white,
      gap: 14,
    },
    fareCol: {
      flex: 1,
      minWidth: 0,
    },
    fareLabel: {
      color: colors.gray[500],
      fontSize: 12,
      fontWeight: '600',
      marginBottom: 2,
    },
    fareValue: {
      color: colors.navy[900],
      fontSize: 24,
      fontWeight: '800',
      marginBottom: 2,
    },
    fareNote: {
      color: colors.gray[500],
      fontSize: 11,
      fontWeight: '500',
    },
    bookBtn: {
      backgroundColor: colors.orange[500],
      borderRadius: 14,
      paddingHorizontal: 32,
      paddingVertical: 16,
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 110,
    },
    bookText: {
      color: colors.white,
      fontSize: 16,
      fontWeight: '800',
    },
  });
}
