import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 16,
      backgroundColor: colors.alpha.black55,
    },
    backdrop: {
      ...StyleSheet.absoluteFillObject,
    },
    card: {
      width: '100%',
      maxWidth: 400,
      maxHeight: '86%',
      backgroundColor: colors.card,
      borderRadius: 28,
      paddingTop: 16,
      paddingHorizontal: 16,
      shadowColor: colors.navy[900],
      shadowOpacity: 0.2,
      shadowRadius: 24,
      shadowOffset: {width: 0, height: 10},
      elevation: 24,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      marginBottom: 12,
      paddingHorizontal: 4,
    },
    title: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 22,
      marginBottom: 6,
    },
    metaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    metaItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    metaText: {
      fontFamily: colors.fonts.sora.semiBold,
      color: colors.muted,
      fontSize: 13,
    },
    closeBtn: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sectionLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.muted,
      fontSize: 11,
      letterSpacing: 0.8,
      marginBottom: 10,
      paddingHorizontal: 4,
    },
    list: {
      flexGrow: 0,
      flexShrink: 1,
    },
    listContent: {
      gap: 8,
      paddingBottom: 8,
    },
    rideRow: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: colors.border,
      borderRadius: 14,
      paddingVertical: 12,
      paddingHorizontal: 12,
      backgroundColor: colors.card,
    },
    rideRowActive: {
      borderColor: colors.orange[500],
      borderWidth: 2,
      backgroundColor: colors.isDark ? colors.navy.cardBg : colors.orange.softBg,
    },
    rideIcon: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    rideIconActive: {
      backgroundColor: colors.isDark ? colors.alpha.orange15 : colors.orange[100],
    },
    rideCopy: {
      flex: 1,
      minWidth: 0,
    },
    rideName: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 15,
      marginBottom: 2,
    },
    rideMeta: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    rideMetaText: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.muted,
      fontSize: 12,
    },
    ridePrice: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 16,
      marginLeft: 8,
    },
    bookAnyCard: {
      borderWidth: 2,
      borderColor: colors.orange[500],
      borderRadius: 16,
      padding: 12,
      backgroundColor: colors.isDark ? colors.navy[950] : colors.orange.softBg,
      marginTop: 4,
      marginBottom: 10,
    },
    bookAnyTop: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    bookAnyCopy: {
      flex: 1,
      minWidth: 0,
    },
    bookAnyName: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 15,
      marginBottom: 2,
    },
    bookAnyRange: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 15,
    },
    pills: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 12,
    },
    pill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 10,
      paddingVertical: 7,
      borderRadius: 20,
      borderWidth: 1.5,
      borderColor: colors.border,
      backgroundColor: colors.card,
    },
    pillOn: {
      borderColor: colors.orange[500],
      backgroundColor: colors.isDark ? colors.alpha.orange15 : colors.orange[100],
    },
    pillText: {
      fontFamily: colors.fonts.sora.semiBold,
      color: colors.text,
      fontSize: 12,
    },
    pillTextOn: {
      color: colors.orange[500],
    },
    footer: {
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
      paddingTop: 12,
      paddingBottom: 8,
    },
    payRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    payIcon: {
      width: 32,
      height: 32,
      borderRadius: 10,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
    payText: {
      fontFamily: colors.fonts.sora.semiBold,
      flex: 1,
      color: colors.text,
      fontSize: 14,
    },
    changeText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.orange[500],
      fontSize: 14,
    },
    promoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    promoIcon: {
      width: 32,
      height: 32,
      borderRadius: 10,
      backgroundColor: colors.isDark ? colors.alpha.green15 : colors.green.light,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
    promoText: {
      fontFamily: colors.fonts.sora.semiBold,
      flex: 1,
      color: colors.green[600],
      fontSize: 14,
    },
    promoAmount: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.green[600],
      fontSize: 14,
    },
    bookRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    totalCol: {
      minWidth: 88,
    },
    totalLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.muted,
      fontSize: 11,
      letterSpacing: 0.6,
    },
    totalValue: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 18,
      marginTop: 2,
    },
    bookBtn: {
      flex: 1,
      backgroundColor: colors.orange[500],
      borderRadius: 16,
      paddingVertical: 15,
      alignItems: 'center',
      justifyContent: 'center',
    },
    bookText: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.white,
      fontSize: 15,
    },
  });
}

