import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'transparent',
    },
    backdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: colors.alpha.black28,
    },
    topBar: {
      position: 'absolute',
      left: 16,
      right: 16,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      zIndex: 20,
    },
    backBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.card,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.black,
      shadowOpacity: 0.15,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 2},
      elevation: 5,
    },
    routePill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      backgroundColor: colors.card,
      borderWidth: 1.5,
      borderColor: colors.orange[500],
      borderRadius: 24,
      paddingVertical: 8,
      paddingHorizontal: 14,
      shadowColor: colors.black,
      shadowOpacity: 0.1,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 2},
      elevation: 4,
    },
    routePillText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 13,
    },
    sheet: {
      backgroundColor: colors.card,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingHorizontal: 18,
      paddingTop: 8,
      overflow: 'hidden',
      shadowColor: colors.navy[900],
      shadowOpacity: 0.18,
      shadowRadius: 20,
      shadowOffset: {width: 0, height: -4},
      elevation: 24,
    },
    grabber: {
      alignSelf: 'center',
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.border,
      marginBottom: 10,
    },
    grabberHit: {
      alignItems: 'center',
      paddingTop: 2,
      paddingBottom: 4,
    },
    headerRow: {
      marginBottom: 14,
    },
    title: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 22,
      letterSpacing: -0.3,
    },
    statsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 16,
      marginTop: 4,
    },
    statItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    statText: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.textMuted,
      fontSize: 13,
    },
    sectionLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.textMuted,
      fontSize: 11,
      letterSpacing: 1,
      marginBottom: 10,
    },
    list: {
      flexGrow: 0,
      flexShrink: 1,
    },
    listContent: {
      paddingBottom: 10,
    },

    // Ride Rows
    rideRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: 16,
      paddingVertical: 12,
      paddingHorizontal: 12,
      marginBottom: 10,
      borderWidth: 1.5,
      borderColor: 'transparent',
    },
    rideRowActive: {
      borderColor: colors.orange[500],
      backgroundColor: colors.isDark ? colors.navy.cardBg : '#FFFDFB',
    },
    rideIconBox: {
      width: 42,
      height: 42,
      borderRadius: 12,
      backgroundColor: colors.card,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    rideIconBoxActive: {
      backgroundColor: colors.isDark ? colors.alpha.orange20 : colors.orange[100],
    },
    rideCopy: {
      flex: 1,
      minWidth: 0,
    },
    rideName: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 15,
    },
    rideMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      marginTop: 2,
    },
    rideMetaText: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.textMuted,
      fontSize: 12.5,
    },
    ridePrice: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 16.5,
      marginLeft: 8,
    },

    // Book Any Card
    bookAnyCard: {
      borderWidth: 1.5,
      borderColor: colors.border,
      borderRadius: 18,
      padding: 14,
      backgroundColor: colors.card,
      marginBottom: 10,
    },
    bookAnyCardActive: {
      borderWidth: 2,
      borderColor: colors.orange[500],
      backgroundColor: colors.isDark ? colors.navy.cardBg : '#FFFDFB',
    },
    bookAnyTop: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    bookAnyIconBox: {
      width: 42,
      height: 42,
      borderRadius: 12,
      backgroundColor: colors.isDark ? colors.alpha.orange20 : colors.orange[100],
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    bookAnyCopy: {
      flex: 1,
      minWidth: 0,
    },
    bookAnyTitle: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 15,
    },
    bookAnyMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      marginTop: 2,
    },
    bookAnyMetaSeats: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.textMuted,
      fontSize: 12,
    },
    bookAnyBlurb: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.isDark ? colors.orange[400] : colors.orange[700],
      fontSize: 12,
      marginLeft: 4,
    },
    bookAnyPrice: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.orange[600],
      fontSize: 16,
      marginLeft: 8,
    },

    // Chips Grid (2 columns)
    chipsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 12,
    },
    chipItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      width: '48.5%',
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 20,
      paddingVertical: 7,
      paddingHorizontal: 10,
      backgroundColor: colors.surface,
    },
    chipItemActive: {
      borderColor: colors.orange[500],
      backgroundColor: colors.card,
    },
    chipText: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.textMuted,
      fontSize: 12,
    },
    chipTextActive: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.isDark ? colors.orange[400] : colors.orange[800],
    },

    // Bottom Payment Rows
    metaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    metaRowPromo: {
      borderTopWidth: 0,
      paddingTop: 0,
    },
    metaIcon: {
      width: 32,
      height: 32,
      borderRadius: 8,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
    metaIconPromo: {
      backgroundColor: colors.isDark ? colors.alpha.green15 : colors.green.light,
    },
    metaCopy: {
      flex: 1,
      minWidth: 0,
    },
    metaText: {
      fontFamily: colors.fonts.sora.semiBold,
      color: colors.text,
      fontSize: 14,
    },
    metaTextPromo: {
      color: colors.green[600],
    },
    changeText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.orange[500],
      fontSize: 14,
    },
    removeText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.red[500] || '#EF4444',
      fontSize: 13,
      marginLeft: 8,
    },
    applyText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.orange[500],
      fontSize: 14,
    },
    promoAmount: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.green[600],
      fontSize: 14,
    },
    footer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      paddingTop: 10,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    totalCol: {
      minWidth: 100,
    },
    totalLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.textMuted,
      fontSize: 11,
      letterSpacing: 0.6,
    },
    totalValue: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 18,
      marginTop: 1,
    },
    bookBtn: {
      flex: 1,
      backgroundColor: colors.primary,
      borderRadius: 16,
      height: 52,
      alignItems: 'center',
      justifyContent: 'center',
    },
    bookText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.white,
      fontSize: 16,
    },
  });
}
