import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingBottom: 12,
    },
    headerBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 18,
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: 20,
      paddingBottom: 20,
    },
    routeCard: {
      flexDirection: 'row',
      alignItems: 'stretch',
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 16,
      paddingHorizontal: 14,
      paddingVertical: 14,
      marginBottom: 22,
      backgroundColor: colors.card,
    },
    timeline: {
      width: 14,
      alignItems: 'center',
      marginRight: 12,
      paddingTop: 4,
      paddingBottom: 4,
    },
    pickupDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.orange[500],
    },
    timelineLine: {
      width: 2,
      flex: 1,
      backgroundColor: colors.border,
      marginVertical: 4,
    },
    dropDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.isDark ? colors.white : colors.navy[800],
    },
    routeCopy: {
      flex: 1,
      minWidth: 0,
      gap: 14,
    },
    routeTitle: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 15,
      marginBottom: 2,
    },
    routeSub: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.muted,
      fontSize: 12,
    },
    editBtn: {
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'center',
      marginLeft: 4,
    },
    sectionLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.muted,
      fontSize: 12,
      letterSpacing: 0.9,
      marginBottom: 12,
    },
    monthRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    monthText: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 17,
    },
    monthNav: {
      flexDirection: 'row',
      gap: 8,
    },
    monthNavBtn: {
      width: 32,
      height: 32,
      borderRadius: 10,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    daysRow: {
      flexDirection: 'row',
      gap: 10,
      paddingBottom: 4,
      marginBottom: 22,
    },
    dayCard: {
      width: 58,
      height: 72,
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: colors.border,
      backgroundColor: colors.card,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
    },
    dayCardActive: {
      backgroundColor: colors.orange[500],
      borderColor: colors.orange[500],
    },
    dayName: {
      fontFamily: colors.fonts.sora.semiBold,
      color: colors.muted,
      fontSize: 13,
    },
    dayNameActive: {
      color: colors.white,
    },
    dayNum: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 18,
    },
    dayNumActive: {
      color: colors.white,
    },
    timeHint: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.muted,
      fontSize: 13,
      marginTop: -4,
      marginBottom: 12,
      lineHeight: 18,
    },
    timeGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      marginBottom: 22,
    },
    timeChip: {
      height: 44,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: colors.border,
      backgroundColor: colors.card,
      alignItems: 'center',
      justifyContent: 'center',
    },
    timeChipActive: {
      borderColor: colors.orange[500],
      backgroundColor: colors.isDark ? colors.alpha.orange15 : colors.orange[50],
      borderWidth: 2,
    },
    timeText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 13,
    },
    timeTextActive: {
      color: colors.orange[500],
    },
    vehicleScroll: {
      marginHorizontal: -20,
      paddingHorizontal: 20,
      marginBottom: 18,
    },
    vehicleRow: {
      flexDirection: 'row',
      gap: 12,
      paddingRight: 20,
    },
    vehicleCard: {
      width: 128,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: colors.border,
      backgroundColor: colors.card,
      paddingHorizontal: 12,
      paddingTop: 12,
      paddingBottom: 14,
    },
    vehicleCardActive: {
      borderColor: colors.orange[500],
      backgroundColor: colors.isDark ? colors.alpha.orange15 : colors.orange[50],
      borderWidth: 2,
    },
    vehicleIcon: {
      marginBottom: 10,
    },
    vehicleName: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 15,
      marginBottom: 2,
    },
    vehiclePrice: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 16,
      marginBottom: 4,
    },
    vehicleMeta: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.muted,
      fontSize: 12,
    },
    paymentCard: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 14,
      backgroundColor: colors.card,
      gap: 12,
    },
    paymentIcon: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    paymentCopy: {
      flex: 1,
      minWidth: 0,
    },
    paymentTitle: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 15,
      marginBottom: 2,
    },
    paymentSub: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.muted,
      fontSize: 12,
    },
    changeText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.orange[500],
      fontSize: 14,
    },
    footer: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingTop: 12,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
      backgroundColor: colors.card,
      gap: 14,
    },
    fareCol: {
      flex: 1,
      minWidth: 0,
    },
    fareLabel: {
      fontFamily: colors.fonts.sora.semiBold,
      color: colors.muted,
      fontSize: 12,
      marginBottom: 2,
    },
    fareValue: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 24,
      marginBottom: 2,
    },
    fareNote: {
      fontFamily: colors.fonts.sora.semiBold,
      color: colors.green[600],
      fontSize: 11,
    },
    confirmBtn: {
      backgroundColor: colors.orange[500],
      borderRadius: 14,
      paddingHorizontal: 28,
      paddingVertical: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    confirmText: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.white,
      fontSize: 16,
    },
  });
}

