import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'transparent',
    },
    backdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: colors.alpha.black28,
    },
    topBar: {
      position: 'absolute',
      left: 16,
      right: 16,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      zIndex: 20,
    },
    backBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.card,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.black,
      shadowOpacity: 0.15,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 2},
      elevation: 5,
    },
    routePill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      backgroundColor: colors.card,
      borderWidth: 1.5,
      borderColor: colors.orange[500],
      borderRadius: 24,
      paddingVertical: 8,
      paddingHorizontal: 14,
      shadowColor: colors.black,
      shadowOpacity: 0.1,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 2},
      elevation: 4,
    },
    routePillText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 13,
    },
    sheet: {
      backgroundColor: colors.card,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingHorizontal: 18,
      paddingTop: 8,
      overflow: 'hidden',
      shadowColor: colors.navy[900],
      shadowOpacity: 0.18,
      shadowRadius: 20,
      shadowOffset: {width: 0, height: -4},
      elevation: 24,
    },
    grabber: {
      alignSelf: 'center',
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.border,
      marginBottom: 10,
    },
    grabberHit: {
      alignItems: 'center',
      paddingTop: 2,
      paddingBottom: 4,
    },
    headerRow: {
      marginBottom: 14,
    },
    title: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 22,
      letterSpacing: -0.3,
    },
    subtitle: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.textMuted,
      fontSize: 13.5,
      marginTop: 3,
    },
    list: {
      flexGrow: 0,
      flexShrink: 1,
    },
    listContent: {
      paddingBottom: 10,
    },

    // Featured Pool Card
    poolCard: {
      borderWidth: 1.5,
      borderColor: colors.border,
      borderRadius: 18,
      padding: 14,
      backgroundColor: colors.card,
      marginBottom: 16,
    },
    poolCardActive: {
      borderWidth: 2,
      borderColor: colors.orange[500],
      backgroundColor: colors.isDark ? colors.navy.cardBg : '#FFFDFB',
    },
    poolTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    poolIconBox: {
      width: 46,
      height: 46,
      borderRadius: 14,
      backgroundColor: colors.isDark ? colors.alpha.orange20 : colors.orange[100],
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    poolCopy: {
      flex: 1,
      minWidth: 0,
    },
    poolTitle: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 16,
    },
    poolSub: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.textMuted,
      fontSize: 12.5,
      marginTop: 2,
    },
    poolPriceCol: {
      alignItems: 'flex-end',
      marginLeft: 8,
    },
    poolPrice: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.orange[600],
      fontSize: 20,
    },
    poolSaveText: {
      fontFamily: colors.fonts.sora.semiBold,
      color: colors.green[600],
      fontSize: 12,
      marginTop: 1,
    },
    poolDivider: {
      height: 1,
      backgroundColor: colors.isDark ? colors.border : '#FED7AA',
      marginVertical: 12,
    },
    seatsLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.isDark ? colors.orange[400] : colors.orange[800],
      fontSize: 11,
      letterSpacing: 0.8,
      marginBottom: 8,
    },
    seatsRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    seatChip: {
      paddingHorizontal: 16,
      paddingVertical: 7,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      marginRight: 10,
    },
    seatChipActive: {
      borderWidth: 1.5,
      borderColor: colors.orange[500],
      backgroundColor: colors.card,
    },
    seatChipText: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.textMuted,
      fontSize: 13,
    },
    seatChipTextActive: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
    },
    detourNoteRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginTop: 10,
    },
    detourNoteText: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.isDark ? colors.orange[400] : colors.orange[800],
      fontSize: 12,
      flex: 1,
    },

    // Or Ride Alone section
    sectionLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.textMuted,
      fontSize: 11,
      letterSpacing: 1,
      marginBottom: 10,
    },
    soloCard: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: colors.border,
      borderRadius: 16,
      paddingVertical: 12,
      paddingHorizontal: 12,
      backgroundColor: colors.card,
      marginBottom: 10,
    },
    soloCardActive: {
      borderColor: colors.orange[500],
      borderWidth: 2,
      backgroundColor: colors.isDark ? colors.navy.cardBg : '#FFFDFB',
    },
    soloIconBox: {
      width: 42,
      height: 42,
      borderRadius: 12,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    soloIconBoxActive: {
      backgroundColor: colors.isDark ? colors.alpha.orange20 : colors.orange[100],
    },
    soloCopy: {
      flex: 1,
      minWidth: 0,
    },
    soloTitle: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.text,
      fontSize: 15,
    },
    soloMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginTop: 2,
    },
    soloMeta: {
      fontFamily: colors.fonts.sora.medium,
      color: colors.textMuted,
      fontSize: 12.5,
    },
    soloPrice: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 17,
      marginLeft: 8,
    },

    // Time restriction banner
    infoBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.isDark ? colors.alpha.blue20_59 : '#EFF6FF',
      borderWidth: 1,
      borderColor: colors.isDark ? colors.blue[800] : '#BFDBFE',
      borderRadius: 14,
      paddingVertical: 10,
      paddingHorizontal: 12,
      marginTop: 4,
      marginBottom: 8,
    },
    infoBannerText: {
      fontFamily: colors.fonts.sora.regular,
      color: colors.isDark ? colors.blue[300] : colors.blue[800],
      fontSize: 12.5,
      flex: 1,
    },

    // Bottom Payment Rows
    metaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    metaRowPromo: {
      borderTopWidth: 0,
      paddingTop: 0,
    },
    metaIcon: {
      width: 32,
      height: 32,
      borderRadius: 8,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
    metaIconPromo: {
      backgroundColor: colors.isDark ? colors.alpha.green15 : colors.green.light,
    },
    metaCopy: {
      flex: 1,
      minWidth: 0,
    },
    metaText: {
      fontFamily: colors.fonts.sora.semiBold,
      color: colors.text,
      fontSize: 14,
    },
    metaTextPromo: {
      color: colors.green[600],
    },
    changeText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.orange[500],
      fontSize: 14,
    },
    removeText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.red[500] || '#EF4444',
      fontSize: 13,
      marginLeft: 8,
    },
    applyText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.orange[500],
      fontSize: 14,
    },
    promoAmount: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.green[600],
      fontSize: 14,
    },
    footer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      paddingTop: 10,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    totalCol: {
      minWidth: 80,
    },
    totalLabel: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.textMuted,
      fontSize: 11,
      letterSpacing: 0.6,
    },
    totalValue: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontSize: 22,
      marginTop: 1,
    },
    bookBtn: {
      flex: 1,
      backgroundColor: colors.primary,
      borderRadius: 16,
      height: 52,
      alignItems: 'center',
      justifyContent: 'center',
    },
    bookText: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.white,
      fontSize: 16,
    },
  });
}
