import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'transparent',
    },
    backdrop: {
      ...StyleSheet.absoluteFillObject,
    },
    backBtn: {
      position: 'absolute',
      left: 16,
      zIndex: 6,
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.white,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.navy[900],
      shadowOpacity: 0.12,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 2},
      elevation: 4,
    },
    routeSummary: {
      position: 'absolute',
      alignSelf: 'center',
      zIndex: 5,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 22,
      backgroundColor: colors.white,
      borderWidth: 1.5,
      borderColor: colors.orange[500],
      shadowColor: colors.navy[900],
      shadowOpacity: 0.1,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 2},
      elevation: 4,
      maxWidth: '72%',
    },
    routeSummaryText: {
      color: colors.navy[900],
      fontSize: 13,
      fontWeight: '700',
      flexShrink: 1,
    },
    locateFab: {
      position: 'absolute',
      right: 16,
      zIndex: 5,
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.white,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.navy[900],
      shadowOpacity: 0.12,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 2},
      elevation: 4,
    },
    routePreview: {
      position: 'absolute',
      left: 28,
      right: 40,
      top: '14%',
      height: 140,
    },
    routeLine: {
      position: 'absolute',
      left: '4%',
      right: '10%',
      top: 48,
      height: 5,
      borderRadius: 3,
      backgroundColor: colors.orange[500],
      transform: [{rotate: '-10deg'}],
    },
    routeDotStart: {
      position: 'absolute',
      left: '6%',
      top: 42,
      width: 14,
      height: 14,
      borderRadius: 7,
      backgroundColor: colors.orange[500],
      borderWidth: 3,
      borderColor: colors.white,
    },
    routePinEnd: {
      position: 'absolute',
      right: '8%',
      top: 18,
      alignItems: 'center',
    },
    sheet: {
      backgroundColor: colors.white,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingHorizontal: 18,
      paddingTop: 10,
      shadowColor: colors.navy[900],
      shadowOpacity: 0.14,
      shadowRadius: 18,
      shadowOffset: {width: 0, height: -4},
      elevation: 20,
    },
    grabber: {
      alignSelf: 'center',
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.gray[200],
      marginBottom: 12,
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 14,
    },
    title: {
      color: colors.navy[900],
      fontSize: 24,
      fontWeight: '800',
    },
    scheduleBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.gray[100],
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 12,
    },
    scheduleText: {
      color: colors.navy[800],
      fontSize: 13,
      fontWeight: '600',
    },
    list: {
      flexGrow: 0,
      flexShrink: 1,
    },
    listContent: {
      paddingBottom: 8,
      gap: 10,
    },
    rideCard: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: colors.gray[200],
      borderRadius: 16,
      paddingVertical: 12,
      paddingHorizontal: 12,
      backgroundColor: colors.white,
    },
    rideCardActive: {
      borderColor: colors.orange[500],
      borderWidth: 2,
      backgroundColor: '#FFF8F3',
    },
    rideIconWrap: {
      width: 52,
      height: 52,
      borderRadius: 14,
      backgroundColor: colors.gray[100],
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    rideIconActive: {
      backgroundColor: colors.orange[100],
    },
    rideCopy: {
      flex: 1,
      minWidth: 0,
    },
    rideTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 6,
      marginBottom: 2,
    },
    rideTitle: {
      color: colors.navy[900],
      fontSize: 16,
      fontWeight: '700',
    },
    badge: {
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 8,
      backgroundColor: '#E8F8EF',
    },
    badgeText: {
      color: colors.green[600],
      fontSize: 11,
      fontWeight: '700',
    },
    rideMeta: {
      color: colors.gray[500],
      fontSize: 12,
      fontWeight: '500',
    },
    ridePriceCol: {
      alignItems: 'flex-end',
      marginLeft: 8,
    },
    ridePrice: {
      color: colors.navy[900],
      fontSize: 17,
      fontWeight: '800',
    },
    rideEta: {
      color: colors.gray[500],
      fontSize: 11,
      fontWeight: '500',
      marginTop: 2,
    },
    metaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.gray[200],
    },
    metaIcon: {
      width: 34,
      height: 34,
      borderRadius: 10,
      backgroundColor: colors.gray[100],
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
    metaIconPromo: {
      backgroundColor: '#E8F8EF',
    },
    metaCopy: {
      flex: 1,
      minWidth: 0,
    },
    metaText: {
      color: colors.navy[900],
      fontSize: 14,
      fontWeight: '600',
    },
    metaTextPromo: {
      color: colors.green[600],
    },
    changeText: {
      color: colors.orange[600],
      fontSize: 14,
      fontWeight: '700',
    },
    promoAmount: {
      color: colors.green[600],
      fontSize: 14,
      fontWeight: '700',
    },
    footer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      paddingTop: 12,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.gray[200],
    },
    totalCol: {
      minWidth: 72,
    },
    totalLabel: {
      color: colors.gray[500],
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.6,
    },
    totalValue: {
      color: colors.navy[900],
      fontSize: 22,
      fontWeight: '800',
      marginTop: 2,
    },
    bookBtn: {
      flex: 1,
      backgroundColor: colors.orange[500],
      borderRadius: 16,
      paddingVertical: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    bookText: {
      color: colors.white,
      fontSize: 16,
      fontWeight: '800',
    },
  });
}
