import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.slate[50],
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: colors.white,
      borderBottomWidth: 1,
      borderBottomColor: colors.slate[100],
    },
    backBtn: {
      width: 40,
      height: 40,
      justifyContent: 'center',
      alignItems: 'flex-start',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      fontSize: 17,
      fontWeight: '700',
      color: colors.text,
      marginRight: 40, // balance out back button
    },
    scroll: {
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 32,
    },
    heroSection: {
      marginBottom: 20,
    },
    overline: {
      fontSize: 12,
      fontWeight: '800',
      color: colors.orange.brand,
      letterSpacing: 0.8,
      marginBottom: 6,
      textTransform: 'uppercase',
    },
    title: {
      fontSize: 24,
      fontWeight: '800',
      color: colors.text,
      marginBottom: 8,
    },
    subtitle: {
      fontSize: 14,
      lineHeight: 20,
      color: colors.slate[500],
    },
    avatarSection: {
      alignItems: 'center',
      justifyContent: 'center',
      marginVertical: 16,
    },
    avatarWrapper: {
      position: 'relative',
      width: 96,
      height: 96,
      borderRadius: 48,
      backgroundColor: colors.blue.mutedBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarImage: {
      width: 96,
      height: 96,
      borderRadius: 48,
    },
    cameraBadge: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.orange.brand,
      borderWidth: 2.5,
      borderColor: colors.white,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.black,
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.12,
      shadowRadius: 3,
      elevation: 3,
    },
    addPhotoText: {
      marginTop: 10,
      fontSize: 15,
      fontWeight: '700',
      color: colors.orange.brand,
    },
    photoHintText: {
      marginTop: 4,
      fontSize: 13,
      color: colors.slate[500],
    },
    form: {
      marginTop: 12,
    },
    fieldGroup: {
      marginBottom: 18,
    },
    label: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 8,
    },
    requiredStar: {
      color: colors.danger,
      fontWeight: '700',
    },
    input: {
      height: 52,
      backgroundColor: colors.white,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.slate[200],
      paddingHorizontal: 16,
      fontSize: 15,
      color: colors.text,
    },
    inputFocused: {
      borderColor: colors.orange.brand,
    },
    inputIconWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      height: 52,
      backgroundColor: colors.white,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.slate[200],
      paddingHorizontal: 16,
    },
    inputWithIcon: {
      flex: 1,
      fontSize: 15,
      color: colors.text,
      paddingVertical: 0,
    },
    caption: {
      fontSize: 12.5,
      color: colors.slate[500],
      marginTop: 6,
      lineHeight: 17,
    },
    verifiedPhoneBox: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.gray.whiteOff,
      borderWidth: 1,
      borderColor: colors.slate[200],
      borderRadius: 12,
      height: 50,
      paddingHorizontal: 14,
      marginTop: 6,
      marginBottom: 12,
    },
    verifiedIconWrap: {
      marginRight: 10,
    },
    verifiedPhoneText: {
      fontSize: 13.5,
      fontWeight: '500',
      color: colors.slate[600],
    },
    footer: {
      backgroundColor: colors.white,
      paddingHorizontal: 20,
      paddingTop: 14,
      borderTopWidth: 1,
      borderTopColor: colors.slate[100],
    },
    startBtn: {
      height: 54,
      borderRadius: 14,
      backgroundColor: colors.orange.brand,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.orange.brand,
      shadowOffset: {width: 0, height: 4},
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 4,
    },
    startBtnText: {
      fontSize: 17,
      fontWeight: '700',
      color: colors.white,
    },
  });
}
