import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    keyboardContainer: {
      flex: 1,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 16,
      paddingVertical: 14,
      backgroundColor: 'transparent',
    },
    headerTitle: {
      fontFamily: colors.fonts.sora.bold,
      textAlign: 'center',
      fontSize: 17,
      color: colors.text,
    },
    scroll: {
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 24,
    },
    heroSection: {
      marginBottom: 20,
    },
    overline: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 12,
      color: colors.orange[500],
      letterSpacing: 0.8,
      marginBottom: 6,
      textTransform: 'uppercase',
    },
    title: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 24,
      color: colors.text,
      marginBottom: 8,
    },
    subtitle: {
      fontFamily: colors.fonts.sora.regular,
      fontSize: 14,
      lineHeight: 20,
      color: colors.textMuted,
    },
    avatarSection: {
      alignItems: 'center',
      justifyContent: 'center',
      marginVertical: 16,
    },
    avatarWrapper: {
      position: 'relative',
      width: 96,
      height: 96,
      borderRadius: 48,
      backgroundColor: colors.isDark ? colors.navy.cardBg : colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarImage: {
      width: 96,
      height: 96,
      borderRadius: 48,
    },
    cameraBadge: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.orange[500],
      borderWidth: 2.5,
      borderColor: colors.card,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.black,
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.12,
      shadowRadius: 3,
      elevation: 3,
    },
    addPhotoText: {
      fontFamily: colors.fonts.sora.bold,
      marginTop: 10,
      fontSize: 15,
      color: colors.orange[500],
    },
    photoHintText: {
      fontFamily: colors.fonts.sora.regular,
      marginTop: 4,
      fontSize: 13,
      color: colors.textMuted,
    },
    form: {
      marginTop: 12,
    },
    fieldGroup: {
      marginBottom: 18,
    },
    label: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 14,
      color: colors.text,
      marginBottom: 8,
    },
    labelError: {
      color: colors.danger || colors.red?.[500] || '#EF4444',
    },
    requiredStar: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.danger || colors.red?.[500] || '#EF4444',
    },
    input: {
      fontFamily: colors.fonts.sora.regular,
      height: 52,
      backgroundColor: colors.surface,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 16,
      fontSize: 15,
      color: colors.text,
    },
    inputFocused: {
      borderColor: colors.orange[500],
    },
    inputError: {
      borderColor: colors.danger || colors.red?.[500] || '#EF4444',
      borderWidth: 1.2,
    },
    inputIconWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      height: 52,
      backgroundColor: colors.surface,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 16,
    },
    inputWithIcon: {
      fontFamily: colors.fonts.sora.regular,
      flex: 1,
      fontSize: 15,
      color: colors.text,
      paddingVertical: 0,
    },
    caption: {
      fontFamily: colors.fonts.sora.regular,
      fontSize: 12.5,
      color: colors.textMuted,
      marginTop: 6,
      lineHeight: 17,
    },
    errorText: {
      fontFamily: colors.fonts.sora.regular,
      fontSize: 12.5,
      color: colors.danger || colors.red?.[500] || '#EF4444',
      marginTop: 6,
      lineHeight: 17,
    },
    genderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 2,
    },
    genderChip: {
      flex: 1,
      height: 48,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 8,
    },
    genderChipLast: {
      marginRight: 0,
    },
    genderChipActive: {
      borderColor: colors.primary,
      backgroundColor: colors.isDark ? colors.alpha?.orange20 || 'rgba(255,107,0,0.15)' : colors.orange.subtleBg,
    },
    genderChipText: {
      fontFamily: colors.fonts.sora.semiBold,
      fontSize: 14,
      color: colors.text,
    },
    genderChipTextActive: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.primary,
    },
    verifiedPhoneBox: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      height: 50,
      paddingHorizontal: 14,
      marginTop: 6,
      marginBottom: 12,
    },
    verifiedIconWrap: {
      marginRight: 10,
    },
    verifiedPhoneText: {
      fontFamily: colors.fonts.sora.medium,
      fontSize: 13.5,
      color: colors.textMuted,
    },
    footer: {
      backgroundColor: 'transparent',
      paddingHorizontal: 20,
      paddingTop: 10,
    },
    startBtn: {
      height: 54,
      borderRadius: 14,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.orange[500],
      shadowOffset: {width: 0, height: 4},
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 4,
    },
    startBtnText: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 17,
      color: colors.white,
    },
  });
}

