import { StyleSheet } from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },

    // Header Bar
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 10,
      backgroundColor: colors.background,
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    menuBtn: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.black,
      shadowOpacity: 0.06,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    headerTitle: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 28,
      fontWeight: '900',
      color: colors.text,
    },
    statementBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.black,
      shadowOpacity: 0.06,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },

    scrollContent: {
      paddingBottom: 110,
    },

    // Period Tabs (Today, Week, Month, Custom)
    periodTabsContainer: {
      flexDirection: 'row',
      backgroundColor: colors.navy[250],
      borderRadius: 18,
      padding: 4,
      marginHorizontal: 16,
      marginTop: 12,
    },
    periodTab: {
      flex: 1,
      paddingVertical: 10,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 14,
      flexDirection: 'row',
      gap: 5,
    },
    periodTabActive: {
      backgroundColor: colors.surface,
      shadowColor: colors.black,
      shadowOpacity: 0.08,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    periodTabText: {
      fontFamily: colors.fonts.sora.semiBold,
      fontSize: 13.5,
      fontWeight: '600',
      color: colors.textMuted,
    },
    periodTabTextActive: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.text,
      fontWeight: '800',
    },

    // Main Chart Card (Navy)
    chartCard: {
      backgroundColor: colors.navy[850],
      borderRadius: 24,
      padding: 20,
      marginHorizontal: 16,
      marginTop: 16,
    },
    chartHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    chartLabel: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 11.5,
      fontWeight: '700',
      color: colors.navy[350],
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    chartTrend: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 12.5,
      fontWeight: '700',
      color: colors.green[550],
    },
    netAmount: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 38,
      fontWeight: '900',
      color: colors.white,
      marginTop: 10,
      marginBottom: 16,
      letterSpacing: -0.5,
    },

    // Bar Chart
    chartContainer: {
      position: 'relative',
      height: 140,
      justifyContent: 'flex-end',
    },
    chartGridLineTop: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 36,
      height: 1,
      backgroundColor: colors.alpha.white10,
    },
    chartGridLineMid: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 72,
      height: 1,
      backgroundColor: colors.alpha.white10,
    },
    chartBaseLine: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 22,
      height: 1,
      backgroundColor: colors.alpha.white14,
    },
    barsRow: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      justifyContent: 'space-between',
      paddingHorizontal: 6,
      height: 110,
    },
    barCol: {
      alignItems: 'center',
      width: 32,
      justifyContent: 'flex-end',
      overflow: 'visible',
    },
    tooltipBadge: {
      backgroundColor: colors.primary,
      minWidth: 54,
      height: 22,
      paddingHorizontal: 8,
      borderRadius: 7,
      marginBottom: 4,
      alignSelf: 'center',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 5,
    },
    tooltipText: {
      fontFamily: colors.fonts.sora.extraBold,
      color: colors.white,
      fontSize: 11.5,
      fontWeight: '800',
      textAlign: 'center',
      includeFontPadding: false,
    },
    bar: {
      width: 26,
      backgroundColor: colors.alpha.white16,
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
    },
    barActive: {
      backgroundColor: colors.primary,
    },
    dayLabelsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 6,
      marginTop: 8,
    },
    dayLabel: {
      fontFamily: colors.fonts.sora.semiBold,
      fontSize: 11.5,
      fontWeight: '600',
      color: colors.textMuted,
      width: 32,
      textAlign: 'center',
    },
    dayLabelActive: {
      fontFamily: colors.fonts.sora.bold,
      color: colors.navy[350],
      fontWeight: '700',
    },

    // 2x2 Metric Grid
    metricGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
      marginHorizontal: 16,
      marginTop: 14,
    },
    metricCard: {
      width: '48.1%',
      backgroundColor: colors.surface,
      borderRadius: 18,
      padding: 16,
      shadowColor: colors.black,
      shadowOpacity: 0.04,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    metricTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 8,
    },
    metricTitle: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 10.5,
      fontWeight: '700',
      color: colors.textMuted,
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    metricValue: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 18.5,
      fontWeight: '900',
      color: colors.text,
      marginBottom: 4,
    },
    metricValueRed: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 18.5,
      fontWeight: '900',
      color: colors.red[600],
      marginBottom: 4,
    },
    metricValueGreen: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 18.5,
      fontWeight: '900',
      color: colors.green[600],
      marginBottom: 4,
    },
    metricSub: {
      fontFamily: colors.fonts.sora.medium,
      fontSize: 12.5,
      fontWeight: '500',
      color: colors.textMuted,
    },

    // Ride Level Earnings Section
    sectionTitle: {
      fontFamily: colors.fonts.sora.bold,
      fontSize: 11.5,
      fontWeight: '700',
      color: colors.textMuted,
      letterSpacing: 0.6,
      textTransform: 'uppercase',
      marginHorizontal: 16,
      marginTop: 22,
      marginBottom: 10,
    },
    ridesCard: {
      backgroundColor: colors.surface,
      borderRadius: 18,
      marginHorizontal: 16,
      paddingHorizontal: 16,
      shadowColor: colors.black,
      shadowOpacity: 0.04,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    rideItem: {
      paddingVertical: 14,
    },
    rideItemBorder: {
      borderBottomWidth: 1,
      borderBottomColor: colors.slate[100],
    },
    rideTopRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
    },
    rideLeft: {
      flex: 1,
      marginRight: 10,
    },
    rideTime: {
      fontFamily: colors.fonts.sora.semiBold,
      fontSize: 12,
      fontWeight: '600',
      color: colors.textMuted,
      marginBottom: 3,
    },
    rideRoute: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 14,
      fontWeight: '800',
      color: colors.text,
    },
    rideRight: {
      alignItems: 'flex-end',
    },
    rideEarning: {
      fontFamily: colors.fonts.sora.extraBold,
      fontSize: 15,
      fontWeight: '800',
      color: colors.green[700],
    },
    rideFare: {
      fontFamily: colors.fonts.sora.medium,
      fontSize: 12,
      fontWeight: '500',
      color: colors.textMuted,
      marginTop: 2,
    },
  });
}
