import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.navy[900],
    },
    mapImage: {
      ...StyleSheet.absoluteFillObject,
      width: '100%',
      height: '100%',
      zIndex: 0,
    },
    scrim: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(14, 42, 74, 0.4)',
      zIndex: 5,
      elevation: 5,
    },
    topProgressTrack: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      zIndex: 20,
      height: 4,
      backgroundColor: 'rgba(255,255,255,0.22)',
      overflow: 'hidden',
    },
    topProgressFill: {
      height: '100%',
      backgroundColor: colors.orange[600],
    },
    topBanner: {
      position: 'absolute',
      left: 16,
      // right: 16,
      zIndex: 20,
      alignItems: 'center',
    },
    autoRejectChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.orange[600],
      borderRadius: 999,
      paddingVertical: 10,
      paddingHorizontal: 14,
      shadowColor: colors.navy[900],
      shadowOpacity: 0.25,
      shadowRadius: 10,
      shadowOffset: {width: 0, height: 4},
      elevation: 8,
    },
    autoRejectText: {
      color: colors.white,
      fontSize: 13,
      fontWeight: '700',
    },
    missedChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.navy[800],
      borderRadius: 999,
      paddingVertical: 10,
      paddingHorizontal: 14,
    },
    missedChipText: {
      color: colors.white,
      fontSize: 13,
      fontWeight: '700',
    },
    mapRoute: {
      position: 'absolute',
      left: 0,
      right: 0,
      zIndex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'visible',
    },
    routeStage: {
      position: 'relative',
    },
    routePin: {
      position: 'absolute',
      width: 44,
      height: 54,
      zIndex: 3,
    },
    pickupPin: {
      width: 48,
      height: 58,
      zIndex: 5,
    },
    carMarker: {
      position: 'absolute',
      width: 54,
      height: 54,
      zIndex: 4,
    },
    sheet: {
      position: 'absolute',
      left: 16,
      right: 16,
      backgroundColor: colors.white,
      borderRadius: 28,
      paddingTop: 18,
      paddingHorizontal: 16,
      shadowColor: colors.navy[900],
      shadowOpacity: 0.18,
      shadowRadius: 16,
      shadowOffset: {width: 0, height: 8},
      elevation: 12,
      zIndex: 10,
    },
    sheetHead: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      marginBottom: 16,
    },
    timerCircle: {
      width: 56,
      height: 56,
      borderRadius: 28,
      borderWidth: 5,
      borderColor: colors.orange[600],
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.white,
    },
    timerCircleExpired: {
      borderColor: colors.gray[300],
    },
    timerText: {
      color: colors.orange[600],
      fontSize: 20,
      fontWeight: '800',
      lineHeight: 24,
      textAlign: 'center',
      includeFontPadding: false,
    },
    timerTextExpired: {
      color: colors.navy[400],
    },
    headCopy: {
      flex: 1,
      minWidth: 0,
      alignItems: 'flex-start',
      justifyContent: 'flex-start',
      paddingTop: 2,
    },
    requestKicker: {
      color: colors.orange[600],
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 0.7,
      textTransform: 'uppercase',
      textAlign: 'left',
    },
    expiredKicker: {
      color: colors.navy[400],
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 0.7,
      textTransform: 'uppercase',
      textAlign: 'left',
    },
    requestTitle: {
      color: colors.navy[900],
      fontSize: 17,
      fontWeight: '800',
      marginTop: 4,
      lineHeight: 22,
      textAlign: 'left',
    },
    expiredTitle: {
      color: colors.navy[400],
      fontSize: 16,
      fontWeight: '800',
      marginTop: 4,
      lineHeight: 21,
      textAlign: 'left',
    },
    earnWrap: {
      alignItems: 'flex-end',
      justifyContent: 'flex-start',
      paddingTop: 2,
    },
    earnLabel: {
      color: colors.navy[400],
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 0.6,
      textTransform: 'uppercase',
      textAlign: 'right',
    },
    earnValueExpired: {
      color: colors.navy[400],
    },
    earnValue: {
      color: colors.navy[900],
      fontSize: 22,
      fontWeight: '800',
      marginTop: 2,
      lineHeight: 26,
      textAlign: 'right',
    },
    divider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.gray[200],
      marginBottom: 14,
    },
    tripBlock: {
      marginBottom: 14,
    },
    tripRow: {
      flexDirection: 'row',
      alignItems: 'stretch',
      gap: 12,
    },
    tripIconCol: {
      width: 14,
      alignItems: 'center',
      paddingTop: 4,
    },
    tripCopyCol: {
      flex: 1,
      minWidth: 0,
    },
    pickupDot: {
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: colors.orange[600],
    },
    pickupDotExpired: {
      backgroundColor: colors.navy[300],
    },
    dropSquare: {
      width: 12,
      height: 12,
      borderRadius: 3,
      backgroundColor: colors.navy[900],
    },
    dropSquareExpired: {
      backgroundColor: colors.navy[300],
    },
    tripRail: {
      width: 2,
      flex: 1,
      minHeight: 28,
      backgroundColor: colors.gray[200],
      marginVertical: 2,
    },
    tripCopy: {
      minWidth: 0,
    },
    tripCopyDrop: {
      marginTop: 14,
    },
    tripLabel: {
      color: colors.navy[400],
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.4,
    },
    tripTitle: {
      color: colors.navy[900],
      fontSize: 15,
      fontWeight: '800',
      marginTop: 2,
    },
    tripTitleExpired: {
      color: colors.navy[400],
    },
    tripMeta: {
      color: colors.navy[400],
      fontSize: 12,
      marginTop: 2,
    },
    riderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      backgroundColor: colors.navy[50],
      borderRadius: 10,
      paddingVertical: 8,
      paddingHorizontal: 10,
      marginBottom: 16,
    },
    avatar: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: colors.navy[800],
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarText: {
      color: colors.white,
      fontSize: 12,
      fontWeight: '800',
    },
    riderText: {
      flex: 1,
      color: colors.navy[900],
      fontSize: 13,
      fontWeight: '700',
    },
    riderTextExpired: {
      color: colors.navy[600],
    },
    payWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 2,
    },
    payText: {
      color: colors.navy[700],
      fontSize: 13,
      fontWeight: '700',
    },
    actions: {
      flexDirection: 'row',
      alignItems: 'stretch',
      gap: 10,
      marginBottom: 12,
    },
    rejectBtn: {
      flex: 0.9,
      minHeight: 56,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: colors.gray[200],
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.white,
    },
    rejectText: {
      color: colors.navy[700],
      fontSize: 14,
      fontWeight: '800',
      letterSpacing: 0.4,
    },
    acceptBtn: {
      flex: 1.4,
      minHeight: 56,
      borderRadius: 16,
      backgroundColor: colors.orange[600],
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 12,
    },
    acceptTitle: {
      color: colors.white,
      fontSize: 16,
      fontWeight: '800',
      letterSpacing: 0.5,
    },
    acceptSub: {
      color: 'rgba(255,255,255,0.9)',
      fontSize: 12,
      fontWeight: '600',
      marginTop: 2,
    },
    backBtn: {
      minHeight: 54,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: colors.navy[800],
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.white,
      marginBottom: 12,
    },
    backBtnText: {
      color: colors.navy[800],
      fontSize: 15,
      fontWeight: '800',
    },
    footerHint: {
      color: colors.navy[400],
      fontSize: 11,
      lineHeight: 15,
      textAlign: 'center',
    },
  });
}
