import {StyleSheet} from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.map.land,
    },
    header: {
      position: 'absolute',
      left: 16,
      right: 16,
      zIndex: 5,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    menuBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.white,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.navy[900],
      shadowOpacity: 0.1,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 2},
      elevation: 3,
    },
    greetingPill: {
      flex: 1,
      backgroundColor: colors.white,
      borderRadius: 999,
      paddingVertical: 10,
      paddingHorizontal: 16,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.navy[900],
      shadowOpacity: 0.08,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 2},
      elevation: 2,
    },
    greetingKicker: {
      color: colors.gray[500],
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 1,
      textAlign: 'center',
    },
    greetingName: {
      color: colors.navy[900],
      fontSize: 15,
      fontWeight: '800',
      marginTop: 1,
      textAlign: 'center',
    },
    headerActions: {
      flexDirection: 'row',
      gap: 8,
    },
    offlineBanner: {
      position: 'absolute',
      left: 16,
      right: 16,
      zIndex: 5,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFF4D9',
      borderRadius: 999,
      paddingVertical: 12,
      paddingHorizontal: 16,
      shadowColor: colors.navy[900],
      shadowOpacity: 0.1,
      shadowRadius: 10,
      shadowOffset: {width: 0, height: 3},
      elevation: 4,
    },
    offlineIcon: {
      marginRight: 10,
    },
    offlineText: {
      flex: 1,
      color: '#9A6B12',
      fontSize: 13,
      fontWeight: '600',
      lineHeight: 18,
    },
    iconCircle: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.navy[900],
      alignItems: 'center',
      justifyContent: 'center',
    },
    badge: {
      position: 'absolute',
      top: -2,
      right: -2,
      minWidth: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: colors.red[500],
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 4,
      borderWidth: 2,
      borderColor: colors.white,
    },
    badgeText: {
      color: colors.white,
      fontSize: 10,
      fontWeight: '800',
    },
    avatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.navy[800],
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarText: {
      color: colors.white,
      fontSize: 13,
      fontWeight: '800',
    },
    locateFab: {
      position: 'absolute',
      right: 16,
      zIndex: 3,
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.white,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.navy[900],
      shadowOpacity: 0.12,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 2},
      elevation: 4,
    },
    sheetWrap: {
      position: 'absolute',
      left: 0,
      right: 0,
      zIndex: 4,
    },
    sheet: {
      backgroundColor: colors.white,
      borderTopLeftRadius: 32,
      borderTopRightRadius: 32,
      paddingTop: 10,
      paddingHorizontal: 20,
      paddingBottom: 10,
      overflow: 'hidden',
    },
    grabber: {
      alignSelf: 'center',
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.gray[200],
      marginBottom: 14,
    },
    sheetScroll: {
      paddingBottom: 4,
    },
    searchCard: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: colors.orange[500],
      borderRadius: 22,
      paddingVertical: 10,
      paddingLeft: 10,
      paddingRight: 10,
      marginBottom: 14,
      backgroundColor: colors.orange[50],
    },
    searchIconBox: {
      width: 48,
      height: 48,
      borderRadius: 14,
      backgroundColor: colors.orange[500],
      alignItems: 'center',
      justifyContent: 'center',
    },
    searchCopy: {
      flex: 1,
      paddingHorizontal: 12,
    },
    searchTitle: {
      color: colors.navy[900],
      fontSize: 20,
      fontWeight: '800',
    },
    searchSub: {
      color: colors.gray[500],
      fontSize: 13,
      marginTop: 3,
    },
    nowBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      paddingHorizontal: 12,
      paddingVertical: 9,
      borderRadius: 999,
      backgroundColor: colors.white,
      borderWidth: 1,
      borderColor: colors.gray[200],
    },
    nowText: {
      color: colors.orange[600],
      fontSize: 13,
      fontWeight: '700',
    },
    shortcuts: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 22,
      width: '100%',
    },
    shortcut: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 11,
      borderRadius: 999,
      backgroundColor: colors.navy[50],
    },
    shortcutText: {
      color: colors.navy[800],
      fontSize: 14,
      fontWeight: '600',
    },
    sectionHead: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    sectionTitle: {
      color: colors.gray[500],
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 1.2,
    },
    sectionLink: {
      color: colors.orange[600],
      fontSize: 13,
      fontWeight: '700',
    },
    exploreRow: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 22,
    },
    exploreCard: {
      flex: 1,
      backgroundColor: colors.white,
      borderRadius: 16,
      paddingVertical: 14,
      paddingHorizontal: 6,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.gray[200],
      gap: 4,
    },
    exploreCardMore: {
      backgroundColor: colors.white,
      borderColor: colors.orange[500],
    },
    exploreLabel: {
      color: colors.navy[900],
      fontSize: 13,
      fontWeight: '700',
      marginTop: 4,
    },
    exploreLabelMore: {
      color: colors.orange[600],
    },
    explorePrice: {
      color: colors.gray[500],
      fontSize: 11,
      fontWeight: '600',
    },
    explorePriceMore: {
      color: colors.orange[600],
    },
    recentRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingVertical: 12,
      marginBottom: 16,
    },
    recentIcon: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: colors.blue[100],
      alignItems: 'center',
      justifyContent: 'center',
    },
    recentCopy: {
      flex: 1,
    },
    recentTitle: {
      color: colors.navy[900],
      fontSize: 15,
      fontWeight: '700',
    },
    recentSub: {
      color: colors.gray[500],
      fontSize: 13,
      marginTop: 2,
    },
    promo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: colors.orange[50],
      borderRadius: 16,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.orange[100],
      marginBottom: 0,
    },
    promoIcon: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: colors.orange[500],
      alignItems: 'center',
      justifyContent: 'center',
    },
    promoCopy: {
      flex: 1,
    },
    promoTitle: {
      color: colors.navy[900],
      fontSize: 15,
      fontWeight: '800',
    },
    promoSub: {
      color: colors.gray[600],
      fontSize: 12,
      marginTop: 2,
    },
  });
}
